/-
Copyright (c) 2026 Scott. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Scott
-/
import Algsuperdiff.Section3.Provider.Diffusivity.Corrector.MeasurablePrereqSolutionOperator
import Algsuperdiff.Section3.Cutoff.ShellIndependence

/-!
# Sample measurability of the fresh-shell forcing, in the `L^2` carrier

The forcing of the two corrector problems `e.def.w` is `streamForcing sigmaInv
omega n m e = sigmaInv (k_m - k_n) e`, and the displays downstream of it read
the corrector gradient as an element of the `L^2` carrier over the large cube.
To speak of measurability of the corrector in the sample one first needs
measurability of the *forcing* as an `L^2`-carrier-valued map of `omega`, and
that is what this module proves.

The point that makes it provable at all is that the frozen shell carrier
`ShellField d` is topologized by the compact-open topology and carries the
associated **Borel** measurable structure
(`Algsuperdiff.Frozen.Assumptions.shellFieldBorelSpace`).  Uniform convergence
on compacta implies `L^2` convergence on a bounded cube, so the passage from a
shell field to its `L^2` class is continuous, hence Borel measurable; the
coordinates `omega |-> omega k` are measurable by construction, and the finite
stream increment is a finite sum.

## What is proved here

* `continuous_contMatrixFieldL2`: for a fixed direction `e` and a fixed triadic
  cube, the map sending a continuous matrix field `f` to the `L^2` class of
  `x |-> f(x) e` on the cube is continuous for the compact-open topology.
* `freshShellForcingL2` and `freshShellForcingL2_eq_finsetSum`: the `L^2` class
  of the forcing `-streamForcing` -- exactly the forcing the corrector displays
  quantify over -- written as a finite sum of single-shell classes.
* `measurable_freshShellForcingL2`: the forcing class is a measurable function
  of the sample.
* `measurable_freshShellForcingL2_shellIndexSigma`: the same, for the
  sub-sigma-field generated by the *fresh* shells `(n, m]` alone.  This is the
  form's parenthetical ("the latter is a function of `k_m - k_{m-h}`") needs.

## Method, and the constant

Continuity is proved as uniform continuity against CoarseGraining's ambient
uniformity.  Given a compact `K` containing the cube and an entrywise closeness
`delta` on `K`, the two `L^2` classes differ by at most

```
  |cu_K|^{1/2} d (d delta |e|)
```

-- one factor `d` from the crude passage between the ambient sup-normed carrier
`Vec d` and CoarseGraining's Euclidean carrier `HilbertVec d`, one from the
matrix-vector product, and `|cu_K|^{1/2}` from Cauchy--Schwarz on a
finite-measure set.  No sharpness is claimed or needed: only continuity is
used.

## References

* ABK26, `e.def.w` (the forcing whose class is measured).
* ABK26 (the parenthetical that the fresh-shell measurability statement serves).
-/

namespace Algsuperdiff.Section3.Provider.Diffusivity.Corrector

open Homogenization MeasureTheory
open Algsuperdiff.Frozen.Assumptions
open Algsuperdiff.Section3

noncomputable section

variable {d : ℕ}

/-! ## Elementary algebra of the matrix-vector product -/

/-- Unconditional: the matrix-vector product is continuous in the base point when
the matrix field is continuous. -/
theorem continuous_matVecMul_right (f : C(Vec d, Mat d)) (e : Vec d) :
    Continuous fun x => matVecMul (f x) e := by
  refine continuous_pi fun i => ?_
  simp only [matVecMul]
  exact continuous_finset_sum _ fun j _ =>
    (((continuous_apply j).comp ((continuous_apply i).comp f.continuous)).mul continuous_const)

/-- Unconditional: the matrix-vector product is homogeneous in the direction. -/
theorem matVecMul_smul_right (A : Mat d) (c : ℝ) (e : Vec d) :
    matVecMul A (c • e) = c • matVecMul A e := by
  funext i
  simp only [matVecMul, Pi.smul_apply, smul_eq_mul, Finset.mul_sum]
  exact Finset.sum_congr rfl fun j _ => by ring

/-- Unconditional: entrywise closeness of two matrices controls the sup norm of
the difference of the two matrix-vector products. -/
theorem norm_matVecMul_sub_le {A B : Mat d} {e : Vec d} {delta : ℝ} (hdelta : 0 ≤ delta)
    (h : ∀ i j, |A i j - B i j| ≤ delta) :
    ‖matVecMul A e - matVecMul B e‖ ≤ (d : ℝ) * delta * ‖e‖ := by
  refine (pi_norm_le_iff_of_nonneg (by positivity)).2 fun i => ?_
  have hbd : ∀ j : Fin d, |(A i j - B i j) * e j| ≤ delta * ‖e‖ := by
    intro j
    rw [abs_mul]
    exact mul_le_mul (h i j) (norm_le_pi_norm e j) (abs_nonneg _) hdelta
  have hval : (matVecMul A e - matVecMul B e) i = ∑ j, (A i j - B i j) * e j := by
    simp only [Pi.sub_apply, matVecMul, ← Finset.sum_sub_distrib]
    exact Finset.sum_congr rfl fun j _ => by ring
  calc ‖(matVecMul A e - matVecMul B e) i‖ = |∑ j, (A i j - B i j) * e j| := by rw [hval]; rfl
    _ ≤ ∑ _j : Fin d, delta * ‖e‖ :=
        (Finset.abs_sum_le_sum_abs _ _).trans (Finset.sum_le_sum fun j _ => hbd j)
    _ = (d : ℝ) * delta * ‖e‖ := by
        rw [Finset.sum_const, Finset.card_univ, Fintype.card_fin]
        simp [mul_assoc]

/-! ## Bookkeeping for the `L^2` class of a vector field -/

section ClassAlgebra

variable {U : Set (Vec d)} [IsFiniteMeasure (volumeMeasureOn U)]

omit [IsFiniteMeasure (volumeMeasureOn U)] in
/-- Unconditional: the `L^2` class depends only on the field, not on the
membership proof. -/
theorem toHilbertVectorL2OfVecField_congr {f g : Vec d → Vec d}
    (hf : MemVectorL2 U f) (hg : MemVectorL2 U g) (h : f = g) :
    toHilbertVectorL2OfVecField hf = toHilbertVectorL2OfVecField hg := by
  subst h; rfl

omit [IsFiniteMeasure (volumeMeasureOn U)] in
/-- Unconditional: the `L^2` class of a field vanishing identically is zero. -/
theorem toHilbertVectorL2OfVecField_eq_zero {G : Vec d → Vec d} (hG : MemVectorL2 U G)
    (hzero : ∀ x, G x = 0) : toHilbertVectorL2OfVecField hG = 0 := by
  have hadd : toHilbertVectorL2OfVecField hG =
      toHilbertVectorL2OfVecField hG + toHilbertVectorL2OfVecField hG := by
    rw [← toHilbertVectorL2OfVecField_add hG hG]
    exact toHilbertVectorL2OfVecField_congr hG (hG.add hG)
      (funext fun x => by simp [Pi.add_apply, hzero x])
  have hcancel : toHilbertVectorL2OfVecField hG + 0 =
      toHilbertVectorL2OfVecField hG + toHilbertVectorL2OfVecField hG := by
    simpa using hadd
  exact (add_left_cancel hcancel).symm

omit [IsFiniteMeasure (volumeMeasureOn U)] in
/-- Unconditional: the `L^2` class of a finite sum of fields is the sum of the
classes. -/
theorem toHilbertVectorL2OfVecField_finsetSum {iota : Type*} [DecidableEq iota]
    (F : iota → Vec d → Vec d) (hF : ∀ i, MemVectorL2 U (F i)) (s : Finset iota)
    {G : Vec d → Vec d} (hG : MemVectorL2 U G) (hGeq : ∀ x, G x = ∑ i ∈ s, F i x) :
    toHilbertVectorL2OfVecField hG = ∑ i ∈ s, toHilbertVectorL2OfVecField (hF i) := by
  classical
  induction s using Finset.induction_on generalizing G with
  | empty =>
      simpa using toHilbertVectorL2OfVecField_eq_zero hG (by simpa using hGeq)
  | @insert a s ha ih =>
      have hH : MemVectorL2 U (fun x => ∑ i ∈ s, F i x) :=
        memLp_finset_sum s fun i _ => hF i
      have hsplit : G = fun x => F a x + ∑ i ∈ s, F i x :=
        funext fun x => by rw [hGeq x, Finset.sum_insert ha]
      calc toHilbertVectorL2OfVecField hG
          = toHilbertVectorL2OfVecField ((hF a).add hH) :=
            toHilbertVectorL2OfVecField_congr hG ((hF a).add hH) hsplit
        _ = toHilbertVectorL2OfVecField (hF a) + toHilbertVectorL2OfVecField hH :=
            toHilbertVectorL2OfVecField_add (hF a) hH
        _ = toHilbertVectorL2OfVecField (hF a) + ∑ i ∈ s, toHilbertVectorL2OfVecField (hF i) := by
            rw [ih hH (fun _ => rfl)]
        _ = ∑ i ∈ insert a s, toHilbertVectorL2OfVecField (hF i) :=
            (Finset.sum_insert ha).symm

/-- Unconditional: a pointwise bound on the domain gives an `L^2` bound on the
class, with the crude constant `d` of the passage to CoarseGraining's Euclidean
carrier. -/
theorem norm_toHilbertVectorL2OfVecField_le_of_bound_on (hU : MeasurableSet U)
    {f : Vec d → Vec d} (hf : MemVectorL2 U f) {C : ℝ} (hC : 0 ≤ C)
    (hb : ∀ x ∈ U, ‖f x‖ ≤ C) :
    ‖toHilbertVectorL2OfVecField hf‖ ≤
      ((volumeMeasureOn U) Set.univ).toReal ^ ((2 : ℝ)⁻¹) * ((d : ℝ) * C) := by
  have hae : ∀ᵐ x ∂(volumeMeasureOn U), ‖hilbertifyVecField f x‖ ≤ (d : ℝ) * C := by
    rw [volumeMeasureOn, MeasureTheory.ae_restrict_iff' hU]
    filter_upwards with x hx
    exact le_trans (HilbertVec.norm_ofVec_le_mul_norm (f x))
      (mul_le_mul_of_nonneg_left (hb x hx) (by positivity))
  have hnorm : ‖toHilbertVectorL2OfVecField hf‖ =
      (eLpNorm (hilbertifyVecField f) 2 (volumeMeasureOn U)).toReal := by
    rw [toHilbertVectorL2OfVecField, toHilbertVectorL2, MeasureTheory.Lp.norm_toLp]
  have hbound := MeasureTheory.eLpNorm_le_of_ae_bound (p := (2 : ENNReal)) hae
  have hfin : ((volumeMeasureOn U) Set.univ) ^ ((2 : ENNReal).toReal)⁻¹ *
      ENNReal.ofReal ((d : ℝ) * C) ≠ ⊤ :=
    ENNReal.mul_ne_top
      (ENNReal.rpow_ne_top_of_nonneg (by positivity)
        (measure_ne_top (volumeMeasureOn U) Set.univ))
      ENNReal.ofReal_ne_top
  rw [hnorm]
  refine le_trans (ENNReal.toReal_mono hfin hbound) ?_
  rw [ENNReal.toReal_mul, ENNReal.toReal_rpow, ENNReal.toReal_ofReal (by positivity)]
  norm_num

end ClassAlgebra

/-! ## Entrywise entourages of the matrix carrier -/

/-- Unconditional: entrywise closeness cuts out an entourage of the ambient
matrix carrier. -/
theorem matrixEntrywiseEntourage_mem_uniformity {delta : ℝ} (hdelta : 0 < delta) :
    {p : Mat d × Mat d | ∀ i j, |p.1 i j - p.2 i j| < delta} ∈ uniformity (Mat d) := by
  have hstep : ∀ i j : Fin d,
      {p : Mat d × Mat d | |p.1 i j - p.2 i j| < delta} ∈ uniformity (Mat d) := by
    intro i j
    have hc : UniformContinuous fun A : Mat d => A i j :=
      (Pi.uniformContinuous_proj (fun _ : Fin d => ℝ) j).comp
        (Pi.uniformContinuous_proj (fun _ : Fin d => (Fin d → ℝ)) i)
    simpa [Real.dist_eq] using hc (Metric.dist_mem_uniformity hdelta)
  have hEq : {p : Mat d × Mat d | ∀ i j, |p.1 i j - p.2 i j| < delta} =
      ⋂ i : Fin d, ⋂ j : Fin d, {p : Mat d × Mat d | |p.1 i j - p.2 i j| < delta} := by
    ext p; simp
  rw [hEq]
  exact Filter.iInter_mem.2 fun i => Filter.iInter_mem.2 fun j => hstep i j

/-! ## The `L^2` class of a continuous matrix field, and its continuity -/

/-- Unconditional: the `L^2` class on the open triadic cube `Q` of the vector
field `x |-> f(x) e` attached to a continuous matrix field `f`. -/
def contMatrixFieldL2 (Q : TriadicCube d) (e : Vec d) (f : C(Vec d, Mat d)) :
    HilbertVectorL2 (openCubeSet Q) :=
  toHilbertVectorL2OfVecField
    (memVectorL2_openCubeSet_of_continuous Q (continuous_matVecMul_right f e))

/-- Unconditional: **the passage from a continuous matrix field to its `L^2`
class on a cube is continuous** for the compact-open topology.

This is the transfer that makes a Borel-measurable shell field produce a
Borel-measurable `L^2` class, and hence the whole measurability chain of the
corrector. -/
theorem continuous_contMatrixFieldL2 (Q : TriadicCube d) (e : Vec d) :
    Continuous (contMatrixFieldL2 Q e) := by
  obtain ⟨R, hR, hball⟩ := (isOpenBoundedConvexDomain_openCubeSet Q).2.1
  have hKcpt : IsCompact (Metric.closedBall (0 : Vec d) R) := isCompact_closedBall _ _
  have hUK : openCubeSet Q ⊆ Metric.closedBall (0 : Vec d) R := by
    intro x hx
    simp only [Metric.mem_closedBall, dist_zero_right]
    exact (pi_norm_le_iff_of_nonneg hR.le).2 fun i => by
      simpa [Real.norm_eq_abs] using hball x hx i
  haveI : IsFiniteMeasure (volumeMeasureOn (openCubeSet Q)) :=
    isFiniteMeasure_volumeMeasureOn_openCubeSet Q
  set A : ℝ := ((volumeMeasureOn (openCubeSet Q)) Set.univ).toReal ^ ((2 : ℝ)⁻¹) *
    ((d : ℝ) * ((d : ℝ) * ‖e‖)) with hAdef
  have hA : 0 ≤ A := by
    rw [hAdef]; positivity
  refine UniformContinuous.continuous ?_
  rw [uniformContinuous_def]
  intro V hV
  obtain ⟨eps, heps, hepsV⟩ := Metric.mem_uniformity_dist.1 hV
  have hdelta : 0 < eps / (A + 1) := by positivity
  refine (ContinuousMap.mem_compactConvergence_entourage_iff _).2
    ⟨Metric.closedBall (0 : Vec d) R,
      {p : Mat d × Mat d | ∀ i j, |p.1 i j - p.2 i j| < eps / (A + 1)}, hKcpt,
      matrixEntrywiseEntourage_mem_uniformity hdelta, ?_⟩
  rintro ⟨f, g⟩ hfg
  refine hepsV ?_
  have hf : MemVectorL2 (openCubeSet Q) (fun x => matVecMul (f x) e) :=
    memVectorL2_openCubeSet_of_continuous Q (continuous_matVecMul_right f e)
  have hg : MemVectorL2 (openCubeSet Q) (fun x => matVecMul (g x) e) :=
    memVectorL2_openCubeSet_of_continuous Q (continuous_matVecMul_right g e)
  have hpoint : ∀ x ∈ openCubeSet Q,
      ‖(fun y => matVecMul (f y) e) x - (fun y => matVecMul (g y) e) x‖ ≤
        (d : ℝ) * (eps / (A + 1)) * ‖e‖ := by
    intro x hx
    exact norm_matVecMul_sub_le hdelta.le fun i j => (hfg x (hUK hx) i j).le
  have hstep :
      ‖contMatrixFieldL2 Q e f - contMatrixFieldL2 Q e g‖ ≤ A * (eps / (A + 1)) := by
    have hsub : contMatrixFieldL2 Q e f - contMatrixFieldL2 Q e g =
        toHilbertVectorL2OfVecField (hf.sub hg) :=
      (toHilbertVectorL2OfVecField_sub hf hg).symm
    rw [hsub]
    refine le_trans
      (norm_toHilbertVectorL2OfVecField_le_of_bound_on (measurableSet_openCubeSet Q)
        (hf.sub hg) (by positivity) hpoint) ?_
    refine le_of_eq ?_
    rw [hAdef]; ring
  have hfinal : A * (eps / (A + 1)) < eps := by
    rw [mul_div_assoc', div_lt_iff₀ (by positivity)]
    nlinarith
  rw [dist_eq_norm]
  exact lt_of_le_of_lt hstep hfinal

/-! ## The fresh-shell forcing class and its measurability -/

/-- Unconditional: the `L^2` class on `cu_K` of the forcing `-streamForcing` of
`e.def.w`, i.e. of the exact right-hand side the corrector displays carry. -/
def freshShellForcingL2 (Q : TriadicCube d) (sigmaInv : ℝ) (n m : ℤ) (e : Vec d)
    (omega : Cutoff.ShellSeq d) : HilbertVectorL2 (openCubeSet Q) :=
  toHilbertVectorL2OfVecField
    (memVectorL2_openCubeSet_of_continuous Q
      (continuous_streamForcing sigmaInv omega n m e).neg)

/-- Unconditional: the forcing class is the finite sum, over the fresh shell
range `(n, m]`, of the single-shell classes in the direction `-sigmaInv e`. -/
theorem freshShellForcingL2_eq_finsetSum (Q : TriadicCube d) (sigmaInv : ℝ) (n m : ℤ)
    (e : Vec d) (omega : Cutoff.ShellSeq d) :
    freshShellForcingL2 Q sigmaInv n m e omega =
      ∑ k ∈ Finset.Ioc n m, contMatrixFieldL2 Q ((-sigmaInv) • e) ((omega k).1.1) := by
  haveI : IsFiniteMeasure (volumeMeasureOn (openCubeSet Q)) :=
    isFiniteMeasure_volumeMeasureOn_openCubeSet Q
  classical
  refine toHilbertVectorL2OfVecField_finsetSum
    (fun k : ℤ => fun x => matVecMul (((omega k).1.1) x) ((-sigmaInv) • e))
    (fun k => memVectorL2_openCubeSet_of_continuous Q
      (continuous_matVecMul_right ((omega k).1.1) ((-sigmaInv) • e)))
    (Finset.Ioc n m) _ ?_
  intro x
  have hincrement : (Cutoff.finiteShellIncrement omega n m x : Mat d) =
      ∑ k ∈ Finset.Ioc n m, ((omega k).1.1) x := by
    rw [Cutoff.finiteShellIncrement_apply]
    rfl
  have hsum : matVecMul (∑ k ∈ Finset.Ioc n m, ((omega k).1.1) x) e =
      ∑ k ∈ Finset.Ioc n m, matVecMul (((omega k).1.1) x) e := by
    funext i
    simp only [matVecMul, Matrix.sum_apply, Finset.sum_apply, Finset.sum_mul]
    exact Finset.sum_comm
  calc (fun y => -streamForcing sigmaInv omega n m e y) x
      = -(sigmaInv • matVecMul (Cutoff.finiteShellIncrement omega n m x) e) := rfl
    _ = ∑ k ∈ Finset.Ioc n m, matVecMul (((omega k).1.1) x) ((-sigmaInv) • e) := by
        rw [hincrement, hsum, Finset.smul_sum, ← Finset.sum_neg_distrib]
        exact Finset.sum_congr rfl fun k _ => by
          rw [matVecMul_smul_right, neg_smul]

/-- Unconditional: the value of a frozen shell field, read as a continuous
matrix field, depends continuously on the shell. -/
theorem continuous_shellFieldToContMap :
    Continuous fun j : ShellField d => (j.1.1 : C(Vec d, Mat d)) :=
  continuous_fst.comp continuous_subtype_val

/-- Unconditional: a single shell contributes a measurable `L^2` class. -/
theorem measurable_shellFieldContMatrixFieldL2 (Q : TriadicCube d) (e : Vec d) :
    Measurable fun j : ShellField d => contMatrixFieldL2 Q e (j.1.1) :=
  ((continuous_contMatrixFieldL2 Q e).comp continuous_shellFieldToContMap).measurable

/-- Unconditional: **the forcing class is a measurable function of the sample.**

No selection and no measurability hypothesis enters: the shells are Borel
measurable coordinates of the sample by construction, and the passage to the
`L^2` class is continuous. -/
theorem measurable_freshShellForcingL2 (Q : TriadicCube d) (sigmaInv : ℝ) (n m : ℤ)
    (e : Vec d) :
    Measurable (freshShellForcingL2 Q sigmaInv n m e) := by
  haveI : Fact ((2 : ENNReal) ≠ ⊤) := ⟨by simp⟩
  haveI : IsFiniteMeasure (volumeMeasureOn (openCubeSet Q)) :=
    isFiniteMeasure_volumeMeasureOn_openCubeSet Q
  have hEq : freshShellForcingL2 Q sigmaInv n m e =
      fun omega : Cutoff.ShellSeq d =>
        ∑ k ∈ Finset.Ioc n m, contMatrixFieldL2 Q ((-sigmaInv) • e) ((omega k).1.1) :=
    funext fun omega => freshShellForcingL2_eq_finsetSum Q sigmaInv n m e omega
  rw [hEq]
  exact Finset.measurable_sum (Finset.Ioc n m) fun k _ =>
    (measurable_shellFieldContMatrixFieldL2 Q ((-sigmaInv) • e)).comp (measurable_pi_apply k)

/-- Unconditional: **the forcing class is measurable for the fresh shells alone.**
This is the literal content's parenthetical, "the latter is a function of `k_m
- k_{m-h}`", at the level of the forcing. -/
theorem measurable_freshShellForcingL2_shellIndexSigma (Q : TriadicCube d) (sigmaInv : ℝ)
    (n m : ℤ) (e : Vec d) :
    @Measurable (Cutoff.ShellSeq d) (HilbertVectorL2 (openCubeSet Q))
      (Cutoff.shellIndexSigma (Set.Ioc n m)) inferInstance
      (freshShellForcingL2 Q sigmaInv n m e) := by
  haveI : Fact ((2 : ENNReal) ≠ ⊤) := ⟨by simp⟩
  haveI : IsFiniteMeasure (volumeMeasureOn (openCubeSet Q)) :=
    isFiniteMeasure_volumeMeasureOn_openCubeSet Q
  have hshell : ∀ k ∈ Finset.Ioc n m,
      @Measurable (Cutoff.ShellSeq d) (HilbertVectorL2 (openCubeSet Q))
        (Cutoff.shellIndexSigma (Set.Ioc n m)) inferInstance
        (fun omega => contMatrixFieldL2 Q ((-sigmaInv) • e) ((omega k).1.1)) := fun k hk =>
    (measurable_shellFieldContMatrixFieldL2 Q ((-sigmaInv) • e)).comp
      (Cutoff.measurable_shellCoordinate_shellIndexSigma (by simpa using hk))
  have hEq : freshShellForcingL2 Q sigmaInv n m e =
      fun omega : Cutoff.ShellSeq d =>
        ∑ k ∈ Finset.Ioc n m, contMatrixFieldL2 Q ((-sigmaInv) • e) ((omega k).1.1) :=
    funext fun omega => freshShellForcingL2_eq_finsetSum Q sigmaInv n m e omega
  rw [hEq]
  exact Finset.measurable_sum (Finset.Ioc n m) hshell

end

end Algsuperdiff.Section3.Provider.Diffusivity.Corrector
