/-
Copyright (c) 2026 Scott. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Scott
-/
import Algsuperdiff.Section3.Provider.Diffusivity.Corrector.CorrectorMeasurableForcing

/-!
# Sample measurability of the finite-volume correctors of `e.def.w`

This module proves the fact the development has been carrying as an
undischarged side condition on three fronts: **the gradient of the
finite-volume corrector is a measurable function of the sample**, with no
measurability hypothesis on the corrector family and no measurable-selection
argument.

The statement quantifies over an *arbitrary* family `omega |-> w(omega)` of weak
solutions, exactly as the corrector displays do.  That is possible because of
`MeasurablePrereqSolutionOperator`: the gradient of a weak solution is not
merely *some* element produced by choice, it is the value at the forcing class
of a fixed continuous operator.  Composing that operator with the measurable
forcing class of `CorrectorMeasurableForcing` gives measurability of the
gradient, and hence of every continuous functional of it.

## What is proved here

* `measurable_freshShellDirichletGradL2`, `measurable_freshShellNeumannGradL2`:
  for any family of Dirichlet (resp. mean-zero Neumann) weak solutions of the
  fresh-shell problems on the cube, the map
  `omega |-> grad w(omega)` into the Hilbert `L^2` carrier is measurable.
* `measurable_shellIndexSigma_freshShellDirichletGradL2` and its Neumann
  mirror: the same, for the sub-sigma-field generated by the fresh shells `(n,
  m]` alone.  This is's parenthetical for the corrector itself.
* `measurable_setIntegral_gradCoordL2`: for *any* measurable family of `L^2`
  classes on the cube, every coordinate set integral
  `omega |-> int_S (F omega)_i` over a measurable subset `S` is measurable,
  because it is a continuous linear functional of the class.  Composed with the
  two gradient statements above, in either sigma-field, this gives the linear
  corrector observables the principal-response leg reads.

## What is not proved here

Measurability of the *quartic* observables -- `cubeFourthEnergy` and
`meshFourthEnergyCell` of `LocalizationOverlapCoarse` -- does **not** follow from
the statements above, because `F |-> int |F|^4` is not a continuous functional of
an `L^2` class.  It is Borel measurable (it is lower semicontinuous, by Fatou
along an almost-everywhere convergent subsequence, or equivalently a countable
supremum of continuous truncated functionals), but that argument is not carried
out here and the corresponding binders are left standing.  Likewise the
quadratic window observables `meshEnergyCell` and `meshOscillationCell` need the
restriction map to a subwindow, which is not built here.

## References

* ABK26, `e.def.w`.
* ABK26 (the fresh-shell measurability parenthetical).
-/

namespace Algsuperdiff.Section3.Provider.Diffusivity.Corrector

open Homogenization MeasureTheory
open Algsuperdiff.Section3

noncomputable section

variable {d : ℕ}

/-! ## The two gradient measurability statements -/

/-- Unconditional: **the Dirichlet corrector gradient is measurable in the
sample.**

`wD` is an arbitrary family of zero-trace weak solutions of the fresh-shell
Dirichlet problem `e.def.w` on `cu_K = Q`; no measurability, no continuity and
no selection property of the family is assumed.  The conclusion is
measurability of the gradient in CoarseGraining's Hilbert `L^2` carrier. -/
theorem measurable_freshShellDirichletGradL2 [NeZero d] (Q : TriadicCube d)
    (sigmaInv : ℝ) (n m : ℤ) (e : Vec d)
    (wD : Cutoff.ShellSeq d → H10Function (openCubeSet Q))
    (hwD : ∀ omega : Cutoff.ShellSeq d,
      IsZeroTraceDirichletRhsWeakSolution
        (fun _ : Vec d => (1 : Matrix (Fin d) (Fin d) ℝ))
        (openCubeSet Q) (wD omega)
        (fun x => -streamForcing sigmaInv omega n m e x)) :
    Measurable fun omega => (wD omega).toH1Function.gradToHilbertVectorL2 := by
  haveI : IsFiniteMeasure (volumeMeasureOn (openCubeSet Q)) :=
    isFiniteMeasure_volumeMeasureOn_openCubeSet Q
  have hEq : (fun omega => (wD omega).toH1Function.gradToHilbertVectorL2) =
      (dirichletGradientOfForcingClass
          (PotentialSolenoidalL2Data.ofSubmoduleClosures (openCubeSet Q))
          (_root_.Algsuperdiff.Section3.Provider.Corrector.nonempty_openCubeSet Q)
          (isEllipticFieldOn_const_one_openCubeSet Q)) ∘
        freshShellForcingL2 Q sigmaInv n m e := by
    funext omega
    exact gradToHilbertVectorL2_eq_dirichletGradientOfForcingClass
      (memVectorL2_openCubeSet_of_continuous Q
        (continuous_streamForcing sigmaInv omega n m e).neg)
      (_root_.Algsuperdiff.Section3.Provider.Corrector.hasPotentialZeroTraceClosureRealization_openCubeSet Q)
      (_root_.Algsuperdiff.Section3.Provider.Corrector.nonempty_openCubeSet Q)
      (isEllipticFieldOn_const_one_openCubeSet Q) (hwD omega)
  rw [hEq]
  exact (continuous_dirichletGradientOfForcingClass _ _ _).measurable.comp
    (measurable_freshShellForcingL2 Q sigmaInv n m e)

/-- Unconditional: **the Neumann corrector gradient is measurable in the
sample.**  The mean-zero Neumann mirror of the previous statement. -/
theorem measurable_freshShellNeumannGradL2 (Q : TriadicCube d)
    (sigmaInv : ℝ) (n m : ℤ) (e : Vec d)
    (wN : Cutoff.ShellSeq d → H1MeanZeroFunction (openCubeSet Q))
    (hwN : ∀ omega : Cutoff.ShellSeq d,
      IsMeanZeroNeumannRhsWeakSolution
        (fun _ : Vec d => (1 : Matrix (Fin d) (Fin d) ℝ))
        (openCubeSet Q) (wN omega)
        (fun x => -streamForcing sigmaInv omega n m e x)) :
    Measurable fun omega => (wN omega).gradToHilbertVectorL2 := by
  haveI : IsFiniteMeasure (volumeMeasureOn (openCubeSet Q)) :=
    isFiniteMeasure_volumeMeasureOn_openCubeSet Q
  have hEq : (fun omega => (wN omega).gradToHilbertVectorL2) =
      (neumannGradientOfForcingClass (U := openCubeSet Q)
          (a := fun _ : Vec d => (1 : Matrix (Fin d) (Fin d) ℝ)) (lam := 1) (Lam := 1)
          (translatedCubeMeanZeroH1CoerciveEstimate Q)
          (_root_.Algsuperdiff.Section3.Provider.Corrector.nonempty_openCubeSet Q)
          (isEllipticFieldOn_const_one_openCubeSet Q)) ∘
        freshShellForcingL2 Q sigmaInv n m e := by
    funext omega
    exact gradToHilbertVectorL2_eq_neumannGradientOfForcingClass
      (memVectorL2_openCubeSet_of_continuous Q
        (continuous_streamForcing sigmaInv omega n m e).neg)
      (translatedCubeMeanZeroH1CoerciveEstimate Q)
      (_root_.Algsuperdiff.Section3.Provider.Corrector.nonempty_openCubeSet Q)
      (isEllipticFieldOn_const_one_openCubeSet Q) (hwN omega)
  rw [hEq]
  exact (continuous_neumannGradientOfForcingClass _ _ _).measurable.comp
    (measurable_freshShellForcingL2 Q sigmaInv n m e)

/-! ## The fresh-shell sub-sigma-field -/

/-- Unconditional: **the Dirichlet corrector gradient is measurable for the fresh
shells alone.**  This is the corrector-level form's parenthetical "the latter
is a function of `k_m - k_{m-h}`". -/
theorem measurable_shellIndexSigma_freshShellDirichletGradL2 [NeZero d] (Q : TriadicCube d)
    (sigmaInv : ℝ) (n m : ℤ) (e : Vec d)
    (wD : Cutoff.ShellSeq d → H10Function (openCubeSet Q))
    (hwD : ∀ omega : Cutoff.ShellSeq d,
      IsZeroTraceDirichletRhsWeakSolution
        (fun _ : Vec d => (1 : Matrix (Fin d) (Fin d) ℝ))
        (openCubeSet Q) (wD omega)
        (fun x => -streamForcing sigmaInv omega n m e x)) :
    @Measurable (Cutoff.ShellSeq d) (HilbertVectorL2 (openCubeSet Q))
      (Cutoff.shellIndexSigma (Set.Ioc n m)) inferInstance
      (fun omega => (wD omega).toH1Function.gradToHilbertVectorL2) := by
  haveI : IsFiniteMeasure (volumeMeasureOn (openCubeSet Q)) :=
    isFiniteMeasure_volumeMeasureOn_openCubeSet Q
  have hEq : (fun omega => (wD omega).toH1Function.gradToHilbertVectorL2) =
      (dirichletGradientOfForcingClass
          (PotentialSolenoidalL2Data.ofSubmoduleClosures (openCubeSet Q))
          (_root_.Algsuperdiff.Section3.Provider.Corrector.nonempty_openCubeSet Q)
          (isEllipticFieldOn_const_one_openCubeSet Q)) ∘
        freshShellForcingL2 Q sigmaInv n m e := by
    funext omega
    exact gradToHilbertVectorL2_eq_dirichletGradientOfForcingClass
      (memVectorL2_openCubeSet_of_continuous Q
        (continuous_streamForcing sigmaInv omega n m e).neg)
      (_root_.Algsuperdiff.Section3.Provider.Corrector.hasPotentialZeroTraceClosureRealization_openCubeSet Q)
      (_root_.Algsuperdiff.Section3.Provider.Corrector.nonempty_openCubeSet Q)
      (isEllipticFieldOn_const_one_openCubeSet Q) (hwD omega)
  rw [hEq]
  exact (continuous_dirichletGradientOfForcingClass _ _ _).measurable.comp
    (measurable_freshShellForcingL2_shellIndexSigma Q sigmaInv n m e)

/-- Unconditional: **the Neumann corrector gradient is measurable for the fresh
shells alone.** -/
theorem measurable_shellIndexSigma_freshShellNeumannGradL2 (Q : TriadicCube d)
    (sigmaInv : ℝ) (n m : ℤ) (e : Vec d)
    (wN : Cutoff.ShellSeq d → H1MeanZeroFunction (openCubeSet Q))
    (hwN : ∀ omega : Cutoff.ShellSeq d,
      IsMeanZeroNeumannRhsWeakSolution
        (fun _ : Vec d => (1 : Matrix (Fin d) (Fin d) ℝ))
        (openCubeSet Q) (wN omega)
        (fun x => -streamForcing sigmaInv omega n m e x)) :
    @Measurable (Cutoff.ShellSeq d) (HilbertVectorL2 (openCubeSet Q))
      (Cutoff.shellIndexSigma (Set.Ioc n m)) inferInstance
      (fun omega => (wN omega).gradToHilbertVectorL2) := by
  haveI : IsFiniteMeasure (volumeMeasureOn (openCubeSet Q)) :=
    isFiniteMeasure_volumeMeasureOn_openCubeSet Q
  have hEq : (fun omega => (wN omega).gradToHilbertVectorL2) =
      (neumannGradientOfForcingClass (U := openCubeSet Q)
          (a := fun _ : Vec d => (1 : Matrix (Fin d) (Fin d) ℝ)) (lam := 1) (Lam := 1)
          (translatedCubeMeanZeroH1CoerciveEstimate Q)
          (_root_.Algsuperdiff.Section3.Provider.Corrector.nonempty_openCubeSet Q)
          (isEllipticFieldOn_const_one_openCubeSet Q)) ∘
        freshShellForcingL2 Q sigmaInv n m e := by
    funext omega
    exact gradToHilbertVectorL2_eq_neumannGradientOfForcingClass
      (memVectorL2_openCubeSet_of_continuous Q
        (continuous_streamForcing sigmaInv omega n m e).neg)
      (translatedCubeMeanZeroH1CoerciveEstimate Q)
      (_root_.Algsuperdiff.Section3.Provider.Corrector.nonempty_openCubeSet Q)
      (isEllipticFieldOn_const_one_openCubeSet Q) (hwN omega)
  rw [hEq]
  exact (continuous_neumannGradientOfForcingClass _ _ _).measurable.comp
    (measurable_freshShellForcingL2_shellIndexSigma Q sigmaInv n m e)

/-! ## Scalar corollaries -/

/-- Unconditional: a coordinate set integral of a gradient class over a
measurable subset of the cube is a continuous, hence measurable, functional. -/
theorem measurable_setIntegral_gradCoordL2 (Q : TriadicCube d) {Omega : Type*}
    {mOmega : MeasurableSpace Omega} {S : Set (Vec d)} (hS : MeasurableSet S) (i : Fin d)
    {F : Omega → HilbertVectorL2 (openCubeSet Q)} (hF : Measurable F) :
    Measurable fun omega =>
      ∫ x in S, (F omega) x i ∂(volumeMeasureOn (openCubeSet Q)) := by
  haveI : IsFiniteMeasure (volumeMeasureOn (openCubeSet Q)) :=
    isFiniteMeasure_volumeMeasureOn_openCubeSet Q
  have hEq : (fun omega =>
      ∫ x in S, (F omega) x i ∂(volumeMeasureOn (openCubeSet Q))) =
      (hilbertVectorL2CoordSetIntegralCLM (U := openCubeSet Q) S hS i) ∘ F := by
    funext omega
    exact (hilbertVectorL2CoordSetIntegralCLM_apply (U := openCubeSet Q) S hS i (F omega)).symm
  rw [hEq]
  exact (hilbertVectorL2CoordSetIntegralCLM (U := openCubeSet Q) S hS i).continuous.measurable.comp
    hF

end

end Algsuperdiff.Section3.Provider.Diffusivity.Corrector
