import Algsuperdiff.Section3.Provider.Percolation.ColoredConcentration
import Algsuperdiff.Section3.Provider.Percolation.SiteFamilyBridge
import Algsuperdiff.Section3.Probability.TwoTermOrlicz

/-!
# Finite-range concentration for cube-local families at the genuine cutoff law

ABK26 states, immediately after Proposition `p.concentration`, the spatial
corollary used in the proof of Proposition `p.homogenization.step`: if the
family `{X_z}_{z ∈ 3^n ℤ^d ∩ □_m}` is centered, each member is `O_{Γ_σ}(K)`, and
two members are independent whenever the corresponding subcubes do not touch,
then the *average* over the grid is `O_{Γ_σ}(^{-d(m-n)/2} K)`.

This module proves a strengthened-hypothesis form of that corollary on the
**genuine** cutoff sample law
`Cutoff.cutoffSampleLaw M`, for families whose members read only the
integral-local information of their own cube tree.  Three steps:

1. *Finite range.*  `Cutoff.indep_cutoffSampleLocalSigma_of_indep_completion`
   together with `Cutoff.indep_lowerShellLocalCompletion_of_cutoff_separation`
   already give the **two-set** independence of the cutoff-sample local
   σ-fields of two Euclidean-separated regions.  `IndepChain`'s statements are
   tied to `Percolation.siteSigma`, which is generated by set-valued events and
   cannot express these comap σ-fields, so the induction is repeated here
   rather than reused; see also `Percolation.ColoredConcentration`, which
   Section `Concentration` mirrors for the same reason.

2. *Colouring.*  Section `Concentration` runs the residue colouring of
   `Percolation.Coloring` at range `3 ^ sepShift d`, applies CoarseGraining's
   centered independent-sum inequality inside each colour class, and recombines
   the classes with CoarseGraining's finite-average triangle inequality.  This
   mirrors `Percolation.ColoredConcentration`, whose σ-fields are generated by
   set-valued bad events and therefore cannot carry a real-valued functional of
   the coefficient field.

3. *Grid form.*  Section `Grid` specializes the site set to the lattice points
   `Percolation.cubeFinset (m - n)` of `□_m` at spacing `3 ^ n`, i.e. to
   `3^n ℤ^d ∩ □_m`, where the recombined amplitude is literally
   `C(d, σ) · 3 ^ (-d(m-n)/2) · K`, and assembles two lanes into the
   `Probability.IsTwoTermBigOWith` shape used by the Section 3.5 frozen
   statements.

## References

* ABK26, Proposition `p.concentration` and its spatial corollary.
* ABK26, Proposition `p.homogenization.step`.
-/

namespace Algsuperdiff.Section3.Provider.Homogenization

open MeasureTheory ProbabilityTheory
open _root_.Homogenization _root_.Homogenization.Book
open _root_.Homogenization.IndependentSums
open Algsuperdiff.Section3.Cutoff
open Algsuperdiff.Section3.Provider.BadEvents
open Algsuperdiff.Section3.Provider.Percolation

noncomputable section

variable {d : ℕ}

/-! ## Independence -/

section Independence

/-- The observation region of a site family is monotone in the site set. -/
theorem siteRegion_mono (base : ℤ) {S T : Set (Fin d → ℤ)} (hST : S ⊆ T) :
    siteRegion base S ⊆ siteRegion base T :=
  Set.iUnion₂_subset fun _ hu => cubeTreeRegion_subset_siteRegion (hST hu)

/-- **The two-set finite-range input at the genuine cutoff law.**

Two site families at sup-lattice separation more than `3 ^ sepShift d`, read at
cube scale `n`, generate integral-local information of the cutoff `a_L` on two
regions whose Euclidean separation is at least the literal cutoff range `√d · 3
^ L`, provided `L ≤ n`.  The proved cutoff range theorem then supplies the
independence.  Nothing is assumed beyond the standing model. -/
theorem indep_cutoffSampleLocalSigma_siteRegion_of_latDist_sep
    (M : ABKModel d) {L n : ℤ} (hLn : L ≤ n) (S T : Set (Fin d → ℤ))
    (hsep : ∀ u ∈ S, ∀ v ∈ T, 3 ^ sepShift d < latDist u v) :
    Indep (cutoffSampleLocalSigma M L (siteRegion n S))
      (cutoffSampleLocalSigma M L (siteRegion n T))
      (cutoffSampleLaw M).toMeasure := by
  have hd : 0 < d := lt_of_lt_of_le (by omega) M.shellPrefix.dimension
  have hEuclid : ∀ ⦃x y : Vec d⦄, x ∈ siteRegion n S → y ∈ siteRegion n T →
      Real.sqrt (d : ℝ) * (3 : ℝ) ^ L ≤ Homogenization.Book.Ch02.vecNorm (x - y) := by
    intro x y hx hy
    obtain ⟨u, hu, hxu⟩ := Set.mem_iUnion₂.1 hx
    obtain ⟨v, hv, hyv⟩ := Set.mem_iUnion₂.1 hy
    have hlatNat : (3 : ℕ) ^ sepShift d + 1 ≤ latDist u v := hsep u hu v hv
    have hlat : (3 : ℝ) ^ sepShift d + 1 ≤ ((latDist u v : ℕ) : ℝ) := by
      calc (3 : ℝ) ^ sepShift d + 1 = (((3 : ℕ) ^ sepShift d + 1 : ℕ) : ℝ) := by
            push_cast; ring
        _ ≤ ((latDist u v : ℕ) : ℝ) := by exact_mod_cast hlatNat
    have hsqrtLe : Real.sqrt (d : ℝ) ≤ ((latDist u v : ℕ) : ℝ) - 1 := by
      have := sqrt_le_three_pow_sepShift (d := d)
      linarith
    have hregion := vecNorm_sub_ge_of_mem_cubeTreeRegion hd n hxu hyv
    have hnpos : (0 : ℝ) < (3 : ℝ) ^ n := zpow_pos (by norm_num) _
    have hmono : (3 : ℝ) ^ L ≤ (3 : ℝ) ^ n :=
      zpow_le_zpow_right₀ (by norm_num) hLn
    have hstep₁ : Real.sqrt (d : ℝ) * (3 : ℝ) ^ L ≤ Real.sqrt (d : ℝ) * (3 : ℝ) ^ n :=
      mul_le_mul_of_nonneg_left hmono (Real.sqrt_nonneg _)
    have hstep₂ : Real.sqrt (d : ℝ) * (3 : ℝ) ^ n ≤
        (((latDist u v : ℕ) : ℝ) - 1) * (3 : ℝ) ^ n :=
      mul_le_mul_of_nonneg_right hsqrtLe hnpos.le
    linarith
  exact indep_cutoffSampleLocalSigma_of_indep_completion M L
    (siteRegion n S) (siteRegion n T)
    (indep_lowerShellLocalCompletion_of_cutoff_separation M L
      (measurableSet_siteRegion n S) (measurableSet_siteRegion n T) hEuclid)

/-- The chain induction behind
`iIndep_cutoffSampleLocalSigma_siteRegion_of_pairwise_latDist_sep`: the product
formula for a `Finset` of pairwise separated sites.  It is the identity form of
the same induction that `Percolation.IndepChain` runs for the site σ-fields
generated by bad events. -/
private theorem measure_biInter_eq_prod_cutoffSampleLocalSigma
    (M : ABKModel d) {L n : ℤ} (hLn : L ≤ n) {ι : Type*} {z : ι → Fin d → ℤ}
    (hsep : ∀ i j : ι, i ≠ j → 3 ^ sepShift d < latDist (z i) (z j)) :
    ∀ (s : Finset ι) (f : ι → Set (CutoffSample d)),
      (∀ i, i ∈ s → MeasurableSet[cutoffSampleLocalSigma M L
        (siteRegion n ({z i} : Set (Fin d → ℤ)))] (f i)) →
      (cutoffSampleLaw M).toMeasure (⋂ i ∈ s, f i) =
        ∏ i ∈ s, (cutoffSampleLaw M).toMeasure (f i) := by
  classical
  intro s
  induction s using Finset.induction_on with
  | empty => intro f _; simp
  | insert a s ha ih =>
      intro f hf
      have hA : MeasurableSet[cutoffSampleLocalSigma M L
          (siteRegion n ({z a} : Set (Fin d → ℤ)))] (f a) :=
        hf a (Finset.mem_insert_self a s)
      have hC : MeasurableSet[cutoffSampleLocalSigma M L
          (siteRegion n (⋃ i ∈ (s : Set ι), ({z i} : Set (Fin d → ℤ))))]
          (⋂ i ∈ s, f i) := by
        refine Finset.measurableSet_biInter s fun i hi => ?_
        refine cutoffSampleLocalSigma_mono M le_rfl
          (siteRegion_mono n fun u hu => ?_) _ (hf i (Finset.mem_insert_of_mem hi))
        exact Set.mem_biUnion (Finset.mem_coe.mpr hi) hu
      have hsep' : ∀ u ∈ ({z a} : Set (Fin d → ℤ)),
          ∀ v ∈ (⋃ i ∈ (s : Set ι), ({z i} : Set (Fin d → ℤ))),
          3 ^ sepShift d < latDist u v := by
        intro u hu v hv
        obtain ⟨i, hi, hvi⟩ := Set.mem_iUnion₂.mp hv
        rw [Set.mem_singleton_iff] at hu hvi
        subst hu
        subst hvi
        refine hsep a i ?_
        rintro rfl
        exact ha (Finset.mem_coe.mp hi)
      have hprod := (Indep_iff _ _ _).mp
        (indep_cutoffSampleLocalSigma_siteRegion_of_latDist_sep M hLn _ _ hsep')
        _ _ hA hC
      rw [Finset.set_biInter_insert, hprod, Finset.prod_insert ha,
        ih f fun i hi => hf i (Finset.mem_insert_of_mem hi)]

/-- **The `iIndepFun` form.**  Random variables on the genuine cutoff sample
space that read only the integral-local information of the cutoff `a_L` on the
cube tree of their own site are mutually independent as soon as the sites are
pairwise separated at range `3 ^ sepShift d`.  This is the hypothesis format
consumed by the ABK26 concentration inequality. -/
theorem iIndepFun_of_measurable_cutoffSampleLocalSigma_siteRegion
    (M : ABKModel d) {L n : ℤ} (hLn : L ≤ n) {ι : Type*} {z : ι → Fin d → ℤ}
    {X : ι → CutoffSample d → ℝ}
    (hsep : ∀ i j : ι, i ≠ j → 3 ^ sepShift d < latDist (z i) (z j))
    (hX : ∀ i, Measurable[cutoffSampleLocalSigma M L
      (siteRegion n ({z i} : Set (Fin d → ℤ)))] (X i)) :
    iIndepFun X (cutoffSampleLaw M).toMeasure := by
  classical
  refine (iIndepFun_iff_iIndep _ X _).mpr ?_
  rw [iIndep_iff]
  intro s f hf
  exact measure_biInter_eq_prod_cutoffSampleLocalSigma M hLn hsep s f
    fun i hi => (hX i).comap_le _ (hf i hi)

end Independence

/-! ## Concentration -/

section Concentration

/-- **Concentration on a pairwise separated family of cube sites.**

For centered random variables that read only the integral-local information of
the cutoff `a_L` on their own cube tree, and whose sites are pairwise separated
in the lattice at range `3 ^ sepShift d`, the finite-range property of the
genuine cutoff upgrades to mutual independence and ABK26's Proposition
`p.concentration` applies verbatim. -/
theorem isBigO_gammaSigma_siteSum_of_cubeLocal_centered
    (M : ABKModel d) {L n : ℤ} (hLn : L ≤ n) {S : Finset (Fin d → ℤ)} {sig K : ℝ}
    (hsep : ∀ u ∈ S, ∀ v ∈ S, u ≠ v → 3 ^ sepShift d < latDist u v)
    (hS : S.Nonempty) (hsig0 : 0 < sig) (hsig2 : sig ≤ 2) (hK : 0 < K)
    {X : (Fin d → ℤ) → CutoffSample d → ℝ}
    (hXloc : ∀ u ∈ S, Measurable[cutoffSampleLocalSigma M L
      (siteRegion n ({u} : Set (Fin d → ℤ)))] (X u))
    (hXmeas : ∀ u, Measurable (X u))
    (hXtail : ∀ u ∈ S,
      IsBigO (cutoffSampleLaw M).toMeasure (gammaSigma sig) (X u) K)
    (hXmean : ∀ u ∈ S,
      ∫ omega, X u omega ∂(cutoffSampleLaw M).toMeasure = 0) :
    IsBigO (cutoffSampleLaw M).toMeasure (gammaSigma sig)
      (fun omega => ∑ u ∈ S, X u omega)
      (Ch04.gammaSigmaIndependentSumConst sig * Real.sqrt (S.card : ℝ) * K) := by
  classical
  haveI hne : Nonempty {x : Fin d → ℤ // x ∈ S} := ⟨⟨hS.choose, hS.choose_spec⟩⟩
  have hindepFun :
      iIndepFun (fun i : {x : Fin d → ℤ // x ∈ S} => X i.val)
        (cutoffSampleLaw M).toMeasure :=
    iIndepFun_of_measurable_cutoffSampleLocalSigma_siteRegion M hLn
      (z := fun i : {x : Fin d → ℤ // x ∈ S} => i.val)
      (fun i j hij =>
        hsep i.val i.property j.val j.property fun h => hij (Subtype.ext h))
      fun i => hXloc i.val i.property
  have hcard : (Finset.univ : Finset {x : Fin d → ℤ // x ∈ S}).card = S.card := by
    rw [Finset.card_univ, Fintype.card_coe]
  have hmain :=
    Ch04.isBigO_gammaSigma_finset_sum_of_iIndepFun_of_isBigO_of_integral_eq_zero
      (μ := (cutoffSampleLaw M).toMeasure)
      (X := fun i : {x : Fin d → ℤ // x ∈ S} => X i.val)
      (s := Finset.univ) (σ := sig) (K := K) hindepFun (fun i => hXmeas i.val)
      Finset.univ_nonempty hsig0 hsig2 hK (fun i _ => hXtail i.val i.property)
      fun i _ => hXmean i.val i.property
  rw [hcard] at hmain
  have hsum : (fun omega => ∑ i : {x : Fin d → ℤ // x ∈ S}, X i.val omega) =
      fun omega => ∑ u ∈ S, X u omega := by
    funext omega
    exact Finset.sum_coe_sort S fun u => X u omega
  rwa [hsum] at hmain

/-- **The colouring corollary at the genuine cutoff law, in averaged form.**

This is ABK26's spatial corollary of Proposition `p.concentration` for the
actual cutoff coefficient field: the average over a finite family of cube
sites of centered cube-local `O_{Γ_σ}(K)` variables is `O_{Γ_σ}` at the scale
`C(σ) √(colourCount) (√(#S) / #S) K`.  The colour count is `min ((3 ^ sepShift
d + 1) ^ d) (#S)`, so the estimate degrades gracefully to the deterministic
triangle inequality on small site families. -/
theorem isBigO_gammaSigma_siteAverage_of_cubeLocal_centered
    (M : ABKModel d) {L n : ℤ} (hLn : L ≤ n) {S : Finset (Fin d → ℤ)} {sig K : ℝ}
    (hS : S.Nonempty) (hsig0 : 0 < sig) (hsig2 : sig ≤ 2) (hK : 0 < K)
    {X : (Fin d → ℤ) → CutoffSample d → ℝ}
    (hXloc : ∀ u ∈ S, Measurable[cutoffSampleLocalSigma M L
      (siteRegion n ({u} : Set (Fin d → ℤ)))] (X u))
    (hXmeas : ∀ u, Measurable (X u))
    (hXtail : ∀ u ∈ S,
      IsBigO (cutoffSampleLaw M).toMeasure (gammaSigma sig) (X u) K)
    (hXmean : ∀ u ∈ S,
      ∫ omega, X u omega ∂(cutoffSampleLaw M).toMeasure = 0) :
    IsBigO (cutoffSampleLaw M).toMeasure (gammaSigma sig)
      (fun omega => (S.card : ℝ)⁻¹ * ∑ u ∈ S, X u omega)
      (gammaTriangleConst sig * Ch04.gammaSigmaIndependentSumConst sig *
        (Real.sqrt (min (((3 ^ sepShift d + 1) ^ d : ℕ) : ℝ) ((S.card : ℝ))) *
          (Real.sqrt (S.card : ℝ) / (S.card : ℝ))) * K) := by
  classical
  have hTotal : (0 : ℝ) < (S.card : ℝ) := by exact_mod_cast hS.card_pos
  have hcolors : (S.image (siteColor (sepShift d))).Nonempty := hS.image _
  have hClassCount : ∀ c ∈ S.image (siteColor (sepShift d)),
      (0 : ℝ) < ((colorClass (sepShift d) S c).card : ℝ) := by
    intro c hc
    exact_mod_cast (colorClass_nonempty hc).card_pos
  have hY : ∀ c ∈ S.image (siteColor (sepShift d)),
      IsBigO (cutoffSampleLaw M).toMeasure (gammaSigma sig)
        (fun omega => ∑ u ∈ colorClass (sepShift d) S c, X u omega)
        (Ch04.gammaSigmaIndependentSumConst sig *
          Real.sqrt ((colorClass (sepShift d) S c).card : ℝ) * K) := by
    intro c hc
    refine isBigO_gammaSigma_siteSum_of_cubeLocal_centered M hLn
      (fun u hu v hv huv => three_pow_lt_latDist_of_mem_colorClass hu hv huv)
      (colorClass_nonempty hc) hsig0 hsig2 hK
      (fun u hu => hXloc u (colorClass_subset hu)) hXmeas
      (fun u hu => hXtail u (colorClass_subset hu))
      fun u hu => hXmean u (colorClass_subset hu)
  have hYmeas : ∀ c ∈ S.image (siteColor (sepShift d)),
      Measurable fun omega => ∑ u ∈ colorClass (sepShift d) S c, X u omega :=
    fun _ _ => Finset.measurable_sum _ fun u _ => hXmeas u
  have haverage :=
    Ch04.isBigO_finsetAverage_colorClassSums_gammaSigma
      (μ := (cutoffSampleLaw M).toMeasure)
      (colors := S.image (siteColor (sepShift d)))
      (Y := fun c omega => ∑ u ∈ colorClass (sepShift d) S c, X u omega)
      (classCount := fun c => ((colorClass (sepShift d) S c).card : ℝ))
      (colorCount := min (((3 ^ sepShift d + 1) ^ d : ℕ) : ℝ) ((S.card : ℝ)))
      (totalCount := (S.card : ℝ))
      (C := Ch04.gammaSigmaIndependentSumConst sig) (K := K) (σ := sig)
      hsig0 hcolors hClassCount hTotal
      (gammaSigmaIndependentSumConst_pos hsig0) hK hY hYmeas
      (sum_sqrt_card_colorClass_le (sepShift d) S)
  have hsum : (fun omega => (S.card : ℝ)⁻¹ *
      ∑ c ∈ S.image (siteColor (sepShift d)),
        ∑ u ∈ colorClass (sepShift d) S c, X u omega) =
      fun omega => (S.card : ℝ)⁻¹ * ∑ u ∈ S, X u omega := by
    funext omega
    congr 1
    exact Finset.sum_fiberwise_of_maps_to
      (fun x hx => Finset.mem_image_of_mem _ hx) fun u => X u omega
  rwa [hsum] at haverage

end Concentration

/-! ## Grid -/

section Grid

/-- The dimensional constant of the grid concentration estimate: the colouring cost
`√((3 ^ sepShift d + 1) ^ d)` times CoarseGraining's triangle and
independent-sum constants.

The choice `sepShift d = d` inherited from `Percolation.SiteFamilyBridge` makes
the colour count `(3 ^ d + 1) ^ d` (100 at `d = 2`, 21952 at `d = 3`).  ABK26's
corollary writes `C(σ)`; the `d`-dependence is intrinsic to any colouring
realization of that corollary. -/
def gridConcentrationConst (d : ℕ) (sig : ℝ) : ℝ :=
  gammaTriangleConst sig * Ch04.gammaSigmaIndependentSumConst sig *
    Real.sqrt ((((3 ^ sepShift d + 1) ^ d : ℕ)) : ℝ)

theorem gridConcentrationConst_pos {sig : ℝ} (hsig : 0 < sig) :
    0 < gridConcentrationConst d sig := by
  refine mul_pos (mul_pos gammaTriangleConst_pos
    (gammaSigmaIndependentSumConst_pos hsig)) (Real.sqrt_pos.2 ?_)
  have : 0 < ((3 : ℕ) ^ sepShift d + 1) ^ d := by positivity
  exact_mod_cast this

/-- The manuscript's grid gain `3 ^ (-d k / 2)` at relative depth `k`. -/
def gridDecay (d k : ℕ) : ℝ := (3 : ℝ) ^ (-((d * k : ℕ) : ℝ) / 2)

theorem gridDecay_pos (d k : ℕ) : 0 < gridDecay d k :=
  Real.rpow_pos_of_pos (by norm_num) _

/-- The lattice points of `□_m` at spacing `3 ^ n`, i.e. ABK26's index set
`3 ^ n ℤ^d ∩ □_m` written at relative depth `k = m - n`, carry the exact
grid gain `√(#S) / #S = 3 ^ (-d k / 2)`. -/
theorem sqrt_card_div_card_cubeFinset (k : ℕ) :
    Real.sqrt ((cubeFinset (d := d) k).card : ℝ) /
        ((cubeFinset (d := d) k).card : ℝ) = gridDecay d k := by
  have hcast : (((cubeFinset (d := d) k).card : ℕ) : ℝ) = (3 : ℝ) ^ ((d * k : ℕ) : ℝ) := by
    rw [card_cubeFinset]
    rw [show (((3 : ℕ) ^ (d * k) : ℕ) : ℝ) = ((3 : ℝ)) ^ (d * k) by push_cast; ring]
    exact (Real.rpow_natCast (3 : ℝ) (d * k)).symm
  rw [hcast, gridDecay, Real.sqrt_eq_rpow,
    ← Real.rpow_mul (by norm_num : (0 : ℝ) ≤ 3),
    ← Real.rpow_sub (by norm_num : (0 : ℝ) < 3)]
  congr 1
  ring

/-- **The Section 3.5 grid concentration estimate at the genuine cutoff law.**

For every unit-free family indexed by the grid `3 ^ n ℤ^d ∩ □_m` whose members
are centered, cube-local for the cutoff `a_L`, and `O_{Γ_σ}(K)`, the grid
average is `O_{Γ_σ}(C(d, σ) K 3 ^ (-d(m-n)/2))`. -/
theorem isBigO_gammaSigma_gridAverage_of_cubeLocal_centered
    (M : ABKModel d) {L n : ℤ} (hLn : L ≤ n) (k : ℕ) {sig K : ℝ}
    (hsig0 : 0 < sig) (hsig2 : sig ≤ 2) (hK : 0 < K)
    {X : (Fin d → ℤ) → CutoffSample d → ℝ}
    (hXloc : ∀ u ∈ cubeFinset (d := d) k, Measurable[cutoffSampleLocalSigma M L
      (siteRegion n ({u} : Set (Fin d → ℤ)))] (X u))
    (hXmeas : ∀ u, Measurable (X u))
    (hXtail : ∀ u ∈ cubeFinset (d := d) k,
      IsBigO (cutoffSampleLaw M).toMeasure (gammaSigma sig) (X u) K)
    (hXmean : ∀ u ∈ cubeFinset (d := d) k,
      ∫ omega, X u omega ∂(cutoffSampleLaw M).toMeasure = 0) :
    IsBigO (cutoffSampleLaw M).toMeasure (gammaSigma sig)
      (fun omega => ((cubeFinset (d := d) k).card : ℝ)⁻¹ *
        ∑ u ∈ cubeFinset (d := d) k, X u omega)
      (gridConcentrationConst d sig * K * gridDecay d k) := by
  have hbase := isBigO_gammaSigma_siteAverage_of_cubeLocal_centered M hLn
    (cubeFinset_nonempty k) hsig0 hsig2 hK hXloc hXmeas hXtail hXmean
  refine hbase.mono_scale ?_
  rw [sqrt_card_div_card_cubeFinset]
  have hmin : Real.sqrt (min (((3 ^ sepShift d + 1) ^ d : ℕ) : ℝ)
      (((cubeFinset (d := d) k).card : ℝ))) ≤
      Real.sqrt ((((3 ^ sepShift d + 1) ^ d : ℕ)) : ℝ) :=
    Real.sqrt_le_sqrt (min_le_left _ _)
  have hfactor : (0 : ℝ) ≤ gammaTriangleConst sig *
      Ch04.gammaSigmaIndependentSumConst sig * K * gridDecay d k :=
    mul_nonneg (mul_nonneg (mul_nonneg gammaTriangleConst_pos.le
      (gammaSigmaIndependentSumConst_pos hsig0).le) hK.le) (gridDecay_pos d k).le
  have hgoal := mul_le_mul_of_nonneg_left hmin hfactor
  calc gammaTriangleConst sig * Ch04.gammaSigmaIndependentSumConst sig *
        (Real.sqrt (min (((3 ^ sepShift d + 1) ^ d : ℕ) : ℝ)
          (((cubeFinset (d := d) k).card : ℝ))) * gridDecay d k) * K
      = gammaTriangleConst sig * Ch04.gammaSigmaIndependentSumConst sig * K *
          gridDecay d k *
          Real.sqrt (min (((3 ^ sepShift d + 1) ^ d : ℕ) : ℝ)
            (((cubeFinset (d := d) k).card : ℝ))) := by ring
    _ ≤ gammaTriangleConst sig * Ch04.gammaSigmaIndependentSumConst sig * K *
          gridDecay d k * Real.sqrt ((((3 ^ sepShift d + 1) ^ d : ℕ)) : ℝ) := hgoal
    _ = gridConcentrationConst d sig * K * gridDecay d k := by
        rw [gridConcentrationConst]; ring

/-- **The two-lane grid display.**

If the grid family splits pointwise into a `Γ_1` lane and a `Γ_{1/4}` lane,
each centered and cube-local for the cutoff `a_L`, then the absolute grid
average satisfies the one-sided two-term weak-Orlicz relation of the ABK26
Appendix at the two amplitudes `C(d,1) K₁ 3 ^ (-d k / 2)` and `C(d,1/4) K₄ 3 ^
(-d k / 2)`. -/
theorem isTwoTermBigOWith_gridAverage_of_twoLane
    (M : ABKModel d) {L n : ℤ} (hLn : L ≤ n) (k : ℕ) {K₁ K₄ : ℝ}
    (hK₁ : 0 < K₁) (hK₄ : 0 < K₄)
    {X Y Z : (Fin d → ℤ) → CutoffSample d → ℝ}
    (hsplit : ∀ u ∈ cubeFinset (d := d) k, ∀ omega,
      X u omega = Y u omega + Z u omega)
    (hYloc : ∀ u ∈ cubeFinset (d := d) k, Measurable[cutoffSampleLocalSigma M L
      (siteRegion n ({u} : Set (Fin d → ℤ)))] (Y u))
    (hYmeas : ∀ u, Measurable (Y u))
    (hYtail : ∀ u ∈ cubeFinset (d := d) k,
      IsBigO (cutoffSampleLaw M).toMeasure (gammaSigma 1) (Y u) K₁)
    (hYmean : ∀ u ∈ cubeFinset (d := d) k,
      ∫ omega, Y u omega ∂(cutoffSampleLaw M).toMeasure = 0)
    (hZloc : ∀ u ∈ cubeFinset (d := d) k, Measurable[cutoffSampleLocalSigma M L
      (siteRegion n ({u} : Set (Fin d → ℤ)))] (Z u))
    (hZmeas : ∀ u, Measurable (Z u))
    (hZtail : ∀ u ∈ cubeFinset (d := d) k,
      IsBigO (cutoffSampleLaw M).toMeasure (gammaSigma (1 / 4)) (Z u) K₄)
    (hZmean : ∀ u ∈ cubeFinset (d := d) k,
      ∫ omega, Z u omega ∂(cutoffSampleLaw M).toMeasure = 0) :
    Probability.IsTwoTermBigOWith (cutoffSampleLaw M).toMeasure
      (gammaSigma 1) (gammaSigma (1 / 4))
      (fun omega => |((cubeFinset (d := d) k).card : ℝ)⁻¹ *
        ∑ u ∈ cubeFinset (d := d) k, X u omega|)
      (gridConcentrationConst d 1 * K₁ * gridDecay d k)
      (gridConcentrationConst d (1 / 4) * K₄ * gridDecay d k) := by
  classical
  have hYavg := isBigO_gammaSigma_gridAverage_of_cubeLocal_centered M hLn k
    (by norm_num : (0 : ℝ) < 1) (by norm_num : (1 : ℝ) ≤ 2) hK₁
    hYloc hYmeas hYtail hYmean
  have hZavg := isBigO_gammaSigma_gridAverage_of_cubeLocal_centered M hLn k
    (by norm_num : (0 : ℝ) < 1 / 4) (by norm_num : (1 / 4 : ℝ) ≤ 2) hK₄
    hZloc hZmeas hZtail hZmean
  have hYsum : Measurable fun omega : CutoffSample d =>
      ((cubeFinset (d := d) k).card : ℝ)⁻¹ *
        ∑ u ∈ cubeFinset (d := d) k, Y u omega :=
    (Finset.measurable_sum _ fun u _ => hYmeas u).const_mul _
  have hZsum : Measurable fun omega : CutoffSample d =>
      ((cubeFinset (d := d) k).card : ℝ)⁻¹ *
        ∑ u ∈ cubeFinset (d := d) k, Z u omega :=
    (Finset.measurable_sum _ fun u _ => hZmeas u).const_mul _
  have hYmeasAvg : Measurable fun omega : CutoffSample d =>
      |((cubeFinset (d := d) k).card : ℝ)⁻¹ *
        ∑ u ∈ cubeFinset (d := d) k, Y u omega| := continuous_abs.measurable.comp hYsum
  have hZmeasAvg : Measurable fun omega : CutoffSample d =>
      |((cubeFinset (d := d) k).card : ℝ)⁻¹ *
        ∑ u ∈ cubeFinset (d := d) k, Z u omega| := continuous_abs.measurable.comp hZsum
  have hXmeasAvg : Measurable fun omega : CutoffSample d =>
      |((cubeFinset (d := d) k).card : ℝ)⁻¹ *
        ∑ u ∈ cubeFinset (d := d) k, X u omega| := by
    have hEq : (fun omega : CutoffSample d =>
        |((cubeFinset (d := d) k).card : ℝ)⁻¹ *
          ∑ u ∈ cubeFinset (d := d) k, X u omega|) =
        fun omega : CutoffSample d =>
          |((cubeFinset (d := d) k).card : ℝ)⁻¹ *
              ∑ u ∈ cubeFinset (d := d) k, Y u omega +
            ((cubeFinset (d := d) k).card : ℝ)⁻¹ *
              ∑ u ∈ cubeFinset (d := d) k, Z u omega| := by
      funext omega
      rw [← mul_add, ← Finset.sum_add_distrib]
      congr 2
      exact Finset.sum_congr rfl fun u hu => hsplit u hu omega
    rw [hEq]
    exact continuous_abs.measurable.comp (hYsum.add hZsum)
  refine ⟨_, _, Probability.isAdmissibleTail_gammaSigma (by norm_num : (0 : ℝ) < 1),
    Probability.isAdmissibleTail_gammaSigma (by norm_num : (0 : ℝ) < 1 / 4),
    mul_pos (mul_pos (gridConcentrationConst_pos (by norm_num : (0 : ℝ) < 1)) hK₁)
      (gridDecay_pos d k),
    mul_pos (mul_pos (gridConcentrationConst_pos (by norm_num : (0 : ℝ) < 1 / 4)) hK₄)
      (gridDecay_pos d k),
    hXmeasAvg, hYmeasAvg, hZmeasAvg, ?_, hYavg, hZavg⟩
  intro omega
  have hsum : ∑ u ∈ cubeFinset (d := d) k, X u omega =
      ∑ u ∈ cubeFinset (d := d) k, Y u omega +
        ∑ u ∈ cubeFinset (d := d) k, Z u omega := by
    rw [← Finset.sum_add_distrib]
    exact Finset.sum_congr rfl fun u hu => hsplit u hu omega
  show |((cubeFinset (d := d) k).card : ℝ)⁻¹ *
      ∑ u ∈ cubeFinset (d := d) k, X u omega| ≤
    |((cubeFinset (d := d) k).card : ℝ)⁻¹ *
        ∑ u ∈ cubeFinset (d := d) k, Y u omega| +
      |((cubeFinset (d := d) k).card : ℝ)⁻¹ *
        ∑ u ∈ cubeFinset (d := d) k, Z u omega|
  rw [hsum, mul_add]
  exact abs_add_le _ _

end Grid

end

end Algsuperdiff.Section3.Provider.Homogenization
