/-
Copyright (c) 2026 Scott. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Scott
-/
import Algsuperdiff.Section3.Provider.Diffusivity.ApproximateRecurrence.LocalizationFluctuationMuMeasCell
import Algsuperdiff.Section3.Provider.Diffusivity.ApproximateRecurrence.PrincipalResponseLoadMeas

/-!
# The Step-2 principal load is sample-measurable on the cutoff carrier

ABK26, `l.approximate.recurrence.formula`, Step 2, `e.Pz.def`.

## What this module supplies

`LocalizationFluctuationMuMeasCell.integrable_switchCubeEnergy_of_le` --- the
producer of the `hintPrincipal` binder of
`LocalizationFluctuationSelectEndpoint.integral_blockVecDot_recurrenceP_le_principalSwitchEnergyAverage_add`
--- carries two inputs: measurability of the load family, and an almost-sure
integrable upper bound for the switch energy.  This module supplies the **first**
one at the endpoint's own load and on the endpoint's own carrier
`Cutoff.CutoffSample d`.

`PrincipalResponseLoadMeas.measurable_shellIndexSigma_principalPz` proves the
statement on `Cutoff.ShellSeq d` for the *sub*-sigma-field generated by the fresh
shells `(n, m]`.  Two transports finish it: `Cutoff.shellIndexSigma_le_borel`
turns the fresh-block measurability into plain measurability, and
`measurable_subtype_coe` moves the carrier to the lower-tail-good subtype the
Step-2 endpoint integrates over.

The **second** input --- the almost-sure integrable upper bound --- is *not*
supplied here and is not implied by anything below.

## Binders

Beyond the typing binders: `[NeZero d]`, the geometric membership of the
localization cube in the mesh below the large cube, and the two weak-solution
properties of `e.def.w` for the corrector families.  No measurability,
continuity or selection property of the families is assumed, and no estimate,
moment or smallness occurs.

## Scope

There is no `sorry`, no `admit`, no custom axiom and no `set_option
maxHeartbeats`.

## References

* ABK26, `l.approximate.recurrence.formula`, Step 2, `e.Pz.def`, `e.def.w`.
-/

namespace Algsuperdiff.Section3.Provider.Diffusivity.ApproximateRecurrence.Closure

open Homogenization Homogenization.Book Homogenization.Book.Ch02 MeasureTheory
open Algsuperdiff.Section3 Algsuperdiff.Section3.Cutoff
open Algsuperdiff.Section3.Observable
open Algsuperdiff.Section3.Provider.Diffusivity.ApproximateRecurrence

noncomputable section

variable {d : ℕ}

/-- **`e.Pz.def`'s load is measurable in the sample, on the shell carrier.**
The fresh-block statement of `PrincipalResponseLoadMeas`, read against the full
sigma-field. -/
theorem measurable_principalPz_shellSeq [NeZero d]
    {Q R : TriadicCube d} {jd : ℕ} (hR : R ∈ descendantsAtDepth Q jd)
    (sigma : PositiveScalar) (sigmaInvD sigmaInvN : ℝ) (n m : ℤ)
    (eD eN e e' : Vec d)
    (wD : ShellSeq d → H10Function (openCubeSet Q))
    (wN : ShellSeq d → H1MeanZeroFunction (openCubeSet Q))
    (hwD : ∀ omega : ShellSeq d,
      IsZeroTraceDirichletRhsWeakSolution
        (fun _ : Vec d => (1 : Matrix (Fin d) (Fin d) ℝ))
        (openCubeSet Q) (wD omega)
        (fun x => -Corrector.streamForcing sigmaInvD omega n m eD x))
    (hwN : ∀ omega : ShellSeq d,
      IsMeanZeroNeumannRhsWeakSolution
        (fun _ : Vec d => (1 : Matrix (Fin d) (Fin d) ℝ))
        (openCubeSet Q) (wN omega)
        (fun x => -Corrector.streamForcing sigmaInvN omega n m eN x)) :
    Measurable fun omega : ShellSeq d =>
      principalPz sigma omega n m e e' R (wD omega) (wN omega) :=
  (measurable_shellIndexSigma_principalPz hR sigma sigmaInvD sigmaInvN n m eD eN e e'
    wD wN hwD hwN).mono (shellIndexSigma_le_borel _) le_rfl

/-- **The `hmeas` input of
`LocalizationFluctuationMuMeasCell.integrable_switchCubeEnergy_descendants`, at
the endpoint's own carrier.**

only on the geometric membership of the cell and the two weak-solution
properties of `e.def.w`. -/
theorem measurable_principalPz_cutoffSample [NeZero d]
    {Q R : TriadicCube d} {jd : ℕ} (hR : R ∈ descendantsAtDepth Q jd)
    (sigma : PositiveScalar) (sigmaInvD sigmaInvN : ℝ) (n m : ℤ)
    (eD eN e e' : Vec d)
    (wD : ShellSeq d → H10Function (openCubeSet Q))
    (wN : ShellSeq d → H1MeanZeroFunction (openCubeSet Q))
    (hwD : ∀ omega : ShellSeq d,
      IsZeroTraceDirichletRhsWeakSolution
        (fun _ : Vec d => (1 : Matrix (Fin d) (Fin d) ℝ))
        (openCubeSet Q) (wD omega)
        (fun x => -Corrector.streamForcing sigmaInvD omega n m eD x))
    (hwN : ∀ omega : ShellSeq d,
      IsMeanZeroNeumannRhsWeakSolution
        (fun _ : Vec d => (1 : Matrix (Fin d) (Fin d) ℝ))
        (openCubeSet Q) (wN omega)
        (fun x => -Corrector.streamForcing sigmaInvN omega n m eN x)) :
    Measurable fun omega : CutoffSample d =>
      principalPz sigma omega.val n m e e' R (wD omega.val) (wN omega.val) :=
  (measurable_principalPz_shellSeq hR sigma sigmaInvD sigmaInvN n m eD eN e e' wD wN
    hwD hwN).comp
      (measurable_subtype_coe : Measurable (Subtype.val : CutoffSample d → ShellSeq d))

/-- The same, at the name `LocalizationFluctuationMuMeasCell.meshCellLoad` gives
the load.  Definitional. -/
theorem measurable_meshCellLoad [NeZero d] (M : ABKModel d) (n : ℤ) (h : ℕ) (Kc : ℤ)
    (e e' : Vec d)
    (wD : ShellSeq d → H10Function (openCubeSet (originCube d Kc)))
    (wN : ShellSeq d → H1MeanZeroFunction (openCubeSet (originCube d Kc)))
    (hwD : ∀ omega : ShellSeq d,
      IsZeroTraceDirichletRhsWeakSolution
        (fun _ : Vec d => (1 : Matrix (Fin d) (Fin d) ℝ))
        (openCubeSet (originCube d Kc)) (wD omega)
        (fun x => -Corrector.streamForcing ((Annealed.sigmaBar M n : ℝ))⁻¹ omega n
          (n + (h : ℤ)) e x))
    (hwN : ∀ omega : ShellSeq d,
      IsMeanZeroNeumannRhsWeakSolution
        (fun _ : Vec d => (1 : Matrix (Fin d) (Fin d) ℝ))
        (openCubeSet (originCube d Kc)) (wN omega)
        (fun x => -Corrector.streamForcing ((Annealed.sigmaBar M n : ℝ))⁻¹ omega n
          (n + (h : ℤ)) e' x))
    {jd : ℕ} {R : TriadicCube d} (hR : R ∈ descendantsAtDepth (originCube d Kc) jd) :
    Measurable (meshCellLoad M n h Kc e e' wD wN R) :=
  measurable_principalPz_cutoffSample hR (Annealed.sigmaBar M n)
    ((Annealed.sigmaBar M n : ℝ))⁻¹ ((Annealed.sigmaBar M n : ℝ))⁻¹ n (n + (h : ℤ))
    e e' e e' wD wN hwD hwN

end

end Algsuperdiff.Section3.Provider.Diffusivity.ApproximateRecurrence.Closure
