import MarkovProcess.Kernel.PositiveC0Resolvent
import MarkovProcess.Semigroup.PoissonInvariant

/-!
# Measurable families generated by positive C₀ resolvents

This file propagates joint parameter/state measurability of resolvent evaluations through the
Poisson--Yosida construction of the generated semigroup.  It is deliberately independent of any
particular coefficient field.
-/

namespace SuperdiffusionAudit.Support

open Filter MeasureTheory ProbabilityTheory
open MarkovProcess MarkovProcess.Semigroup
open scoped NNReal ZeroAtInfty

noncomputable section

variable {Ω X : Type*} [MeasurableSpace Ω]
  [TopologicalSpace X] [T2Space X] [LocallyCompactSpace X]
  [SecondCountableTopology X] [MeasurableSpace X] [BorelSpace X]

variable (R : Ω → PositiveC0ContractiveResolvent X)

/-- The Riesz kernel of a normalized member of a parameterized resolvent family. -/
private noncomputable def scaledResolventKernel
    (hR : ∀ (alpha : PositiveShift) (f : C₀(X, ℝ)),
      Measurable fun p : Ω × X ↦
        (R p.1).toContractiveResolvent.operator alpha f p.2)
    (alpha : PositiveShift) : Kernel (Ω × X) X := by
  let T : Ω → C₀(X, ℝ) →L[ℝ] C₀(X, ℝ) := fun omega ↦
    (R omega).toContractiveResolvent.scaledOperator alpha
  let hT : ∀ omega, PositiveC0OperatorMeasure.IsPositive (T omega) := fun omega f hf x ↦
    mul_nonneg alpha.property.le ((R omega).isPositive alpha f hf x)
  let hnorm : ∀ omega, ‖T omega‖ ≤ 1 := fun omega ↦
    (R omega).toContractiveResolvent.opNorm_scaledOperator_le_one alpha
  let mu : Ω × X → Measure X := fun p ↦
    PositiveC0OperatorMeasure.measure (T p.1) (hT p.1) p.2
  letI : ∀ p, IsFiniteMeasure (mu p) := fun p ↦
    PositiveC0OperatorMeasure.isFiniteMeasure_measure
      (T p.1) (hT p.1) (hnorm p.1) p.2
  exact
    { toFun := mu
      measurable' := measurable_measure_of_measurable_integral_compactlySupported mu fun f ↦ by
        rw [show (fun p : Ω × X ↦ ∫ x, f x ∂mu p) =
            fun p ↦ T p.1
              (PositiveC0OperatorMeasure.compactlySupportedToC0LinearMap f) p.2 by
          funext p
          exact PositiveC0OperatorMeasure.integral_measure (T p.1) (hT p.1) p.2 f]
        exact (hR alpha
          (PositiveC0OperatorMeasure.compactlySupportedToC0LinearMap f)).const_mul alpha }

private theorem scaledResolventKernel_integral
    (hR : ∀ (alpha : PositiveShift) (f : C₀(X, ℝ)),
      Measurable fun p : Ω × X ↦
        (R p.1).toContractiveResolvent.operator alpha f p.2)
    (alpha : PositiveShift) (omega : Ω) (x : X) (f : C₀(X, ℝ)) :
    ∫ y, f y ∂scaledResolventKernel R hR alpha (omega, x) =
      (R omega).toContractiveResolvent.scaledOperator alpha f x := by
  let T := (R omega).toContractiveResolvent.scaledOperator alpha
  let hT : PositiveC0OperatorMeasure.IsPositive T := fun g hg y ↦
    mul_nonneg alpha.property.le ((R omega).isPositive alpha g hg y)
  let hnorm : ‖T‖ ≤ 1 :=
    (R omega).toContractiveResolvent.opNorm_scaledOperator_le_one alpha
  exact PositiveC0OperatorKernel.integral_kernel T hT hnorm x f

/-- Iterating a jointly measurable normalized-resolvent kernel preserves joint measurability.
The recursion carries the external parameter unchanged while integrating over the state. -/
private theorem measurable_scaledOperator_pow_apply
    (hR : ∀ (alpha : PositiveShift) (f : C₀(X, ℝ)),
      Measurable fun p : Ω × X ↦
        (R p.1).toContractiveResolvent.operator alpha f p.2)
    (alpha : PositiveShift) (f : C₀(X, ℝ)) (n : ℕ) :
    Measurable fun p : Ω × X ↦
      ((R p.1).toContractiveResolvent.scaledOperator alpha ^ n) f p.2 := by
  induction n with
  | zero =>
      change Measurable fun p : Ω × X ↦ f.toContinuousMap p.2
      exact f.continuous.measurable.comp measurable_snd
  | succ n ih =>
      let K := scaledResolventKernel R hR alpha
      have hK : IsSubMarkovKernel K := by
        intro p
        change PositiveC0OperatorMeasure.measure
            ((R p.1).toContractiveResolvent.scaledOperator alpha)
            _ p.2 Set.univ ≤ 1
        exact PositiveC0OperatorMeasure.measure_univ_le_one
          ((R p.1).toContractiveResolvent.scaledOperator alpha) _
          ((R p.1).toContractiveResolvent.opNorm_scaledOperator_le_one alpha) p.2
      let _ : IsFiniteKernel K := hK.isFiniteKernel
      have hint : StronglyMeasurable fun q : (Ω × X) × X ↦
          ((R q.1.1).toContractiveResolvent.scaledOperator alpha ^ n) f q.2 :=
        ih.stronglyMeasurable.comp_measurable
          (measurable_fst.fst.prodMk measurable_snd)
      have hmeas : Measurable fun p : Ω × X ↦
          ∫ y, ((R p.1).toContractiveResolvent.scaledOperator alpha ^ n) f y ∂K p :=
        hint.integral_kernel_prod_right'.measurable
      convert hmeas using 1
      funext p
      rw [scaledResolventKernel_integral R hR]
      simp only [pow_succ', mul_apply_eq_comp]

/-- Joint measurability of each bounded Yosida exponential evaluation. -/
private theorem measurable_yosidaOperator_apply
    (hR : ∀ (alpha : PositiveShift) (f : C₀(X, ℝ)),
      Measurable fun p : Ω × X ↦
        (R p.1).toContractiveResolvent.operator alpha f p.2)
    (alpha : PositiveShift) (t : NNReal) (f : C₀(X, ℝ)) :
    Measurable fun p : Ω × X ↦
      (R p.1).toContractiveResolvent.yosidaOperator alpha t f p.2 := by
  let c : ℝ := (t : ℝ) * (alpha : ℝ)
  have hterm : ∀ n : ℕ, Measurable fun p : Ω × X ↦
      Semigroup.poissonWeight c n *
        (((R p.1).toContractiveResolvent.scaledOperator alpha ^ n) f p.2) := fun n ↦
    (measurable_scaledOperator_pow_apply R hR alpha f n).const_mul _
  have hsum : Measurable fun p : Ω × X ↦
      ∑' n : ℕ, Semigroup.poissonWeight c n *
        (((R p.1).toContractiveResolvent.scaledOperator alpha ^ n) f p.2) :=
    Measurable.tsum hterm
  convert hsum using 1
  funext p
  rw [ContractiveResolvent.yosidaOperator, ContractiveResolvent.yosidaGenerator]
  rw [smul_smul]
  change
    NormedSpace.exp
        (c • ((R p.1).toContractiveResolvent.scaledOperator alpha -
          ContinuousLinearMap.id ℝ C₀(X, ℝ))) f p.2 = _
  rw [Semigroup.exp_smul_sub_id_apply_eq_tsum]
  let ev : C₀(X, ℝ) →L[ℝ] ℝ := LinearMap.mkContinuous
    { toFun := fun g ↦ g p.2
      map_add' := fun _ _ ↦ rfl
      map_smul' := fun _ _ ↦ rfl }
    1 fun g ↦ by
      rw [one_mul]
      calc
        ‖g p.2‖ ≤ ‖g.toBCF‖ := BoundedContinuousFunction.norm_coe_le_norm g.toBCF p.2
        _ = ‖g‖ := ZeroAtInftyContinuousMap.norm_toBCF_eq_norm
  have hseries := Semigroup.summable_poissonWeight_smul_pow_apply
    ((R p.1).toContractiveResolvent.scaledOperator alpha) c f
  change ev (∑' n : ℕ,
    Semigroup.poissonWeight c n •
      ((R p.1).toContractiveResolvent.scaledOperator alpha ^ n) f) = _
  rw [ev.map_tsum hseries]
  apply tsum_congr
  intro n
  rfl

/-- Joint parameter/state measurability of evaluations of the semigroup canonically generated by
a positive `C₀` contractive resolvent family. -/
theorem measurable_generatedSemigroup_apply
    (hR : ∀ (alpha : PositiveShift) (f : C₀(X, ℝ)),
      Measurable fun p : Ω × X ↦
        (R p.1).toContractiveResolvent.operator alpha f p.2)
    (t : NNReal) (f : C₀(X, ℝ)) :
    Measurable fun p : Ω × X ↦
      (R p.1).toContractiveResolvent.generatedSemigroup t f p.2 := by
  apply measurable_of_tendsto_metrizable
    (f := fun n p ↦
      (R p.1).toContractiveResolvent.yosidaOperator (naturalShift n) t f p.2)
  · intro n
    exact measurable_yosidaOperator_apply R hR (naturalShift n) t f
  · apply tendsto_pi_nhds.2
    intro p
    exact
      ((((ZeroAtInftyContinuousMap.isometry_toBCF (α := X) (β := ℝ)).continuous).eval
        continuous_const).continuousAt.tendsto.comp
          ((R p.1).toContractiveResolvent.tendsto_yosidaOperator_naturalShift_apply t f))

/-- At every fixed time, the transition measures represented by a jointly measurable positive
`C₀` resolvent family form a jointly measurable family in the parameter and starting state. -/
theorem measurable_kernelSemigroup_family
    (hR : ∀ (alpha : PositiveShift) (f : C₀(X, ℝ)),
      Measurable fun p : Ω × X ↦
        (R p.1).toContractiveResolvent.operator alpha f p.2)
    (t : NNReal) :
    Measurable fun p : Ω × X ↦ (R p.1).kernelSemigroup t p.2 := by
  let mu : Ω × X → Measure X := fun p ↦ (R p.1).kernelSemigroup t p.2
  let _ : ∀ p, IsFiniteMeasure (mu p) := fun p ↦
    ⟨lt_of_le_of_lt ((R p.1).kernelSemigroup.measure_univ_le_one t p.2) ENNReal.one_lt_top⟩
  let _ : ∀ p, (mu p).Regular := fun p ↦ by
    dsimp only [mu]
    rw [PositiveC0ContractiveResolvent.kernelSemigroup,
      PositiveC0SemigroupKernel.kernelSemigroup_apply,
      PositiveC0OperatorKernel.kernel_apply]
    infer_instance
  apply measurable_measure_of_measurable_integral_compactlySupported mu
  intro f
  rw [show (fun p : Ω × X ↦ ∫ x, f x ∂mu p) = fun p ↦
      (R p.1).toContractiveResolvent.generatedSemigroup t
        (PositiveC0OperatorMeasure.compactlySupportedToC0LinearMap f) p.2 by
    funext p
    exact (PositiveC0ContractiveResolvent.integral_kernelSemigroup
      (R p.1) t (PositiveC0OperatorMeasure.compactlySupportedToC0LinearMap f) p.2)]
  exact measurable_generatedSemigroup_apply R hR t
    (PositiveC0OperatorMeasure.compactlySupportedToC0LinearMap f)

end

end SuperdiffusionAudit.Support
