import MarkovProcess.Kernel.PositiveC0Resolvent
import SuperdiffusionAudit.Support.SuperdiffusivityTransition

/-!
# Feller transitions of the live stream law

The live law's transition expectations are the orbit of the strongly
continuous `C₀` semigroup generated by the stream resolvent.
-/

namespace SuperdiffusionAudit.Support.SDFeller

open Algsuperdiff.Section3 Algsuperdiff.Section5.Field
open Algsuperdiff.StatementAudit.Superdiffusivity
open MarkovProcess MarkovProcess.Semigroup
open MeasureTheory ProbabilityTheory
open SuperdiffusionAudit.Support.SDLiveLaw
open SuperdiffusionAudit.Support.SDMarginal
open SuperdiffusionAudit.Support.SDTransition
open scoped ENNReal NNReal ZeroAtInfty

noncomputable section

variable {d : ℕ} [NeZero d] (M : ABKModel d)
  (omega : Algsuperdiff.Section5.Field.FullSample d M.gamma)

theorem hasFellerTransitions_liveLaw : HasFellerTransitions (liveLaw M omega) := by
  intro f
  let R := streamWholeSpaceResolvent M omega
  let u : ℝ≥0 → C₀(Vec d, ℝ) := fun t => R.toContractiveResolvent.generatedSemigroup t f
  refine ⟨u, ?_, R.toContractiveResolvent.generatedSemigroup.continuous f⟩
  intro t x
  by_cases ht : t = 0
  · subst t
    have hstart : ∀ᵐ path ∂liveLaw M omega x, path 0 = x := by
      rw [ae_iff]
      have hmeas : MeasurableSet {path : ContinuousPath (Vec d) | path 0 = x} :=
        (ContinuousPath.measurable_coordinateProcess (alpha := Vec d) 0)
          (measurableSet_singleton x)
      rw [show {path : ContinuousPath (Vec d) | ¬path 0 = x} =
          {path : ContinuousPath (Vec d) | path 0 = x}ᶜ by ext path; simp,
        measure_compl hmeas ((measure_ne_top (liveLaw M omega x)) _),
        liveLaw_start M omega x]
      simp
    change R.toContractiveResolvent.generatedSemigroup 0 f x =
      ∫ path, f (path 0) ∂liveLaw M omega x
    rw [R.toContractiveResolvent.generatedSemigroup.zero_apply]
    symm
    calc
      (∫ path, f (path 0) ∂liveLaw M omega x) =
          ∫ _path, f x ∂liveLaw M omega x := by
        apply integral_congr_ae
        filter_upwards [hstart] with path hpath
        rw [hpath]
      _ = f x := by simp
  · have htpos : 0 < (t : ℝ) := NNReal.coe_pos.2 (pos_iff_ne_zero.2 ht)
    change R.toContractiveResolvent.generatedSemigroup t f x =
      ∫ path, f (path t) ∂liveLaw M omega x
    rw [← R.integral_kernelSemigroup]
    symm
    simpa using integral_eval_eq_transition M omega (liveLaw M omega)
      (hasDiffusionMarginals_liveLaw M omega) x htpos f.continuous

end
end SuperdiffusionAudit.Support.SDFeller
