import Algsuperdiff.Section3.Cutoff.Finite
import Algsuperdiff.Section3.Model
import Algsuperdiff.Assumptions.ShellField.LIHLocalSigma

/-!
# Integral-locality of the lower cutoff

The manuscript's local information `F(U)` is represented by CoarseGraining's
integral-generated `LocalSigmaR U`, pulled back to a shell by
`ShellField.lihLocalSigma U`.  This module makes the corresponding information
of all shells at or below `m` explicit.  It also supplies the null-set
completion needed when a limiting field is recovered only as an
almost-everywhere limit of finite local reads.

The finite lower cutoffs are proved local here.  The infinite-cutoff promotion
belongs in the next range-law module: it must use both the finite local result
and the actual lower-tail convergence theorem, rather than postulating
locality for the limiting law.
-/

namespace Algsuperdiff.Section3.Cutoff

open Filter MeasureTheory ProbabilityTheory
open Homogenization
open Algsuperdiff.Frozen.Assumptions

noncomputable section

variable {d : ℕ}

/-- The source local sigma-field generated by the restrictions to `U` of every
shell at or below `m`.  The shell index is written as `m-r` with `r : ℕ` so
that it is literally the lower-infinite stream used by the cutoff. -/
def lowerShellLocalSigma (m : ℤ) (U : Set (Vec d)) :
    MeasurableSpace (ShellSeq d) :=
  ⨆ r : ℕ, (ShellField.lihLocalSigma U).comap
    (fun omega : ShellSeq d => omega (m - (r : ℤ)))

/-- Every local lower-shell sigma-field is contained in the canonical Borel
sigma-field of the shell sequence. -/
theorem lowerShellLocalSigma_le_borel (m : ℤ) (U : Set (Vec d)) :
    lowerShellLocalSigma (d := d) m U ≤
      (inferInstance : MeasurableSpace (ShellSeq d)) := by
  refine iSup_le fun r => ?_
  exact MeasurableSpace.comap_mono (ShellField.lihLocalSigma_le_borel U) |>.trans
    ((measurable_pi_apply (m - (r : ℤ))).comap_le)

/-- The `r`th lower shell is measurable from the lower-shell local
sigma-field, with its own integral-local measurable structure. -/
theorem measurable_lowerShellLocal_coordinate (m : ℤ) (U : Set (Vec d)) (r : ℕ) :
    @Measurable (ShellSeq d) (ShellField d)
      (lowerShellLocalSigma (d := d) m U) (ShellField.lihLocalSigma U)
      (fun omega => omega (m - (r : ℤ))) := by
  apply Measurable.of_comap_le
  exact le_iSup (fun q : ℕ => (ShellField.lihLocalSigma U).comap
    (fun omega : ShellSeq d => omega (m - (q : ℤ)))) r

private theorem aeEq_iUnion {μ : Measure (ShellSeq d)}
    {s t : ℕ → Set (ShellSeq d)}
    (h : ∀ n, s n =ᵐ[μ] t n) : (⋃ n, s n) =ᵐ[μ] (⋃ n, t n) := by
  rw [ae_eq_set]
  refine ⟨measure_mono_null ?_
      (measure_iUnion_null fun n => (ae_eq_set.1 (h n)).1),
    measure_mono_null ?_ (measure_iUnion_null fun n => (ae_eq_set.1 (h n)).2)⟩
  · rintro x ⟨hxs, hxt⟩
    obtain ⟨n, hn⟩ := Set.mem_iUnion.1 hxs
    exact Set.mem_iUnion.2 ⟨n, hn, fun hcon =>
      hxt (Set.mem_iUnion.2 ⟨n, hcon⟩)⟩
  · rintro x ⟨hxt, hxs⟩
    obtain ⟨n, hn⟩ := Set.mem_iUnion.1 hxt
    exact Set.mem_iUnion.2 ⟨n, hn, fun hcon =>
      hxs (Set.mem_iUnion.2 ⟨n, hcon⟩)⟩

/-- The completion by ambient null sets of the lower-shell local sigma-field.
This is a sigma-field, not a changed cutoff definition: its only role is to
make genuine representatives of a.e. local limits measurable. -/
def lowerShellLocalCompletion (M : ABKModel d) (m : ℤ) (U : Set (Vec d)) :
    MeasurableSpace (ShellSeq d) where
  MeasurableSet' s := ∃ t,
    MeasurableSet[lowerShellLocalSigma m U] t ∧ s =ᵐ[M.P.toMeasure] t
  measurableSet_empty :=
    ⟨∅, @MeasurableSet.empty _ (lowerShellLocalSigma m U), EventuallyEq.rfl⟩
  measurableSet_compl := by
    rintro s ⟨t, ht, hst⟩
    exact ⟨tᶜ, ht.compl, hst.compl⟩
  measurableSet_iUnion := by
    intro f hf
    choose t ht hft using hf
    exact ⟨⋃ n, t n, MeasurableSet.iUnion ht, aeEq_iUnion hft⟩

/-- The completed local sigma-field contains its literal lower-shell source
sigma-field. -/
theorem lowerShellLocalSigma_le_completion (M : ABKModel d) (m : ℤ)
    (U : Set (Vec d)) :
    lowerShellLocalSigma m U ≤ lowerShellLocalCompletion M m U := by
  intro s hs
  exact ⟨s, hs, EventuallyEq.rfl⟩

/-- The completion is stable under almost-everywhere replacement. -/
theorem measurable_lowerShellLocalCompletion_of_ae_eq_completion
    {M : ABKModel d} {m : ℤ} {U : Set (Vec d)}
    {β : Type*} [MeasurableSpace β] {f g : ShellSeq d → β}
    (hg : @Measurable (ShellSeq d) β (lowerShellLocalCompletion M m U) _ g)
    (hfg : f =ᵐ[M.P.toMeasure] g) :
    @Measurable (ShellSeq d) β (lowerShellLocalCompletion M m U) _ f := by
  intro s hs
  obtain ⟨t, ht, hgt⟩ := hg hs
  exact ⟨t, ht, (hfg.preimage s).trans hgt⟩

/-- Independence is unchanged when each lower-shell local sigma-field is
completed by null sets of the ambient shell law. -/
theorem indep_lowerShellLocalCompletion_of_indep (M : ABKModel d) (m : ℤ)
    (U V : Set (Vec d))
    (h : Indep (lowerShellLocalSigma m U) (lowerShellLocalSigma m V)
      M.P.toMeasure) :
    Indep (lowerShellLocalCompletion M m U) (lowerShellLocalCompletion M m V)
      M.P.toMeasure := by
  rw [Indep_iff]
  intro s t hs ht
  obtain ⟨s', hs'meas, hss'⟩ := hs
  obtain ⟨t', ht'meas, htt'⟩ := ht
  rw [measure_congr (hss'.inter htt'), measure_congr hss', measure_congr htt']
  exact (Indep_iff _ _ M.P.toMeasure).1 h s' t' hs'meas ht'meas

private theorem measurable_entryTestR_shell_from_lowerShellLocal
    (m : ℤ) (U : Set (Vec d)) (r : ℕ) (i j : Fin d)
    {phi : Vec d → ℝ} (hphi : IsProbeR phi) (hphiSupport : Function.support phi ⊆ U) :
    @Measurable (ShellSeq d) ℝ (lowerShellLocalSigma m U) (borel ℝ)
      (fun omega => entryTestR i j phi (shellReg omega (m - (r : ℤ)))) := by
  have hlocal := ShellField.measurable_entryTestR_forgetShell_lihLocalSigma
    U i j hphi hphiSupport
  have hcoord := measurable_lowerShellLocal_coordinate (d := d) m U r
  simpa only [shellReg] using hlocal.comp hcoord

/-- Every finite lower cutoff is measurable with respect to the lower-shell
integral-local sigma-field.  This is the exact finite locality statement that
the lower-infinite limit later promotes through convergence; it uses neither a
point-value restriction sigma-field nor an added locality hypothesis. -/
theorem measurable_finiteLowerCutoff_local (m : ℤ) (q : ℕ)
    (U : Set (Vec d)) :
    @Measurable (ShellSeq d) (RegCoeffField d)
      (lowerShellLocalSigma m U) (LocalSigmaR U)
      (finiteLowerCutoff m q) := by
  change @Measurable (ShellSeq d) (RegCoeffField d)
    (lowerShellLocalSigma m U)
    (MeasurableSpace.generateFrom
      {s | ∃ (i j : Fin d) (phi : Vec d → ℝ), IsProbeR phi ∧
        Function.support phi ⊆ U ∧ ∃ t : Set ℝ, MeasurableSet t ∧
          s = entryTestR i j phi ⁻¹' t})
    (finiteLowerCutoff m q)
  refine @measurable_generateFrom (ShellSeq d) (RegCoeffField d)
    (lowerShellLocalSigma m U) _ _ ?_
  rintro s ⟨i, j, phi, hphi, hphiSupport, t, ht, rfl⟩
  have hsum : @Measurable (ShellSeq d) ℝ (lowerShellLocalSigma m U) (borel ℝ)
      (fun omega => entryTestR i j phi (finiteLowerCutoff m q omega)) := by
    have hcutoff : (fun omega : ShellSeq d =>
        entryTestR i j phi (finiteLowerCutoff m q omega)) =
        fun omega => entryTestR i j phi
          (∑ r ∈ Finset.range q, shellReg omega (m - (r : ℤ))) := by
      funext omega
      rw [finiteLowerCutoff_eq_sum_range_desc]
    rw [hcutoff]
    have hentry : (fun omega : ShellSeq d => entryTestR i j phi
        (∑ r ∈ Finset.range q, shellReg omega (m - (r : ℤ)))) =
        fun omega => ∑ r ∈ Finset.range q,
          entryTestR i j phi (shellReg omega (m - (r : ℤ))) := by
      funext omega
      rw [entryTestR_finsetSum i j hphi]
    rw [hentry]
    apply Finset.measurable_sum
    intro r hr
    exact measurable_entryTestR_shell_from_lowerShellLocal m U r i j hphi hphiSupport
  exact hsum ht

end

end Algsuperdiff.Section3.Cutoff
