/-
Copyright (c) 2026 Scott. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Scott
-/
import Algsuperdiff.Probability.IndexSigma
import Algsuperdiff.Section3.Cutoff.Locality

/-!
# Cross-shell independence in consumable sigma-field form

ABK26 fixes a sequence `{..., j_{-1}, j_0, j_1, ...}` of *independent*
antisymmetric matrix-valued random fields.  That standing assumption is already
carried verbatim by the frozen model surface, as the field
`Algsuperdiff.Frozen.Assumptions.ShellLawPrefix.independent`, namely `iIndepFun
(fun k : ℤ => fun F => F k) P.toMeasure`.

Every downstream consumer of that assumption, however, needs it in a *block*
form: the information carried by one set of shell indices is independent of the
information carried by a disjoint set of shell indices.  This file provides
exactly that translation and nothing more.  It introduces no new assumption:
each result below is a consequence of `ShellLawPrefix.independent` together
with the purely measure-theoretic engine
`Algsuperdiff.Probability.indep_indexSigma_of_disjoint`.

The distinction with the spatial range-dependence facts is deliberate.  The
declarations `Cutoff.indep_shellLocal_of_cutoff_separation` and
`Cutoff.indep_lowerShellLocalSigma_of_cutoff_separation` are consequences of the
*within-shell* finite range of dependence (J1) at a spatial separation; they are
not the cross-shell assumption of ABK26 and must never be cited for it.  The
results in this file are the converse: they never use (J1), only
`shellPrefix.independent`.

## Main definitions

* `shellIndexSigma`: the sigma-field generated by the shells indexed by `I`.

## Main results

* `indep_shellIndexSigma_of_disjoint`: shells with disjoint index sets generate
  independent sigma-fields.
* `indepFun_of_measurable_shellIndexSigma_of_disjoint`: the random-variable form.
* `lowerShellLocalSigma_le_shellIndexSigma_Iic`: the genuine lower cutoff reads
  only shells at or below its own index, so it is independent of every fresh
  block above that index.
-/

namespace Algsuperdiff.Section3.Cutoff

open Filter MeasureTheory ProbabilityTheory
open Homogenization
open Algsuperdiff.Frozen.Assumptions

noncomputable section

variable {d : ℕ}

/-! ## The sigma-field of a set of shell indices -/

/-- The sigma-field on the canonical shell-sequence carrier generated by the
shells whose index lies in `I`. -/
def shellIndexSigma (I : Set ℤ) : MeasurableSpace (ShellSeq d) :=
  Algsuperdiff.Probability.indexSigma (fun omega : ShellSeq d => omega) I

/-- One selected shell is measurable for the sigma-field of any index set
containing it. -/
theorem measurable_shellCoordinate_shellIndexSigma {I : Set ℤ} {k : ℤ}
    (hk : k ∈ I) :
    @Measurable (ShellSeq d) (ShellField d) (shellIndexSigma I) inferInstance
      (fun omega => omega k) :=
  Algsuperdiff.Probability.measurable_coordinate_of_mem
    (fun omega : ShellSeq d => omega) hk

/-- Every shell-index sigma-field is contained in the canonical Borel
sigma-field of the shell sequence. -/
theorem shellIndexSigma_le_borel (I : Set ℤ) :
    shellIndexSigma (d := d) I ≤ (inferInstance : MeasurableSpace (ShellSeq d)) := by
  refine iSup_le fun k => iSup_le fun _ => ?_
  exact (measurable_pi_apply k).comap_le

/-! ## The line-437 assumption in block form -/

/-- **Cross-shell independence, block form.**  Shells indexed by disjoint sets
generate independent sigma-fields.  This is ABK26 and nothing else: the only
input is `ShellLawPrefix.independent`. -/
theorem indep_shellIndexSigma_of_disjoint (M : ABKModel d) {I J : Set ℤ}
    (hIJ : Disjoint I J) :
    Indep (shellIndexSigma (d := d) I) (shellIndexSigma J) M.P.toMeasure :=
  Algsuperdiff.Probability.indep_indexSigma_of_disjoint
    (fun omega : ShellSeq d => omega) M.P.toMeasure
    (fun k => ShellField.measurable_shellCoordinate k)
    M.shellPrefix.independent hIJ

/-- **Random-variable form.**  Any two observables measurable for disjoint
shell blocks are independent. -/
theorem indepFun_of_measurable_shellIndexSigma_of_disjoint (M : ABKModel d)
    {I J : Set ℤ} (hIJ : Disjoint I J)
    {alpha beta : Type*} [MeasurableSpace alpha] [MeasurableSpace beta]
    {X : ShellSeq d → alpha} {Y : ShellSeq d → beta}
    (hX : @Measurable (ShellSeq d) alpha (shellIndexSigma I) inferInstance X)
    (hY : @Measurable (ShellSeq d) beta (shellIndexSigma J) inferInstance Y) :
    IndepFun X Y M.P.toMeasure :=
  (IndepFun_iff_Indep X Y M.P.toMeasure).mpr
    (ProbabilityTheory.indep_of_indep_of_le_right
      (ProbabilityTheory.indep_of_indep_of_le_left
        (indep_shellIndexSigma_of_disjoint M hIJ) hX.comap_le)
      hY.comap_le)

/-! ## Locating the cutoff and the fresh increment in the shell blocks -/

/-- The genuine lower cutoff at index `m` reads only shells at or below `m`. -/
theorem lowerShellLocalSigma_le_shellIndexSigma_Iic (m : ℤ) (U : Set (Vec d)) :
    lowerShellLocalSigma (d := d) m U ≤ shellIndexSigma (Set.Iic m) := by
  refine iSup_le fun r => ?_
  refine (MeasurableSpace.comap_mono (ShellField.lihLocalSigma_le_borel U)).trans ?_
  exact Algsuperdiff.Probability.comap_coordinate_le_indexSigma
    (fun omega : ShellSeq d => omega) (I := Set.Iic m) (by simp)

/-! ## Null-completion of one side -/

/-- **Independence against a fresh block survives null completion.**  The
genuine infinite cutoff is measurable only for the null completion of the
lower-shell local sigma-field, so this is the form in which the cutoff can be
declared independent of a disjointly indexed shell block. -/
theorem indep_lowerShellLocalCompletion_shellIndexSigma_of_disjoint
    (M : ABKModel d) {L : ℤ} {J : Set ℤ} (hJ : Disjoint (Set.Iic L) J)
    (U : Set (Vec d)) :
    Indep (lowerShellLocalCompletion M L U) (shellIndexSigma J) M.P.toMeasure := by
  have h : Indep (lowerShellLocalSigma L U) (shellIndexSigma J) M.P.toMeasure :=
    ProbabilityTheory.indep_of_indep_of_le_left
      (indep_shellIndexSigma_of_disjoint M hJ)
      (lowerShellLocalSigma_le_shellIndexSigma_Iic L U)
  rw [Indep_iff]
  intro s t hs ht
  obtain ⟨s', hs'meas, hss'⟩ := hs
  rw [measure_congr (hss'.inter EventuallyEq.rfl), measure_congr hss']
  exact (Indep_iff _ _ M.P.toMeasure).1 h s' t hs'meas ht

/-- The genuine (null-completed) lower cutoff at index `L` is independent of
every fresh block `(n, m]` lying strictly above `L`. -/
theorem indep_lowerShellLocalCompletion_shellIndexSigma_Ioc
    (M : ABKModel d) {L n m : ℤ} (hLn : L ≤ n) (U : Set (Vec d)) :
    Indep (lowerShellLocalCompletion M L U) (shellIndexSigma (Set.Ioc n m))
      M.P.toMeasure :=
  indep_lowerShellLocalCompletion_shellIndexSigma_of_disjoint M
    (Set.disjoint_left.mpr fun _ hk hk' =>
      absurd (le_trans (Set.mem_Iic.mp hk) hLn)
        (not_le.mpr (Set.mem_Ioc.mp hk').1)) U

end

end Algsuperdiff.Section3.Cutoff
