import Algsuperdiff.Assumptions.ShellField.TranslationAction
import Algsuperdiff.Section3.Provider.Corrector.FreshShellDecorrelation
import Algsuperdiff.Section3.Provider.Corrector.MollifiedDecorrelation
import Algsuperdiff.Section3.Provider.Corrector.MollifierScaling

/-!
# Transporting the fresh-shell law to the continuous-path carrier

The `Ω`-level decorrelation chain of
`Algsuperdiff.Section3.Provider.Corrector.MollifiedDecorrelation` needs three
structures on its carrier: `MeasurableConstVAdd`, `MeasurableVAdd₂` and
`VAddInvariantMeasure`.  On CoarseGraining's regular-coefficient carrier
`RegCoeffField d` the first and the third are available
(`regCoeffFieldMeasurableConstVAdd` and
`Algsuperdiff.Section3.Provider.Corrector.vaddInvariantMeasure_zeroShellRegLaw`),
but the second is not: CoarseGraining's carrier σ-algebra is generated by
pointwise evaluations and compactly supported entry tests of merely measurable,
locally integrable representatives, and joint measurability of `(z, a) ↦ z +ᵥ
a` is not available there.

The continuous-path carrier `C(Vec d, Mat d)` does carry all three, by
`Algsuperdiff.Assumptions.ShellField.TranslationAction`
(`valuePathMeasurableVAdd₂` and its parents).  This file therefore transports
the fresh-shell law along `ShellField.valuePath`, transports the origin forcing
and its covariance kill, and instantiates the decorrelation chain there.

## Main definitions

* `zeroShellValuePathLaw` — the pushforward of the zero-shell law along
  `ShellField.valuePath`, i.e. the law of the shell-zero *values* as a
  continuous matrix-valued path.
* `valuePathForcing` — the literal matrix-vector forcing at the spatial origin,
  read on `C(Vec d, Mat d)`.
* `valuePathForcingL2`, `valuePathPotentialCorrector` — the forcing as an
  element of the stationary `L²` layer, and the canonical source-sign potential
  corrector `w` of the Helmholtz splitting `𝐣 = 𝐟 + ∇w`, namely the negative of
  the orthogonal projection of the forcing onto the stationary potential
  subspace, built by the generic stationary projection of
  `Algsuperdiff.Probability.StationaryProjection` at the transported carrier.

## Main results

* `zeroShellValuePathLaw_toMeasure_eq_map_valuePath`,
  `map_vadd_zeroShellValuePathLaw` — the transported law is the `valuePath`
  pushforward of the zero-shell law, and is unchanged by a real translation of
  the path.
* `vaddInvariantMeasure_zeroShellValuePathLaw` — the transported law is
  translation invariant, from the (J1) stationarity field alone.
* `continuous_valuePathForcing`, `stronglyMeasurable_valuePathForcing`,
  `memLp_two_valuePathForcing` — the transported forcing is continuous, hence
  strongly measurable, and square integrable through the (J2) Gaussian tail,
  which is what places it in the stationary `L²` layer of the new carrier.

Nothing in the transport changes the mathematics: the transported forcing
composed with `valuePath` is *literally* (by `rfl`) the CoarseGraining origin
forcing composed with `forgetShell`, and both laws are pushforwards of one and
the same zero-shell law.

## What is *not* transported

The stationary `L²` layer of `C(Vec d, Mat d)` and the stationary `L²` layer of
`RegCoeffField d` sit over different σ-algebras, so the canonical corrector
built here is **not** identified with `ShellField.zeroShellPotentialCorrector`;
only the forcing, its covariance and its energy are shown to agree.  Any
consumer that needs the CoarseGraining-carrier corrector must supply that
identification separately.

The *energies* of the two correctors are, however, equal, and that is proved
downstream in
`Algsuperdiff/Section3/Provider/Corrector/FreshShellCorrectorEnergy.lean`
(`norm_valuePathPotentialCorrector_eq`), by transporting the stationary
potential projection along the forgetful map `regOfPath` and its Hilbert
adjoint.  A consumer that needs only the corrector *energy* — for instance to
read the frozen (J4) constant into the corrector limit — therefore needs no
further work; a consumer that needs the corrector *element* on CoarseGraining's
carrier still does.

**Disclosure.**  Nothing in this file realizes any source node.  It moves an
`Ω`-level provider chain to a carrier on which its structural hypotheses hold and
discharges its covariance hypothesis at the fresh shell; it does not prove part
(ii) of `l.approximation.stationary.by.local` and it claims no node status.  In
`integral_normSq_mollify_le_of_helmholtz_valuePath` the Helmholtz data `p`, `j`
and their subspace memberships remain genuine binders, at the subspaces of the
transported carrier; they are discharged only for the canonical splitting built
below.
-/

open MeasureTheory
open Homogenization

namespace Algsuperdiff.Section3.Provider.Corrector

open Algsuperdiff.Frozen.Assumptions
open Algsuperdiff.Probability.Stationary
open Algsuperdiff.Section3 (ABKModel)

noncomputable section

variable {d : ℕ}

/-! ### The fresh-shell law on the continuous-path carrier -/

/-- Reading the shell-zero coordinate and forgetting everything but its
continuous matrix values is measurable. -/
theorem measurable_zeroShellValuePathMap :
    Measurable (ShellField.valuePath (d := d) ∘ fun F : ℤ → ShellField d ↦ F 0) :=
  ShellField.measurable_valuePath.comp ShellField.measurable_zeroShellMap

/-- **The fresh-shell law on the continuous-path carrier.**  This is `map
(valuePath ∘ coord 0) P`, the exact analogue of `ShellField.zeroShellRegLaw`
with CoarseGraining's regular-coefficient carrier replaced by the compact-open
carrier `C(Vec d, Mat d)`. -/
def zeroShellValuePathLaw (P : ProbabilityMeasure (ℤ → ShellField d)) :
    ProbabilityMeasure C(Vec d, Mat d) :=
  P.map (measurable_zeroShellValuePathMap (d := d)).aemeasurable

/-- The transported law is the `valuePath` pushforward of the zero-shell law. -/
theorem zeroShellValuePathLaw_toMeasure_eq_map_valuePath
    (P : ProbabilityMeasure (ℤ → ShellField d)) :
    (zeroShellValuePathLaw P).toMeasure =
      Measure.map ShellField.valuePath (ShellField.zeroShellLaw P).toMeasure := by
  change
    Measure.map (ShellField.valuePath ∘ fun F : ℤ → ShellField d ↦ F 0) P.toMeasure =
      Measure.map ShellField.valuePath
        (Measure.map (fun F : ℤ → ShellField d ↦ F 0) P.toMeasure)
  exact (Measure.map_map ShellField.measurable_valuePath
    ShellField.measurable_zeroShellMap).symm

/-! ### The three structural instances at the new carrier -/

/-- Full real-translation invariance of the zero-shell law descends to the
continuous-path pushforward.  The only input is the (J1) stationarity field; no
invariance is assumed on the target law. -/
theorem map_vadd_zeroShellValuePathLaw (M : ABKModel d) (z : Vec d) :
    Measure.map (fun f : C(Vec d, Mat d) ↦ z +ᵥ f)
        (zeroShellValuePathLaw M.P).toMeasure =
      (zeroShellValuePathLaw M.P).toMeasure := by
  set mu := (ShellField.zeroShellLaw M.P).toMeasure with hmu
  calc
    Measure.map (fun f : C(Vec d, Mat d) ↦ z +ᵥ f)
          (zeroShellValuePathLaw M.P).toMeasure
        = Measure.map (fun f : C(Vec d, Mat d) ↦ z +ᵥ f)
            (Measure.map ShellField.valuePath mu) := by
          rw [zeroShellValuePathLaw_toMeasure_eq_map_valuePath, hmu]
    _ = Measure.map ((fun f : C(Vec d, Mat d) ↦ z +ᵥ f) ∘ ShellField.valuePath) mu :=
        Measure.map_map (measurable_const_vadd z) ShellField.measurable_valuePath
    _ = Measure.map (ShellField.valuePath ∘ ShellField.translate z) mu := by
        refine congrArg (fun g : ShellField d → C(Vec d, Mat d) ↦ Measure.map g mu) ?_
        funext j
        exact (ShellField.valuePath_translate z j).symm
    _ = Measure.map ShellField.valuePath (Measure.map (ShellField.translate z) mu) :=
        (Measure.map_map ShellField.measurable_valuePath
          (ShellField.measurable_translate z)).symm
    _ = Measure.map ShellField.valuePath mu := by rw [hmu, M.J1.stationary z]
    _ = (zeroShellValuePathLaw M.P).toMeasure := by
        rw [zeroShellValuePathLaw_toMeasure_eq_map_valuePath, hmu]

/-- The transported fresh-shell law is a translation-invariant measure.  This is
the analogue of `vaddInvariantMeasure_zeroShellRegLaw`, and together with the
two measurability instances above it completes the carrier data required by the
`Ω`-level decorrelation chain. -/
instance vaddInvariantMeasure_zeroShellValuePathLaw (M : ABKModel d) :
    VAddInvariantMeasure (Vec d) C(Vec d, Mat d)
      (zeroShellValuePathLaw M.P).toMeasure where
  measure_preimage_vadd := by
    intro z s hs
    rw [← Measure.map_apply (measurable_const_vadd z) hs]
    exact congrArg (fun m : Measure C(Vec d, Mat d) ↦ m s)
      (map_vadd_zeroShellValuePathLaw M z)

/-! ### The transported origin forcing -/

/-- The literal matrix-vector forcing at the spatial origin, read on the
continuous-path carrier.  This is the same formula as
`ShellField.originForcing`, with the argument a continuous path instead of an
CoarseGraining regular field. -/
def valuePathForcing (e : Vec d) (f : C(Vec d, Mat d)) : HilbertVec d :=
  HilbertVec.ofVec (matVecMul (f 0) e)

@[simp]
theorem valuePathForcing_apply (e : Vec d) (f : C(Vec d, Mat d)) :
    valuePathForcing e f = HilbertVec.ofVec (matVecMul (f 0) e) :=
  rfl

/-- Matrix-vector multiplication is continuous in the matrix. -/
theorem continuous_matVecMul_left (e : Vec d) :
    Continuous (fun A : Mat d ↦ matVecMul A e) := by
  refine continuous_pi fun i ↦ ?_
  refine continuous_finset_sum _ fun l _ ↦ ?_
  exact ((continuous_apply l).comp (continuous_apply i)).mul continuous_const

theorem continuous_valuePathForcing (e : Vec d) :
    Continuous (valuePathForcing (d := d) e) :=
  (HilbertVec.ofVecL d).continuous.comp
    ((continuous_matVecMul_left e).comp (continuous_eval_const (0 : Vec d)))

theorem stronglyMeasurable_valuePathForcing (e : Vec d) :
    StronglyMeasurable (valuePathForcing (d := d) e) :=
  (continuous_valuePathForcing e).stronglyMeasurable

/-! ### The transported `L²` layer -/

/-- The transported forcing is square integrable, from the frozen (J2) Gaussian
tail through `ShellField.memLp_originForcing_of_j2_tail`. -/
theorem memLp_two_valuePathForcing (M : ABKModel d) {e : Vec d}
    (he : Book.Ch02.vecNorm e = 1) :
    MemLp (valuePathForcing e) 2 (zeroShellValuePathLaw M.P).toMeasure := by
  have hsrc : MemLp (ShellField.originForcing e) 2
      (ShellField.zeroShellRegLaw M.P).toMeasure :=
    ShellField.memLp_originForcing_of_j2_tail M.P M.J2.gaussian_tail e he
  rw [ShellField.zeroShellRegLaw_toMeasure_eq_map_forgetShell,
    memLp_map_measure_iff (ShellField.measurable_originForcing e).aestronglyMeasurable
      ShellField.measurable_forgetShell.aemeasurable] at hsrc
  rw [zeroShellValuePathLaw_toMeasure_eq_map_valuePath,
    memLp_map_measure_iff (stronglyMeasurable_valuePathForcing e).aestronglyMeasurable
      ShellField.measurable_valuePath.aemeasurable]
  exact hsrc

/-! ### The canonical fresh-shell Helmholtz splitting at the transported carrier -/

/-- The transported origin forcing as an element of the stationary `L²` layer of
the continuous-path carrier. -/
def valuePathForcingL2 (M : ABKModel d) {e : Vec d} (he : Book.Ch02.vecNorm e = 1) :
    VectorL2 d (zeroShellValuePathLaw M.P).toMeasure :=
  (memLp_two_valuePathForcing M he).toLp (valuePathForcing e)

/-- The canonical source-sign potential corrector at the transported carrier: the
negative of the orthogonal projection of the forcing onto the stationary
potential subspace, the exact analogue of
`ShellField.zeroShellPotentialCorrector` on CoarseGraining's carrier. -/
def valuePathPotentialCorrector (M : ABKModel d) {e : Vec d}
    (he : Book.Ch02.vecNorm e = 1) :
    VectorL2 d (zeroShellValuePathLaw M.P).toMeasure :=
  -stationaryPotentialProjection (μ := (zeroShellValuePathLaw M.P).toMeasure)
    (valuePathForcingL2 M he)

/-- A strongly measurable representative of the canonical corrector. -/
def valuePathCorrectorRepr (M : ABKModel d) {e : Vec d}
    (he : Book.Ch02.vecNorm e = 1) : C(Vec d, Mat d) → HilbertVec d :=
  (Lp.aestronglyMeasurable (valuePathPotentialCorrector M he)).mk _

end

end Algsuperdiff.Section3.Provider.Corrector
