import Algsuperdiff.Section3.Provider.BadEvents.Definitions
import Algsuperdiff.Section3.Provider.BadEvents.LocalMeasurability

/-!
# The oscillation gauges of `e.BoscL.def` are integral-local

`Algsuperdiff.Section3.Provider.BadEvents.LocalMeasurability` places the
*pointwise* data of a shell field — its values and its directional first
derivatives — in the integral-generated local sigma-field
`ShellField.lihLocalSigma U`.  The gauges of `e.BoscL.def` are suprema of such
pointwise data over the open cube, so two further steps are needed.

* The stored **second** derivative is recovered from first derivatives by the
  same difference-quotient limit, and a continuous linear map out of
  `Vec d = Fin d → ℝ` is recovered from its values on the standard basis
  through `ContinuousLinearEquiv.piRing`.  This gives
  `ShellField.secondDeriv j x` as a `lihLocalSigma U`-measurable function of
  `j`.
* The supremum over the *uncountable* open cube is replaced by a supremum over
  a *countable dense* subset.  This is legitimate because the sharp
  characterizations `unitCubeDerivNorm_le_iff` and
  `unitCubeSecondDerivNorm_le_iff'` identify the unit-cube norms as the least
  nonnegative constants dominating a continuous function on the open cube.

The conclusion is that the single-shell oscillation gauge `shellOscGauge Q L`
reads the shell `j_L` only on the closed cube `z + \bar{square}_j`: it is
measurable for the sigma-field generated by the `L`-th shell coordinate with
its `lihLocalSigma`-structure on any `U` containing that closed cube.

## Main results

* `measurable_eval_deriv_lihLocalSigma`, `measurable_eval_secondDeriv_lihLocalSigma`:
  the stored derivatives at an interior point are integral-local, as operators.
* `unitCubeDerivNorm_eq_iSup`, `unitCubeSecondDerivNorm_eq_iSup`: the unit-cube
  gauges are countable suprema over a dense subset of the open cube.
* `measurable_localCubeDerivNorm_translate_lihLocalSigma`,
  `measurable_localCubeSecondDerivNorm_translate_lihLocalSigma`: the two `L^∞`
  gauges of the translated shell at scale `ell` are `lihLocalSigma U`-measurable
  whenever `U` contains the closed ball of radius `3^ell / 2` around the base
  point, i.e. the closed cube `z + \bar{square}_{ell}`.
* `measurable_shellOscGauge_shellLocal`, `measurableSet_badOscAt_shellLocal`:
  the `e.BoscL.def` gauge and event at shell index `L` are measurable for the
  `L`-th shell coordinate's integral-local sigma-field on the closed cube.

## References

* ABK26, `e.BoscL.def`.
* ABK26 (the volume-normalized Sobolev norm).
-/

namespace Algsuperdiff.Section3.Provider.BadEvents

open Filter MeasureTheory Topology
open Homogenization
open scoped Matrix.Norms.Elementwise
open Algsuperdiff.Frozen.Assumptions
open Algsuperdiff.Section3.Provider.Stream

noncomputable section

variable {d : ℕ}

/-! ## Recovering a continuous linear map from its basis values -/

/-- A family of continuous linear maps out of `Vec d = Fin d → ℝ` is measurable
as soon as all of its standard-basis values are.  The inverse of
`ContinuousLinearEquiv.piRing` is continuous, so no completeness or
finite-dimensionality of the target is used beyond the ambient normed
structure. -/
private theorem measurable_clm_of_measurable_apply_single {alpha : Type*}
    [MeasurableSpace alpha] {F : Type*} [NormedAddCommGroup F] [NormedSpace ℝ F]
    [MeasurableSpace F] [BorelSpace F] [SecondCountableTopology F]
    {f : alpha → (Vec d →L[ℝ] F)}
    (h : ∀ i : Fin d, Measurable fun a => f a (Pi.single i (1 : ℝ))) :
    Measurable f := by
  set e := ContinuousLinearEquiv.piRing (𝕜 := ℝ) (E := F) (Fin d) with he
  have hcomp : Measurable fun a => e (f a) := measurable_pi_lambda _ h
  have hsymm : Measurable (e.symm : (Fin d → F) → (Vec d →L[ℝ] F)) :=
    e.symm.continuous.measurable
  have hid : f = fun a => e.symm (e (f a)) := by
    funext a
    rw [e.symm_apply_apply]
  rw [hid]
  exact hsymm.comp hcomp

/-- Entry evaluation is `1`-Lipschitz, hence continuous, for the elementwise
matrix norm carried by the frozen shell carrier. -/
private theorem continuous_matrixEntry (i k : Fin d) :
    Continuous (fun A : Mat d => A i k) := by
  refine (LipschitzWith.of_dist_le_mul (α := Mat d) (β := ℝ) (K := 1)
    (f := fun A : Mat d => A i k) fun A B => ?_).continuous
  rw [Real.dist_eq, dist_eq_norm, NNReal.coe_one, one_mul]
  have h : ‖(A - B) i k‖ ≤ ‖A - B‖ := Matrix.norm_entry_le_entrywise_sup_norm (A - B)
  simpa only [Matrix.sub_apply, Real.norm_eq_abs] using h

private theorem continuous_matrixDerivativeEntry (v : Vec d) (i k : Fin d) :
    Continuous (fun D : ShellField.MatrixDerivative d => D v i k) :=
  (continuous_matrixEntry i k).comp (ContinuousLinearMap.apply ℝ (Mat d) v).continuous

/-! ## The stored first derivative as an operator -/

/-- **The stored first derivative is integral-local as an operator.**  If some
closed ball around `x` lies in `U`, then `j ↦ (∇j)(x)` is
`lihLocalSigma U`-measurable with values in `Vec d →L[ℝ] Mat d`. -/
theorem measurable_eval_deriv_lihLocalSigma {U : Set (Vec d)} {x : Vec d} {r : ℝ}
    (hr : 0 < r) (hrU : Metric.closedBall x r ⊆ U) :
    @Measurable (ShellField d) (ShellField.MatrixDerivative d)
      (ShellField.lihLocalSigma U) inferInstance (fun j => ShellField.deriv j x) := by
  letI : MeasurableSpace (ShellField d) := ShellField.lihLocalSigma U
  exact measurable_clm_of_measurable_apply_single fun i =>
    measurable_eval_deriv_apply_lihLocalSigma hr hrU (Pi.single i (1 : ℝ))

/-! ## The stored second derivative -/

/-- Every point of an open ball around `x` inherits the interior-point
hypothesis for the directional first derivative. -/
private theorem measurable_entry_eval_deriv_of_dist_lt {U : Set (Vec d)} {x : Vec d}
    {r : ℝ} (hrU : Metric.closedBall x r ⊆ U) {y : Vec d} (hy : dist y x < r)
    (v : Vec d) (i k : Fin d) :
    @Measurable (ShellField d) ℝ (ShellField.lihLocalSigma U) inferInstance
      (fun j => ShellField.deriv j y v i k) := by
  refine measurable_entry_eval_deriv_lihLocalSigma (r := r - dist y x) (by linarith) ?_ v i k
  refine subset_trans ?_ hrU
  intro w hw
  rw [Metric.mem_closedBall] at hw ⊢
  have htri : dist w x ≤ dist w y + dist y x := dist_triangle w y x
  linarith

/-- The difference quotients of the stored first derivative along a direction
`u` converge to the stored second derivative applied to `u`. -/
theorem tendsto_diffQuotient_secondDeriv (j : ShellField d) (x u : Vec d)
    {rho : ℕ → ℝ} (hne : ∀ n, rho n ≠ 0) (hrho : Tendsto rho atTop (𝓝 0)) :
    Tendsto (fun n => (rho n)⁻¹ •
        (ShellField.deriv j (x + rho n • u) - ShellField.deriv j x)) atTop
      (𝓝 (ShellField.secondDeriv j x u)) := by
  have hinner : HasDerivAt (fun t : ℝ => x + t • u) u 0 := by
    simpa using ((hasDerivAt_id (0 : ℝ)).smul_const u).const_add x
  have houter : HasFDerivAt
      (fun y : Vec d => (ShellField.deriv j : Vec d → ShellField.MatrixDerivative d) y)
      (ShellField.secondDeriv j x) ((fun t : ℝ => x + t • u) 0) := by
    rw [show (fun t : ℝ => x + t • u) 0 = x by simp]
    exact ShellField.deriv_hasFDerivAt j x
  have hd : HasDerivAt
      (fun t : ℝ => (ShellField.deriv j : Vec d → ShellField.MatrixDerivative d) (x + t • u))
      (ShellField.secondDeriv j x u) 0 := by
    simpa only [Function.comp_def] using houter.comp_hasDerivAt 0 hinner
  rw [hasDerivAt_iff_tendsto_slope] at hd
  have hin : Tendsto rho atTop (𝓝[≠] (0 : ℝ)) :=
    tendsto_nhdsWithin_iff.2 ⟨hrho, Eventually.of_forall fun n => hne n⟩
  have hcomp := hd.comp hin
  refine hcomp.congr fun n => ?_
  simp [slope, sub_zero]

/-- **The stored second derivative is integral-local, entrywise.**  If some
closed ball around `x` lies in `U`, then `j ↦ (∇²j)(x)uv` has
`lihLocalSigma U`-measurable entries. -/
theorem measurable_entry_eval_secondDeriv_lihLocalSigma {U : Set (Vec d)} {x : Vec d}
    {r : ℝ} (hr : 0 < r) (hrU : Metric.closedBall x r ⊆ U) (u v : Vec d)
    (i k : Fin d) :
    @Measurable (ShellField d) ℝ (ShellField.lihLocalSigma U) inferInstance
      (fun j => ShellField.secondDeriv j x u v i k) := by
  letI : MeasurableSpace (ShellField d) := ShellField.lihLocalSigma U
  set nu : ℝ := ‖u‖ with hnudef
  have hnu : 0 ≤ nu := norm_nonneg u
  set rho : ℕ → ℝ := fun n => r / (((n : ℝ) + 1) * (nu + 1)) with hrhodef
  have hden : ∀ n : ℕ, (0 : ℝ) < ((n : ℝ) + 1) * (nu + 1) := fun n => by positivity
  have hpos : ∀ n, 0 < rho n := fun n => div_pos hr (hden n)
  have hne : ∀ n, rho n ≠ 0 := fun n => (hpos n).ne'
  have hrho : Tendsto rho atTop (𝓝 0) := by
    have heq : rho = fun n : ℕ => r / (nu + 1) * (1 / ((n : ℝ) + 1)) := by
      funext n
      have h1 : ((n : ℝ) + 1) ≠ 0 := by positivity
      have h2 : nu + 1 ≠ 0 := by positivity
      rw [hrhodef]
      field_simp
    rw [heq]
    simpa using tendsto_one_div_add_atTop_nhds_zero_nat.const_mul (r / (nu + 1))
  have hdist : ∀ n, dist (x + rho n • u) x < r := by
    intro n
    have hone : (1 : ℝ) ≤ (n : ℝ) + 1 := by
      have : (0 : ℝ) ≤ (n : ℝ) := Nat.cast_nonneg n
      linarith
    have hmul : nu + 1 ≤ ((n : ℝ) + 1) * (nu + 1) :=
      le_mul_of_one_le_left (by linarith) hone
    have hlt : rho n * nu < r := by
      rw [hrhodef, div_mul_eq_mul_div, div_lt_iff₀ (hden n)]
      nlinarith [hr, hnu]
    have hnorm : dist (x + rho n • u) x = rho n * nu := by
      rw [dist_eq_norm, add_sub_cancel_left, norm_smul, Real.norm_eq_abs,
        abs_of_pos (hpos n), hnudef]
    rw [hnorm]
    exact hlt
  have hmeas : ∀ n : ℕ, Measurable
      (fun j : ShellField d => (rho n)⁻¹ *
        (ShellField.deriv j (x + rho n • u) v i k - ShellField.deriv j x v i k)) := by
    intro n
    exact ((measurable_entry_eval_deriv_of_dist_lt hrU (hdist n) v i k).sub
      (measurable_entry_eval_deriv_lihLocalSigma hr hrU v i k)).const_mul _
  refine measurable_of_tendsto_metrizable hmeas (tendsto_pi_nhds.2 fun j => ?_)
  have hD := tendsto_diffQuotient_secondDeriv j x u hne hrho
  have hentry := ((continuous_matrixDerivativeEntry v i k).tendsto
    (ShellField.secondDeriv j x u)).comp hD
  exact hentry.congr fun _ => rfl

/-- **The stored second derivative is integral-local as a matrix value.** -/
theorem measurable_eval_secondDeriv_apply_apply_lihLocalSigma {U : Set (Vec d)}
    {x : Vec d} {r : ℝ} (hr : 0 < r) (hrU : Metric.closedBall x r ⊆ U) (u v : Vec d) :
    @Measurable (ShellField d) (Mat d) (ShellField.lihLocalSigma U) inferInstance
      (fun j => ShellField.secondDeriv j x u v) := by
  letI : MeasurableSpace (ShellField d) := ShellField.lihLocalSigma U
  exact measurable_matrix_of_entries fun i k =>
    measurable_entry_eval_secondDeriv_lihLocalSigma hr hrU u v i k

/-- **The stored second derivative is integral-local in the first slot.** -/
theorem measurable_eval_secondDeriv_apply_lihLocalSigma {U : Set (Vec d)}
    {x : Vec d} {r : ℝ} (hr : 0 < r) (hrU : Metric.closedBall x r ⊆ U) (u : Vec d) :
    @Measurable (ShellField d) (ShellField.MatrixDerivative d)
      (ShellField.lihLocalSigma U) inferInstance
      (fun j => ShellField.secondDeriv j x u) := by
  letI : MeasurableSpace (ShellField d) := ShellField.lihLocalSigma U
  exact measurable_clm_of_measurable_apply_single fun i =>
    measurable_eval_secondDeriv_apply_apply_lihLocalSigma hr hrU u (Pi.single i (1 : ℝ))

/-- **The stored second derivative is integral-local as an operator.** -/
theorem measurable_eval_secondDeriv_lihLocalSigma {U : Set (Vec d)} {x : Vec d}
    {r : ℝ} (hr : 0 < r) (hrU : Metric.closedBall x r ⊆ U) :
    @Measurable (ShellField d) (ShellField.MatrixSecondDerivative d)
      (ShellField.lihLocalSigma U) inferInstance
      (fun j => ShellField.secondDeriv j x) := by
  letI : MeasurableSpace (ShellField d) := ShellField.lihLocalSigma U
  exact measurable_clm_of_measurable_apply_single fun i =>
    measurable_eval_secondDeriv_apply_lihLocalSigma hr hrU (Pi.single i (1 : ℝ))

/-! ## Countable dense subsets of the open unit cube -/

/-- The literal open unit cube of the manuscript carries a countable dense
subset, because the ambient space is second countable. -/
theorem exists_countable_dense_openCube (d : ℕ) :
    ∃ D : Set (Vec d), D.Countable ∧ D ⊆ openCubeSet (originCube d 0) ∧
      openCubeSet (originCube d 0) ⊆ closure D := by
  obtain ⟨s, hs, hsdense⟩ := TopologicalSpace.exists_countable_dense (Vec d)
  refine ⟨s ∩ openCubeSet (originCube d 0), hs.mono Set.inter_subset_left,
    Set.inter_subset_right, ?_⟩
  intro y hy
  rw [Metric.mem_closure_iff]
  intro eps heps
  have hopen : IsOpen (Metric.ball y eps ∩ openCubeSet (originCube d 0)) :=
    Metric.isOpen_ball.inter (isOpen_openCubeSet (originCube d 0))
  have hnonempty : (Metric.ball y eps ∩ openCubeSet (originCube d 0)).Nonempty :=
    ⟨y, Metric.mem_ball_self heps, hy⟩
  obtain ⟨w, hws, hw⟩ := hsdense.exists_mem_open hopen hnonempty
  exact ⟨w, ⟨hws, hw.2⟩, by rw [dist_comm]; exact hw.1⟩

/-- Replacing the open cube by a dense subset does not change the least
nonnegative constant dominating a continuous function on it. -/
private theorem eq_iSup_of_dense_openCube {D : Set (Vec d)}
    (hDsub : D ⊆ openCubeSet (originCube d 0))
    (hDdense : openCubeSet (originCube d 0) ⊆ closure D)
    {g : Vec d → ℝ} (hg : Continuous g) (hgnn : ∀ y, 0 ≤ g y) {S : ℝ}
    (hpt : ∀ y ∈ openCubeSet (originCube d 0), g y ≤ S)
    (hleast : ∀ C : ℝ, 0 ≤ C →
      (∀ y ∈ openCubeSet (originCube d 0), g y ≤ C) → S ≤ C) :
    S = ⨆ w : D, g w.1 := by
  have hzero : (0 : Vec d) ∈ openCubeSet (originCube d 0) := by
    rw [mem_openCubeSet_originCube_iff]
    intro i
    constructor <;> norm_num
  have hDne : D.Nonempty := by
    obtain ⟨w, hw, -⟩ := Metric.mem_closure_iff.1 (hDdense hzero) 1 one_pos
    exact ⟨w, hw⟩
  haveI : Nonempty D := hDne.to_subtype
  have hbdd : BddAbove (Set.range fun w : D => g w.1) := by
    refine ⟨S, ?_⟩
    rintro t ⟨w, rfl⟩
    exact hpt w.1 (hDsub w.2)
  have hupper : ⨆ w : D, g w.1 ≤ S := ciSup_le fun w => hpt w.1 (hDsub w.2)
  have hnn : 0 ≤ ⨆ w : D, g w.1 := by
    obtain ⟨w, hw⟩ := hDne
    exact le_trans (hgnn w) (le_ciSup hbdd (⟨w, hw⟩ : D))
  refine le_antisymm (hleast _ hnn fun y hy => ?_) hupper
  by_contra hcon
  push_neg at hcon
  set eps : ℝ := g y - ⨆ w : D, g w.1 with hepsdef
  have heps : 0 < eps := by rw [hepsdef]; linarith
  obtain ⟨delta, hdelta, hball⟩ := Metric.continuousAt_iff.1 hg.continuousAt eps heps
  obtain ⟨w, hwD, hwd⟩ := Metric.mem_closure_iff.1 (hDdense hy) delta hdelta
  have hgw : |g w - g y| < eps := by
    have := hball (show dist w y < delta by rw [dist_comm]; exact hwd)
    rwa [Real.dist_eq] at this
  have hlow : ⨆ v : D, g v.1 < g w := by
    have := (abs_lt.1 hgw).1
    rw [hepsdef] at this
    linarith
  exact absurd (le_ciSup hbdd (⟨w, hwD⟩ : D)) (not_le.2 hlow)

/-- The unit-cube first-derivative gauge is a countable supremum. -/
theorem unitCubeDerivNorm_eq_iSup {D : Set (Vec d)}
    (hDsub : D ⊆ openCubeSet (originCube d 0))
    (hDdense : openCubeSet (originCube d 0) ⊆ closure D) (j : ShellField d) :
    ShellField.unitCubeDerivNorm j =
      ⨆ w : D, ShellField.matrixDerivativeNorm (ShellField.deriv j w.1) :=
  eq_iSup_of_dense_openCube hDsub hDdense
    (ShellField.matrixDerivativeNorm_continuous.comp (ShellField.deriv j).continuous)
    (fun _ => ShellField.matrixDerivativeNorm_nonneg _)
    (fun _ hy => matrixDerivativeNorm_deriv_le_unitCubeDerivNorm j hy)
    (fun C hC h => (unitCubeDerivNorm_le_iff j C).2 ⟨hC, h⟩)

/-- The unit-cube second-derivative gauge is a countable supremum. -/
theorem unitCubeSecondDerivNorm_eq_iSup {D : Set (Vec d)}
    (hDsub : D ⊆ openCubeSet (originCube d 0))
    (hDdense : openCubeSet (originCube d 0) ⊆ closure D) (j : ShellField d) :
    ShellField.unitCubeSecondDerivNorm j =
      ⨆ w : D, ShellField.matrixSecondDerivativeNorm (ShellField.secondDeriv j w.1) :=
  eq_iSup_of_dense_openCube hDsub hDdense
    (ShellField.matrixSecondDerivativeNorm_continuous.comp
      (ShellField.secondDeriv j).continuous)
    (fun _ => ShellField.matrixSecondDerivativeNorm_nonneg _)
    (fun _ hy => matrixSecondDerivativeNorm_secondDeriv_le_unitCubeSecondDerivNorm j hy)
    (fun C hC h => (unitCubeSecondDerivNorm_le_iff' j C).2 ⟨hC, h⟩)

/-! ## The local cube gauges of a translated shell -/

private theorem norm_lt_half_of_mem_openCube {y : Vec d}
    (hy : y ∈ openCubeSet (originCube d 0)) : ‖y‖ < 1 / 2 := by
  have hball : y ∈ Metric.ball (cubeCenter (originCube d 0))
      (cubeRadius (originCube d 0)) := by
    rw [ball_cubeCenter_eq_openCubeSet]
    exact hy
  have hcenter : cubeCenter (originCube d 0) = (0 : Vec d) := by
    funext i
    simp [cubeCenter, originCube]
  have hradius : cubeRadius (originCube d 0) = (1 / 2 : ℝ) :=
    cubeRadius_eq_half_of_scale_eq_zero rfl
  rw [hcenter, hradius, Metric.mem_ball, dist_zero_right] at hball
  exact hball

/-- The exact base-point ball reached by the scale-`ell` cube gauge of a shell
translated by `z`: every cube point is at sup-distance below `3^ell / 2` from
`z`. -/
private theorem closedBall_subset_of_mem_openCube {z : Vec d} {ell : ℤ}
    (y : Vec d) :
    Metric.closedBall (((3 : ℝ) ^ ell) • y + z)
        ((1 / 2 : ℝ) * (3 : ℝ) ^ ell - (3 : ℝ) ^ ell * ‖y‖) ⊆
      Metric.closedBall z ((1 / 2 : ℝ) * (3 : ℝ) ^ ell) := by
  intro p hp
  rw [Metric.mem_closedBall] at hp ⊢
  have hdist : dist (((3 : ℝ) ^ ell) • y + z) z = (3 : ℝ) ^ ell * ‖y‖ := by
    rw [dist_eq_norm, add_sub_cancel_right, norm_smul, Real.norm_eq_abs,
      abs_of_pos (zpow_pos (by norm_num : (0 : ℝ) < 3) ell)]
  have htri : dist p z ≤ dist p (((3 : ℝ) ^ ell) • y + z) +
      dist (((3 : ℝ) ^ ell) • y + z) z := dist_triangle _ _ _
  rw [hdist] at htri
  linarith

private theorem radius_pos_of_mem_openCube {ell : ℤ} {y : Vec d}
    (hy : y ∈ openCubeSet (originCube d 0)) :
    0 < (1 / 2 : ℝ) * (3 : ℝ) ^ ell - (3 : ℝ) ^ ell * ‖y‖ := by
  have h3 : (0 : ℝ) < (3 : ℝ) ^ ell := zpow_pos (by norm_num) ell
  have hy2 : ‖y‖ < 1 / 2 := norm_lt_half_of_mem_openCube hy
  nlinarith [h3, hy2]

/-- **The first-derivative cube gauge of a translated shell is integral-local.**
At scale `ell` and base point `z` the gauge reads `∇j` only on the closed cube
`z + \bar{square}_{ell}` — the closed ball of radius `3^ell / 2` around `z` for
the ambient sup metric — so any `U` containing that closed ball suffices. -/
theorem measurable_localCubeDerivNorm_translate_lihLocalSigma {U : Set (Vec d)}
    (ell : ℤ) (z : Vec d)
    (hU : Metric.closedBall z ((1 / 2 : ℝ) * (3 : ℝ) ^ ell) ⊆ U) :
    @Measurable (ShellField d) ℝ (ShellField.lihLocalSigma U) inferInstance
      (fun j => localCubeDerivNorm ell (ShellField.translate z j)) := by
  letI : MeasurableSpace (ShellField d) := ShellField.lihLocalSigma U
  obtain ⟨D, hDc, hDsub, hDdense⟩ := exists_countable_dense_openCube d
  haveI : Countable D := hDc.to_subtype
  have hrw : (fun j : ShellField d => localCubeDerivNorm ell (ShellField.translate z j)) =
      fun j : ShellField d => ((3 : ℝ) ^ ell)⁻¹ *
        ⨆ w : D, ShellField.matrixDerivativeNorm
          ((3 : ℝ) ^ ell • ShellField.deriv j (((3 : ℝ) ^ ell) • w.1 + z)) := by
    funext j
    rw [localCubeDerivNorm, unitCubeDerivNorm_eq_iSup hDsub hDdense]
    rfl
  rw [hrw]
  refine measurable_const.mul (Measurable.iSup fun w => ?_)
  have hsub := (closedBall_subset_of_mem_openCube (z := z) (ell := ell) w.1).trans hU
  exact ((ShellField.matrixDerivativeNorm_continuous.comp
      (continuous_const_smul ((3 : ℝ) ^ ell))).measurable).comp
    (measurable_eval_deriv_lihLocalSigma (radius_pos_of_mem_openCube (hDsub w.2)) hsub)

/-- **The second-derivative cube gauge of a translated shell is
integral-local**, on the same closed cube. -/
theorem measurable_localCubeSecondDerivNorm_translate_lihLocalSigma {U : Set (Vec d)}
    (ell : ℤ) (z : Vec d)
    (hU : Metric.closedBall z ((1 / 2 : ℝ) * (3 : ℝ) ^ ell) ⊆ U) :
    @Measurable (ShellField d) ℝ (ShellField.lihLocalSigma U) inferInstance
      (fun j => localCubeSecondDerivNorm ell (ShellField.translate z j)) := by
  letI : MeasurableSpace (ShellField d) := ShellField.lihLocalSigma U
  obtain ⟨D, hDc, hDsub, hDdense⟩ := exists_countable_dense_openCube d
  haveI : Countable D := hDc.to_subtype
  have hrw : (fun j : ShellField d =>
        localCubeSecondDerivNorm ell (ShellField.translate z j)) =
      fun j : ShellField d => (((3 : ℝ) ^ ell)⁻¹) ^ 2 *
        ⨆ w : D, ShellField.matrixSecondDerivativeNorm
          (((3 : ℝ) ^ ell) ^ 2 • ShellField.secondDeriv j (((3 : ℝ) ^ ell) • w.1 + z)) := by
    funext j
    rw [localCubeSecondDerivNorm, unitCubeSecondDerivNorm_eq_iSup hDsub hDdense]
    refine congrArg _ (iSup_congr fun w => ?_)
    rw [ShellField.spatialScale_secondDeriv, ShellField.translate_secondDeriv]
  rw [hrw]
  refine measurable_const.mul (Measurable.iSup fun w => ?_)
  have hsub := (closedBall_subset_of_mem_openCube (z := z) (ell := ell) w.1).trans hU
  exact ((ShellField.matrixSecondDerivativeNorm_continuous.comp
      (continuous_const_smul (((3 : ℝ) ^ ell) ^ 2))).measurable).comp
    (measurable_eval_secondDeriv_lihLocalSigma
      (radius_pos_of_mem_openCube (hDsub w.2)) hsub)

/-! ## The `e.BoscL.def` gauge at a single shell -/

/-- The sigma-field on the cutoff sample space generated by the integral-local
information of the shell of index `L` in the region `U`. -/
def shellCoordinateLocalSigma (L : ℤ) (U : Set (Vec d)) :
    MeasurableSpace (Algsuperdiff.Section3.Cutoff.CutoffSample d) :=
  (ShellField.lihLocalSigma U).comap (fun omega => omega.1 L)

/-- **The single-shell oscillation gauge is local to the closed cube.**  The
gauge `3^{2j} ‖∇ j_L‖_{W^{1,∞}(z + square_j)}` of `e.BoscL.def` reads the shell
`j_L` only on the closed cube `z + \bar{square}_j`. -/
theorem measurable_shellOscGauge_shellLocal {U : Set (Vec d)} (Q : TriadicCube d)
    (L : ℤ)
    (hU : Metric.closedBall (cubeBasePoint Q) ((1 / 2 : ℝ) * (3 : ℝ) ^ Q.scale) ⊆ U) :
    @Measurable (Algsuperdiff.Section3.Cutoff.CutoffSample d) ℝ
      (shellCoordinateLocalSigma L U) inferInstance (shellOscGauge Q L) := by
  have hcoord : @Measurable (Algsuperdiff.Section3.Cutoff.CutoffSample d) (ShellField d)
      (shellCoordinateLocalSigma L U) (ShellField.lihLocalSigma U)
      (fun omega => omega.1 L) :=
    Measurable.of_comap_le le_rfl
  have hfirst := measurable_localCubeDerivNorm_translate_lihLocalSigma
    (U := U) Q.scale (cubeBasePoint Q) hU
  have hsecond := measurable_localCubeSecondDerivNorm_translate_lihLocalSigma
    (U := U) Q.scale (cubeBasePoint Q) hU
  exact (((hsecond.comp hcoord).const_mul ((3 : ℝ) ^ (2 * Q.scale))).max
    ((hfirst.comp hcoord).const_mul ((3 : ℝ) ^ Q.scale)))

/-- **The `e.BoscL.def` event is local to the closed cube at its own shell.** -/
theorem measurableSet_badOscAt_shellLocal {U : Set (Vec d)} (M : ABKModel d)
    (Q : TriadicCube d) (L : ℤ)
    (hU : Metric.closedBall (cubeBasePoint Q) ((1 / 2 : ℝ) * (3 : ℝ) ^ Q.scale) ⊆ U) :
    MeasurableSet[shellCoordinateLocalSigma L U] (badOscAt M Q L) := by
  letI : MeasurableSpace (Algsuperdiff.Section3.Cutoff.CutoffSample d) :=
    shellCoordinateLocalSigma L U
  exact measurableSet_lt measurable_const (measurable_shellOscGauge_shellLocal Q L hU)

end

end Algsuperdiff.Section3.Provider.BadEvents
