import Algsuperdiff.Section5.Field.StreamProcess
import Algsuperdiff.Section5.Support.IntrinsicScale
import Algsuperdiff.StochasticProcess.Common.DivergenceForm.WholeSpace.ParameterizedProcessSemigroup
import Algsuperdiff.Section5.Provider.SuperdiffusivityProvider

open Algsuperdiff.Section3
open Algsuperdiff.Section5.Field
open Algsuperdiff.Section5.Support
open DivergenceFormProcess.Form
open Homogenization MeasureTheory
open scoped ENNReal NNReal

/-!
# Quenched power-law superdiffusivity — [ABK] Theorem A

Source: `references/algsuperdiff.tex:145-183`.

Let `nu, gamma` and `cstar` be positive and, for a time `t > 0`, let

`R(t) = ((nu t)^{2-gamma} + cstar gamma⁻¹ t²)^{1/(2(2-gamma))}`

be the intrinsic length scale of the model at that time. For a disorder model
of strength `gamma` small enough there are constants `gamma0` and `C`,
depending only on the dimension and on the value `cstar` of the model's
nondegeneracy constant, such that for every moment
`p ∈ [1, C⁻¹ gamma⁻¹ |log gamma|⁻⁶]` the diffusion generated by
`∇·(nu I + k)∇` started at the origin satisfies two estimates: its mean square
displacement at time `t` is within
`C (p^{1/2} + |log gamma|^{1/2}) gamma^{1/2} |log gamma|⁴ R(t)²` of `2 d R(t)²`,
and its mean displacement has square at most
`C (p + |log gamma|) gamma |log gamma|⁷ R(t)²`, both as `Lᵖ`-norm bounds over
the disorder. Equivalently, the raw `p`-th moments are bounded by the
respective amplitudes raised to `p`. The first estimate is the quantitative statement that the
particle spreads like `R(t)`, which is superdiffusive above the crossover time;
the second controls its quenched mean displacement.

## The process

The realization of the environment is a sample `omega` of the model's field,
and `streamExhaustionTailInput M omega` carries the data from which the
continuous-path process of that realization is built. Its `wholeSpaceProcess`
is the unique Markov kernel on continuous paths whose finite-dimensional
distributions are those of the semigroup represented by the resolvent of
`nu I + k_omega`, so the two estimates speak about that one process and about
nothing carried by the construction data.

## The two objects the displays name

* The displacement is read through `onePointRetract (0 : Vec d)`, the
  retraction of the one-point compactification of `Vec d` onto `Vec d` that
  sends the added point to the origin. It agrees pointwise with the plain
  `fun z => Option.getD z 0`, and it is the function the measurability
  statements of the quenched expectations are proved against.
* The length scale `R(t)` is `intrinsicScale M.nu cstar M.gamma t`, the
  displayed formula above with its arguments in the order `nu cstar gamma t`.

## Reading of the statement

* **State space.** The process is built on the one-point compactification of
  `Vec d`. Two consequences are visible in the statement. The starting
  point is written as the image of `(0 : Vec d)` in the compactification, since
  the compactification carries no numeral of its own. The displacement is read
  through the retraction just described; the value it assigns at the added
  point is invisible, because a process started at a live point almost surely
  never reaches that point.
* **Path space and its metric.** The two `letI` lines supply the metric on the
  compactification in which the paths are continuous, and its completeness.
  They are the same two the process itself carries in its type, and they fix
  the Borel structure the two integrals are taken against.
* **Annealed form.** Both estimates are `L^p` norms over the disorder, so the
  environment is integrated, not quantified: there is no almost-sure clause,
  and none is printed. The outer expectation is an `ℝ≥0∞`-valued integral over
  the carrier of the field under its law, and the inner quenched expectation is
  a Bochner integral against the law of the process.
* **`p`-th-power form.** Each estimate is stated as
  `∫⁻ Z^p ≤ (ENNReal.ofReal B)^p` rather than through the `p`-th root of the
  integral. The two are equivalent for a nonnegative bound, and the power form
  is the one an `ℝ≥0∞`-valued integral states without a division; it also needs
  no integrability or measurability premise to be well-defined. The displayed
  inequalities alone do not establish integrability of the inner observables:
  a nonintegrable Bochner integrand has integral zero in Lean. The Theorem A
  comparator therefore separately proves and states almost-everywhere
  integrability of displacement and squared displacement, together with
  measurability of their quenched expectations; see
  `SuperdiffusionAudit/Superdiffusivity/Solution.lean`.
* **Time range.** The time is any positive real. The crossover time appears in
  the discussion following the printed theorem, never as a hypothesis.
* **Constants.** `gamma0` and `C` are chosen before the model and before the
  time, so they depend only on `d` and on `cstar`, which is the printed
  dependence; in particular they do not depend on `nu`. One `C` serves both
  amplitudes and the upper end of the range of `p`, as printed.
* **Carrier.** The disorder is integrated over the subtype of samples on which
  the field's two-sided scale rates and gradient bounds hold. That event has
  full measure for the unrestricted law, so the restriction loses nothing, and
  it is what makes the coefficient field, its resolvent and its process total
  functions of the sample rather than partially defined ones.
* **Non-vacuity.** The carrier is inhabited for every model, since its law is a
  probability measure. This is a conditional theorem for models satisfying
  the stated assumptions. The development does not construct a concrete
  `ABKModel d` or prove non-emptiness of that model class.

## Where the two amplitudes come from

The proof reaches each display through a product of two factors. The first is
the moment of the renormalization error of Theorem B evaluated at the random
scale `m_t` at which the particle is confined up to time `t`; the second is the
moment of `3^{2 m_t}` itself. Normalizing `m_t` by its deterministic lower
bound makes the random part of the first factor free, so it is the Theorem B
amplitude `C (p^{1/2} + |log gamma|^{1/2}) gamma^{1/2} |log gamma|³`, and the
second factor is `C |log gamma| R(t)²`. Their product is the amplitude of the
first display, `C (p^{1/2} + |log gamma|^{1/2}) gamma^{1/2} |log gamma|⁴ R(t)²`,
and squaring the `p`-dependent factor gives the second display,
`C (p + |log gamma|) gamma |log gamma|⁷ R(t)²`, both as in the paper.

The confinement scale is chosen at least of order
`|log gamma|^{1/2} R(t)`. The exit-time estimate at that scale makes the
stopping-removal error polynomially small in `gamma`.

## Conventions

* The displayed quantity is the summed `2 d R(t)²`, as in the paper. The
  proposition the proof reaches is the per-direction form with `2 R(t)²`, and
  the two are joined by summing over the standard basis: the squared
  Euclidean length is the sum of the squared coordinates.
* The two amplitudes carry the factors `p^{1/2} + |log gamma|^{1/2}` and
  `p + |log gamma|`, as in the paper. They are the factors the renormalization
  theorem supplies and this proof consumes down to `p = 1`; for `p` of order
  `|log gamma|` and above they agree with `p^{1/2}` and `p` up to a constant.

Proved; reduces to the standard axioms.
-/

-- FROZEN-STATEMENT-BEGIN
theorem Algsuperdiff.Frozen.Section5.superdiffusivity_v2
    (d : ℕ) [NeZero d] (cstar : ℝ) (hcstar : 0 < cstar) :
    ∃ gamma0 C : ℝ, 0 < gamma0 ∧ 0 < C ∧
      ∀ M : ABKModel d, Disorder.cstar M = cstar → M.gamma ≤ gamma0 →
      ∀ t : ℝ, 0 < t →
      ∀ p : ℝ, 1 ≤ p →
        p ≤ C⁻¹ * M.gamma⁻¹ * |Real.log M.gamma| ^ (-6 : ℤ) →
        (∫⁻ omega : FullSample d M.gamma,
            (letI := (streamExhaustionTailInput M omega).toOnePointRegular.metricSpace
             letI := (streamExhaustionTailInput M omega).toOnePointRegular.completeSpace
             ENNReal.ofReal
                |(∫ path, vecNormSq (onePointRetract (0 : Vec d) (path t.toNNReal))
                    ∂((streamExhaustionTailInput M omega).wholeSpaceProcess
                        ((0 : Vec d) : OnePoint (Vec d)))) -
                  2 * (d : ℝ) * intrinsicScale M.nu cstar M.gamma t ^ 2| ^ p)
            ∂(fullSampleLaw M).toMeasure) ≤
          ENNReal.ofReal (C * (Real.sqrt p + Real.sqrt |Real.log M.gamma|) *
              Real.sqrt M.gamma * |Real.log M.gamma| ^ (4 : ℕ) *
              intrinsicScale M.nu cstar M.gamma t ^ 2) ^ p ∧
        (∫⁻ omega : FullSample d M.gamma,
            (letI := (streamExhaustionTailInput M omega).toOnePointRegular.metricSpace
             letI := (streamExhaustionTailInput M omega).toOnePointRegular.completeSpace
             ENNReal.ofReal
                (vecNormSq (∫ path, onePointRetract (0 : Vec d) (path t.toNNReal)
                    ∂((streamExhaustionTailInput M omega).wholeSpaceProcess
                        ((0 : Vec d) : OnePoint (Vec d))))) ^ p)
            ∂(fullSampleLaw M).toMeasure) ≤
          ENNReal.ofReal (C * (p + |Real.log M.gamma|) * M.gamma *
              |Real.log M.gamma| ^ (7 : ℕ) *
              intrinsicScale M.nu cstar M.gamma t ^ 2) ^ p
-- FROZEN-STATEMENT-END
    := by
  exact Algsuperdiff.Section5.Provider.superdiffusivity_v2_provider d cstar hcstar
