/-
Copyright (c) 2026 Scott. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Scott
-/
import Algsuperdiff.Section3.Provider.Stream.CutoffLawTransport
import Algsuperdiff.Section4.Probability.IndicatorArray
import Algsuperdiff.Section4.Probability.LayerIndependence

/-!
# Columns that read a single shell are independent, for every dependence range

`p.concentration.for.scales` consumes the hypothesis `e.independent.columns.twosided`:
for some `r ∈ ℕ`, the columns of the Appendix-D array, taken along any residue
class modulo `r`, are mutually independent as `ℤ → ℝ`-valued random variables.

So `ColumnsIndep` holds for **every** `r ≥ 1`, with no separation geometry — in
contrast to the `𝒢₀`/`𝒢₂` lanes, whose columns read overlapping truncations and
therefore need the annulus separation.

## Carrier transfer

(J1) is stated on `Cutoff.ShellSeq d` under `M.P`; the arrays live on
`Cutoff.CutoffSample d` under `Cutoff.cutoffSampleLaw`.  Independence descends
because `Subtype.val` is a measurable embedding preserving the mass of *every*
subset (`measure_preimage_val_cutoffSampleLaw`), so no null-set bookkeeping and
no measurability side condition is needed.

## References

* ABK26, `l.ratio.of.good.scales.for.k`, (the two unverified applications), and
  `a.shell.independence` (J1).
-/

namespace Algsuperdiff.Section4.Provider.Proportion

open Algsuperdiff.Section3
open Homogenization MeasureTheory ProbabilityTheory
open Algsuperdiff.Section4.Probability
open Algsuperdiff.Section4.Probability.ScalesConcentration

noncomputable section

variable {d : ℕ}

/-! ## 1. Mutual independence of arbitrary-valued observables -/

/-- The arbitrary-codomain form of
`Algsuperdiff.Section4.Probability.iIndepFun_of_iIndep_sigma`.  The `𝒢₁`
columns are `ℤ → ℝ`-valued (a whole column at a time), so the real-valued form
proved in `LayerIndependence` does not apply directly. -/
theorem iIndepFun_of_iIndep_sigma_pi {Omega iota : Type*} [MeasurableSpace Omega]
    {mu : Measure Omega} {m : iota → MeasurableSpace Omega} (h : iIndep m mu)
    {beta : iota → Type*} [mbeta : ∀ i, MeasurableSpace (beta i)]
    {f : ∀ i, Omega → beta i} (hf : ∀ i, Measurable[m i] (f i)) :
    iIndepFun f mu :=
  (iIndepFun_iff_iIndep mbeta f mu).mpr (iIndep_of_le h fun i => (hf i).comap_le)

/-! ## 2. Independence descends to the cutoff carrier -/

/-- **Mutual independence transfers along the cutoff inclusion.**  The inclusion
`Subtype.val : CutoffSample d → ShellSeq d` preserves the mass of every subset,
so the product formula for the generated sigma-fields is preserved verbatim; no
measurability of the observables and no null-set enlargement enter. -/
theorem iIndepFun_comp_val_cutoffSampleLaw (M : ABKModel d) {iota : Type*}
    {beta : iota → Type*} [∀ i, MeasurableSpace (beta i)]
    {f : ∀ i, Cutoff.ShellSeq d → beta i} (h : iIndepFun f M.P.toMeasure) :
    iIndepFun (fun i => fun omega : Cutoff.CutoffSample d => f i omega.1)
      (Cutoff.cutoffSampleLaw M).toMeasure := by
  classical
  rw [iIndepFun_iff_iIndep] at h ⊢
  rw [iIndep_iff]
  intro s g hg
  have hchoice : ∀ i ∈ s, ∃ t : Set (beta i),
      MeasurableSet t ∧
        (Subtype.val : Cutoff.CutoffSample d → Cutoff.ShellSeq d) ⁻¹'
            (f i ⁻¹' t) = g i := by
    intro i hi
    obtain ⟨t, ht, hteq⟩ := MeasurableSpace.measurableSet_comap.1 (hg i hi)
    exact ⟨t, ht, hteq⟩
  choose! t htmeas hteq using hchoice
  have hbig : (⋂ i ∈ s, g i) =
      (Subtype.val : Cutoff.CutoffSample d → Cutoff.ShellSeq d) ⁻¹'
        (⋂ i ∈ s, f i ⁻¹' t i) := by
    rw [Set.preimage_iInter₂]
    exact Set.iInter₂_congr fun i hi => (hteq i hi).symm
  have hprod : M.P.toMeasure (⋂ i ∈ s, f i ⁻¹' t i) =
      ∏ i ∈ s, M.P.toMeasure (f i ⁻¹' t i) :=
    h.meas_biInter fun i hi => ⟨t i, htmeas i hi, rfl⟩
  rw [hbig, Provider.Stream.measure_preimage_val_cutoffSampleLaw, hprod]
  refine Finset.prod_congr rfl fun i hi => ?_
  rw [← hteq i hi, Provider.Stream.measure_preimage_val_cutoffSampleLaw]

/-! ## 3. The single-shell sigma-fields of a cutoff sample -/

/-- The sigma-field generated by reading the single shell `k` of a cutoff
sample.  Every `𝒢₁` column is measurable for exactly one of these. -/
def shellSigma (d : ℕ) (k : ℤ) : MeasurableSpace (Cutoff.CutoffSample d) :=
  MeasurableSpace.comap (fun omega : Cutoff.CutoffSample d => omega.1 k) inferInstance

theorem measurable_shellSigma_coord (k : ℤ) :
    Measurable[shellSigma d k] fun omega : Cutoff.CutoffSample d => omega.1 k :=
  Measurable.of_comap_le le_rfl

theorem shellSigma_le (k : ℤ) :
    shellSigma d k ≤ (inferInstance : MeasurableSpace (Cutoff.CutoffSample d)) :=
  ((measurable_pi_apply k).comp measurable_subtype_coe).comap_le

/-- Any measurable functional of the single shell `k` is `shellSigma d k`
measurable. -/
theorem measurable_shellSigma_comp {beta : Type*} [MeasurableSpace beta] (k : ℤ)
    {F : Algsuperdiff.Frozen.Assumptions.ShellField d → beta} (hF : Measurable F) :
    Measurable[shellSigma d k] fun omega : Cutoff.CutoffSample d => F (omega.1 k) :=
  hF.comp (measurable_shellSigma_coord k)

/-- **(J1) on the cutoff carrier.**  The single-shell sigma-fields are mutually
independent under `cutoffSampleLaw`. -/
theorem iIndep_shellSigma (M : ABKModel d) :
    iIndep (shellSigma d) (Cutoff.cutoffSampleLaw M).toMeasure := by
  have h := iIndepFun_comp_val_cutoffSampleLaw M M.shellPrefix.independent
  rw [iIndepFun_iff_iIndep] at h
  exact h

/-! ## 4. The `ColumnsIndep` producer at the two-index shape -/

private theorem injective_residue {r : ℕ} (hr : 1 ≤ r) (b : ℤ) :
    Function.Injective fun j : ℤ => j * (r : ℤ) + b := by
  intro a c hac
  have hr0 : ((r : ℤ)) ≠ 0 := by
    have : 0 < (r : ℤ) := by exact_mod_cast hr
    exact ne_of_gt this
  have hmul : a * (r : ℤ) = c * (r : ℤ) := by
    simpa only [add_left_inj] using hac
  exact mul_right_cancel₀ hr0 hmul

/-- **The `𝒢₁` independence hypothesis, discharged at every `r ≥ 1`.**  If every
entry `X m j` of a two-index array is a functional of the single shell `j`, then
the array's columns are `r`-dependent for every `r ≥ 1`. -/
theorem columnsIndep_of_shellColumn (M : ABKModel d)
    (X : ℤ → ℤ → Cutoff.CutoffSample d → ℝ) {r : ℕ} (hr : 1 ≤ r)
    (hcol : ∀ m j : ℤ, Measurable[shellSigma d j] (X m j)) :
    ColumnsIndep (Cutoff.cutoffSampleLaw M).toMeasure X r := by
  intro b
  refine iIndepFun_of_iIndep_sigma_pi
    (m := fun j : ℤ => shellSigma d (j * (r : ℤ) + b))
    ((iIndep_shellSigma M).precomp (injective_residue hr b)) ?_
  intro j
  letI : MeasurableSpace (Cutoff.CutoffSample d) := shellSigma d (j * (r : ℤ) + b)
  exact measurable_pi_lambda _ fun k => hcol k (j * (r : ℤ) + b)

end

end Algsuperdiff.Section4.Provider.Proportion
