import Algsuperdiff.Section5.Percolation.PathCount
import Mathlib.Probability.Independence.Basic

/-!
# Probabilistic hypotheses for multiscale percolation

This file records the scale-independence and spatial-separation hypotheses,
the union of bad events over scales, and the measurable crossing-path event.
-/

namespace Algsuperdiff.Section5.Percolation

open MeasureTheory ProbabilityTheory
open scoped BigOperators

/-- Mutual independence of spatial-block sigma-algebras at scales at most
`L`, for any finite family of blocks separated by more than `3^L` in the
lattice sup distance.

The source states the two-block form `SepTwoBlockIndep`, which implies this
mutual form by `sepIndep_of_twoBlock`.  Sites inside one block need not be
separated, which is essential when an inflated event is generated by every
site of a cube. -/
def SepIndep {Ω : Type*} [MeasurableSpace Ω] {d : ℕ}
    (P : Measure Ω) (B : ℕ → Site d → Set Ω) : Prop :=
  ∀ (ι : Type) [Fintype ι] (L : ℕ) (blocks : ι → Set (Site d)),
    (∀ i j, i ≠ j → ∀ z ∈ blocks i, ∀ w ∈ blocks j,
      3 ^ L < siteDist z w) →
    ProbabilityTheory.iIndep
      (fun i : ι => MeasurableSpace.generateFrom
        {S | ∃ z ∈ blocks i, ∃ L' ≤ L, S = B L' z}) P

/-- The source's two-block separation hypothesis: for any scale `L` and any two
sets of sites at lattice sup distance more than `3^L`, the sigma-algebras
generated by the events of scale at most `L` over those sites are independent
(pinned manuscript, line 14196).  Separation already forces the two sets
to be disjoint, so disjointness is not assumed separately. -/
def SepTwoBlockIndep {Ω : Type*} [MeasurableSpace Ω] {d : ℕ}
    (P : Measure Ω) (B : ℕ → Site d → Set Ω) : Prop :=
  ∀ (L : ℕ) (Z Z' : Set (Site d)),
    (∀ z ∈ Z, ∀ w ∈ Z', 3 ^ L < siteDist z w) →
    ProbabilityTheory.Indep
      (MeasurableSpace.generateFrom {A | ∃ z ∈ Z, ∃ L' ≤ L, A = B L' z})
      (MeasurableSpace.generateFrom {A | ∃ z ∈ Z', ∃ L' ≤ L, A = B L' z}) P

/-- One-versus-rest criterion for mutual independence: a family of
sigma-algebras is mutually independent as soon as every index is independent of
the sigma-algebra attached to any set of indices avoiding it, and each index
sigma-algebra is contained in the one attached to any set containing it. -/
private theorem iIndep_of_block_split {Ω ι : Type*} [MeasurableSpace Ω]
    {P : Measure Ω} [IsProbabilityMeasure P] {m : ι → MeasurableSpace Ω}
    {block : Set ι → MeasurableSpace Ω}
    (hmono : ∀ (i : ι) (T : Set ι), i ∈ T → m i ≤ block T)
    (hsplit : ∀ (i : ι) (T : Set ι), i ∉ T → ∀ u v : Set Ω,
      MeasurableSet[m i] u → MeasurableSet[block T] v →
        P (u ∩ v) = P u * P v) :
    ProbabilityTheory.iIndep m P := by
  classical
  have key : ∀ (s : Finset ι) (f : ι → Set Ω),
      (∀ i ∈ s, MeasurableSet[m i] (f i)) →
      P (⋂ i ∈ s, f i) = ∏ i ∈ s, P (f i) := by
    intro s
    induction s using Finset.induction_on with
    | empty =>
        intro f _hf
        simp
    | insert i s hi ih =>
        intro f hf
        have hrest : MeasurableSet[block (↑s : Set ι)] (⋂ j ∈ s, f j) := by
          refine Finset.measurableSet_biInter s ?_
          intro j hj
          exact hmono j (↑s : Set ι) (by exact_mod_cast hj) _
            (hf j (Finset.mem_insert_of_mem hj))
        have hiT : i ∉ (↑s : Set ι) := by exact_mod_cast hi
        rw [Finset.set_biInter_insert, Finset.prod_insert hi,
          hsplit i (↑s : Set ι) hiT _ _ (hf i (Finset.mem_insert_self i s)) hrest,
          ih f fun j hj => hf j (Finset.mem_insert_of_mem hj)]
  rw [ProbabilityTheory.iIndep_iff]
  intro s f hf
  exact key s f hf

/-- The two-block separation hypothesis of the source implies mutual
independence of the spatial blocks of a separated finite family. -/
theorem sepIndep_of_twoBlock {Ω : Type*} [MeasurableSpace Ω] {d : ℕ}
    (P : Measure Ω) [IsProbabilityMeasure P] {B : ℕ → Site d → Set Ω}
    (h : SepTwoBlockIndep P B) : SepIndep P B := by
  intro ι _ L blocks hsep
  refine iIndep_of_block_split
    (block := fun T : Set ι => MeasurableSpace.generateFrom
      {A | ∃ z ∈ ⋃ i ∈ T, blocks i, ∃ L' ≤ L, A = B L' z}) ?_ ?_
  · intro i T hiT
    apply MeasurableSpace.generateFrom_mono
    rintro A ⟨z, hz, L', hL', rfl⟩
    exact ⟨z, Set.mem_biUnion hiT hz, L', hL', rfl⟩
  · intro i T hiT u v hu hv
    have hsepBlocks : ∀ z ∈ blocks i, ∀ w ∈ ⋃ j ∈ T, blocks j,
        3 ^ L < siteDist z w := by
      intro z hz w hw
      obtain ⟨j, hj, hwj⟩ := Set.mem_iUnion₂.mp hw
      refine hsep i j ?_ z hz w hwj
      rintro rfl
      exact hiT hj
    exact (ProbabilityTheory.Indep_iff _ _ _).mp
      (h L (blocks i) _ hsepBlocks) u v hu hv

/-- The bad event at a site, obtained by taking the union over all scales. -/
def badSet {Ω : Type*} {d : ℕ} (B : ℕ → Site d → Set Ω) (z : Site d) : Set Ω :=
  ⋃ L, B L z

/-- The number of distinct good vertices of a path, represented as a real
random variable.  Passing through `toFinset` implements the vertex-set reading
when a path repeats a site. -/
noncomputable def goodVertexCount {Ω : Type*} {d : ℕ}
    (B : ℕ → Site d → Set Ω) (Γ : List (Site d)) (ω : Ω) : ℝ :=
  ∑ z ∈ Γ.toFinset, (badSet B z)ᶜ.indicator (fun _ => (1 : ℝ)) ω

/-- The event that some crossing path has fewer than the prescribed number of
good vertices. -/
noncomputable def lightPathEvent {Ω : Type*} {d : ℕ}
    (B : ℕ → Site d → Set Ω) (lam : ℝ) (k : ℕ) : Set Ω :=
  {ω | ∃ Γ : List (Site d), IsPathFrom k Γ ∧
    goodVertexCount B Γ ω < (1 - lam) * 3 ^ k}

end Algsuperdiff.Section5.Percolation
