/-
Copyright (c) 2026 Scott. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Scott
-/
import Algsuperdiff.Section4.Provider.ExcessDecay.BoundaryLaneWindows

/-!
# The partially reflected window of the §4.3 boundary lane

This module proves the **geometry** of that construction.

## The met faces are pairwise orthogonal, one per coordinate

`V` is the coordinate box `∏ᵢ (windowLo i, windowHi i)` with

```text
  windowLo x m k i = max (xᵢ - ½·3^k) (-½·3^m) ,
  windowHi x m k i = min (xᵢ + ½·3^k) ( ½·3^m) .
```

The `i`-th upper face of `∂□_m` meets `closure V` exactly when
`½·3^m ≤ xᵢ + ½·3^k` (`MeetsUpperFace`), the lower one exactly when
`xᵢ - ½·3^k ≤ -½·3^m` (`MeetsLowerFace`).  For `k < m` the two are mutually
exclusive (`not_meetsLowerFace_of_meetsUpperFace`), so **at most one face per
coordinate is met** and the met faces are pairwise orthogonal, as the draft
asserts.  Consequently the group generated by the corresponding reflections is
`(ℤ/2)^S` for the met set `S ⊆ Fin d`, of order `2^{#S} ≤ 2^d`.

## The reflected window is again a box

Because each reflection acts in a single coordinate and the reflected face is
an *endpoint* of that coordinate's interval, the union of the images of `V`
under the group, together with the interface hyperplanes, is again an open
coordinate box: `reflectedWindow`, with

```text
  reflectedLo i = if lower met then -3^m - windowHi i else windowLo i ,
  reflectedHi i = if upper met then  3^m - windowLo i else windowHi i .
```

This is the cube-adapted substitute for the draft's "open set containing
`closure W₃`", and it is *cheaper*: no interface bookkeeping is needed, because
the box already contains the relatively open faces.

## The interior distance (the draft's `c(d)·3ⁿ` ball)

The draft's key geometric claim — the reflected set "contains a ball of radius
`c(d)3^n` around every point of `W₃`" — is proved here in the sharper triadic
form

```text
  p ∈ W₃ = (x + □_{n-3}) ∩ □_m   ⟹   p + □_{n-3} ⊆ reflectedWindow x m (n-2)
```

(`image_add_openCubeSet_subset_reflectedWindow`), i.e. with `c(d) = 1/54`,
uniformly in `d`, and with the *cube* `p + □_{n-3}` rather than a ball, which
is the shape CoarseGraining's interior estimates consume.

## What is not done here

Nothing analytic.  No function is reflected, no `H¹` statement is made, and no
Hessian estimate is proved.

## References

* ABK26, `l.excess.decay.good.scales`; the odd-reflection step replaced.
* CoarseGraining
  `Homogenization.Sobolev.Foundations.CubeReflection.Reflections`
  (`coordFaceReflection`, the single-face reflection map adapted downstream).
-/

namespace Algsuperdiff.Section4.Provider.ExcessDecay

open Homogenization

noncomputable section

variable {d : ℕ}

/-! ## 1. Open coordinate boxes -/

/-- The open coordinate box `∏ i (lo i, hi i)` of `Vec d`. -/
def coordBox (lo hi : Fin d → ℝ) : Set (Vec d) :=
  Set.pi Set.univ fun i => Set.Ioo (lo i) (hi i)

theorem mem_coordBox_iff {lo hi : Fin d → ℝ} {y : Vec d} :
    y ∈ coordBox lo hi ↔ ∀ i, lo i < y i ∧ y i < hi i :=
  ⟨fun hy i => hy i (Set.mem_univ i), fun hy i _ => hy i⟩

theorem isOpen_coordBox (lo hi : Fin d → ℝ) : IsOpen (coordBox lo hi) :=
  isOpen_set_pi Set.finite_univ fun _ _ => isOpen_Ioo

theorem convex_coordBox (lo hi : Fin d → ℝ) : Convex ℝ (coordBox lo hi) :=
  convex_pi fun _ _ => convex_Ioo _ _

/-- Widening every coordinate interval enlarges the box. -/
theorem coordBox_subset_coordBox {lo hi lo' hi' : Fin d → ℝ}
    (hlo : ∀ i, lo' i ≤ lo i) (hhi : ∀ i, hi i ≤ hi' i) :
    coordBox lo hi ⊆ coordBox lo' hi' := by
  intro y hy
  rw [mem_coordBox_iff] at hy ⊢
  intro i
  exact ⟨lt_of_le_of_lt (hlo i) (hy i).1, lt_of_lt_of_le (hy i).2 (hhi i)⟩

/-! ## 2. The truncated window as a box -/

/-- The lower endpoint of the `i`-th edge of `(x + □_k) ∩ □_m`. -/
def windowLo (x : Vec d) (m k : ℤ) (i : Fin d) : ℝ :=
  max (x i - (1 / 2 : ℝ) * (3 : ℝ) ^ k) (-(1 / 2 : ℝ) * (3 : ℝ) ^ m)

/-- The upper endpoint of the `i`-th edge of `(x + □_k) ∩ □_m`. -/
def windowHi (x : Vec d) (m k : ℤ) (i : Fin d) : ℝ :=
  min (x i + (1 / 2 : ℝ) * (3 : ℝ) ^ k) ((1 / 2 : ℝ) * (3 : ℝ) ^ m)

theorem neg_half_zpow_le_windowLo (x : Vec d) (m k : ℤ) (i : Fin d) :
    -(1 / 2 : ℝ) * (3 : ℝ) ^ m ≤ windowLo x m k i :=
  le_max_right _ _

theorem windowHi_le_half_zpow (x : Vec d) (m k : ℤ) (i : Fin d) :
    windowHi x m k i ≤ (1 / 2 : ℝ) * (3 : ℝ) ^ m :=
  min_le_right _ _

/-- The truncated window `(x + □_k) ∩ □_m` is the coordinate box cut out by
`windowLo` and `windowHi`. -/
theorem truncatedWindow_eq_coordBox (x : Vec d) (m k : ℤ) :
    truncatedWindow x m k = coordBox (windowLo x m k) (windowHi x m k) := by
  ext y
  constructor
  · intro hy
    rw [mem_coordBox_iff]
    intro i
    obtain ⟨⟨z, hz, hzy⟩, hym⟩ := hy
    have hzi : z i = y i - x i := by
      rw [← hzy]
      simp
    rw [mem_openCubeSet_originCube_iff] at hz
    have hz' := hz i
    rw [hzi] at hz'
    rw [mem_openCubeSet_originCube_iff] at hym
    have hym' := hym i
    refine ⟨max_lt ?_ hym'.1, lt_min ?_ hym'.2⟩
    · linarith only [hz'.1]
    · linarith only [hz'.2]
  · intro hy
    rw [mem_coordBox_iff] at hy
    refine ⟨⟨y - x, ?_, by simp⟩, ?_⟩
    · rw [mem_openCubeSet_originCube_iff]
      intro i
      have h1 := (hy i).1
      have h2 := (hy i).2
      have h1' : x i - (1 / 2 : ℝ) * (3 : ℝ) ^ k < y i :=
        lt_of_le_of_lt (le_max_left _ _) h1
      have h2' : y i < x i + (1 / 2 : ℝ) * (3 : ℝ) ^ k :=
        lt_of_lt_of_le h2 (min_le_left _ _)
      exact ⟨by simp only [Pi.sub_apply]; linarith only [h1'],
        by simp only [Pi.sub_apply]; linarith only [h2']⟩
    · rw [mem_openCubeSet_originCube_iff]
      intro i
      exact ⟨lt_of_le_of_lt (le_max_right _ _) (hy i).1,
        lt_of_lt_of_le (hy i).2 (min_le_right _ _)⟩

/-! ## 3. The met faces -/

/-- The upper `i`-face of `∂□_m` meets the closure of `(x + □_k) ∩ □_m`. -/
def MeetsUpperFace (x : Vec d) (m k : ℤ) (i : Fin d) : Prop :=
  (1 / 2 : ℝ) * (3 : ℝ) ^ m ≤ x i + (1 / 2 : ℝ) * (3 : ℝ) ^ k

/-- The lower `i`-face of `∂□_m` meets the closure of `(x + □_k) ∩ □_m`. -/
def MeetsLowerFace (x : Vec d) (m k : ℤ) (i : Fin d) : Prop :=
  x i - (1 / 2 : ℝ) * (3 : ℝ) ^ k ≤ -(1 / 2 : ℝ) * (3 : ℝ) ^ m

/-- **At most one face per coordinate.**  A window strictly smaller than the
domain cube cannot meet both the upper and the lower `i`-face; this is what
makes the met faces pairwise orthogonal and the reflection group
`(ℤ/2)^S`. -/
theorem not_meetsLowerFace_of_meetsUpperFace {x : Vec d} {m k : ℤ} {i : Fin d}
    (hkm : k < m) (h : MeetsUpperFace x m k i) : ¬ MeetsLowerFace x m k i := by
  intro hlow
  have hlt : (3 : ℝ) ^ k < (3 : ℝ) ^ m :=
    zpow_lt_zpow_right₀ (by norm_num) hkm
  have hup : (1 / 2 : ℝ) * (3 : ℝ) ^ m ≤ x i + (1 / 2 : ℝ) * (3 : ℝ) ^ k := h
  have hlo : x i - (1 / 2 : ℝ) * (3 : ℝ) ^ k ≤ -(1 / 2 : ℝ) * (3 : ℝ) ^ m := hlow
  linarith only [hup, hlo, hlt]

theorem windowHi_of_meetsUpperFace {x : Vec d} {m k : ℤ} {i : Fin d}
    (h : MeetsUpperFace x m k i) :
    windowHi x m k i = (1 / 2 : ℝ) * (3 : ℝ) ^ m :=
  min_eq_right h

theorem windowHi_of_not_meetsUpperFace {x : Vec d} {m k : ℤ} {i : Fin d}
    (h : ¬ MeetsUpperFace x m k i) :
    windowHi x m k i = x i + (1 / 2 : ℝ) * (3 : ℝ) ^ k :=
  min_eq_left (not_le.mp h).le

theorem windowLo_of_meetsLowerFace {x : Vec d} {m k : ℤ} {i : Fin d}
    (h : MeetsLowerFace x m k i) :
    windowLo x m k i = -(1 / 2 : ℝ) * (3 : ℝ) ^ m :=
  max_eq_right h

theorem windowLo_of_not_meetsLowerFace {x : Vec d} {m k : ℤ} {i : Fin d}
    (h : ¬ MeetsLowerFace x m k i) :
    windowLo x m k i = x i - (1 / 2 : ℝ) * (3 : ℝ) ^ k :=
  max_eq_left (not_le.mp h).le

/-! ## 4. The partially reflected window -/

/-- The lower endpoint of the `i`-th edge of the partially reflected window:
unchanged unless the lower `i`-face of `∂□_m` is met, in which case the edge is
reflected through that face. -/
def reflectedLo (x : Vec d) (m k : ℤ) (i : Fin d) : ℝ :=
  if x i - (1 / 2 : ℝ) * (3 : ℝ) ^ k ≤ -(1 / 2 : ℝ) * (3 : ℝ) ^ m then
    -(3 : ℝ) ^ m - windowHi x m k i
  else windowLo x m k i

/-- The upper endpoint of the `i`-th edge of the partially reflected window. -/
def reflectedHi (x : Vec d) (m k : ℤ) (i : Fin d) : ℝ :=
  if (1 / 2 : ℝ) * (3 : ℝ) ^ m ≤ x i + (1 / 2 : ℝ) * (3 : ℝ) ^ k then
    (3 : ℝ) ^ m - windowLo x m k i
  else windowHi x m k i

/-- **The partially reflected window.**  The union of the images of
`V = (x + □_k) ∩ □_m` under the reflection group generated by the met faces of
`∂□_m`, together with the interface hyperplanes: again an open box. -/
def reflectedWindow (x : Vec d) (m k : ℤ) : Set (Vec d) :=
  coordBox (reflectedLo x m k) (reflectedHi x m k)

theorem reflectedLo_of_meetsLowerFace {x : Vec d} {m k : ℤ} {i : Fin d}
    (h : MeetsLowerFace x m k i) :
    reflectedLo x m k i = -(3 : ℝ) ^ m - windowHi x m k i :=
  if_pos h

theorem reflectedLo_of_not_meetsLowerFace {x : Vec d} {m k : ℤ} {i : Fin d}
    (h : ¬ MeetsLowerFace x m k i) :
    reflectedLo x m k i = windowLo x m k i :=
  if_neg h

theorem reflectedHi_of_meetsUpperFace {x : Vec d} {m k : ℤ} {i : Fin d}
    (h : MeetsUpperFace x m k i) :
    reflectedHi x m k i = (3 : ℝ) ^ m - windowLo x m k i :=
  if_pos h

theorem reflectedHi_of_not_meetsUpperFace {x : Vec d} {m k : ℤ} {i : Fin d}
    (h : ¬ MeetsUpperFace x m k i) :
    reflectedHi x m k i = windowHi x m k i :=
  if_neg h

theorem mem_reflectedWindow_iff {x : Vec d} {m k : ℤ} {y : Vec d} :
    y ∈ reflectedWindow x m k ↔
      ∀ i, reflectedLo x m k i < y i ∧ y i < reflectedHi x m k i :=
  mem_coordBox_iff

/-- The window sits inside its own partial reflection.

Note that the *endpoint* comparisons `reflectedLo ≤ windowLo` and
`windowHi ≤ reflectedHi` are false for degenerate (empty) windows — reflecting
an empty edge through a face moves it — so the inclusion is proved pointwise
instead, using only the two-sided bounds a genuine point of the window
carries. -/
theorem truncatedWindow_subset_reflectedWindow (x : Vec d) (m k : ℤ) :
    truncatedWindow x m k ⊆ reflectedWindow x m k := by
  rw [truncatedWindow_eq_coordBox]
  intro y hy
  rw [mem_coordBox_iff] at hy
  rw [mem_reflectedWindow_iff]
  intro i
  have hlo := (hy i).1
  have hhi := (hy i).2
  have hlo' : -(1 / 2 : ℝ) * (3 : ℝ) ^ m < y i :=
    lt_of_le_of_lt (neg_half_zpow_le_windowLo x m k i) hlo
  have hhi' : y i < (1 / 2 : ℝ) * (3 : ℝ) ^ m :=
    lt_of_lt_of_le hhi (windowHi_le_half_zpow x m k i)
  constructor
  · by_cases h : MeetsLowerFace x m k i
    · rw [reflectedLo_of_meetsLowerFace h]
      linarith only [hhi, hlo']
    · rw [reflectedLo_of_not_meetsLowerFace h]
      exact hlo
  · by_cases h : MeetsUpperFace x m k i
    · rw [reflectedHi_of_meetsUpperFace h]
      linarith only [hlo, hhi']
    · rw [reflectedHi_of_not_meetsUpperFace h]
      exact hhi

theorem isOpen_reflectedWindow (x : Vec d) (m k : ℤ) :
    IsOpen (reflectedWindow x m k) :=
  isOpen_coordBox _ _

theorem convex_reflectedWindow (x : Vec d) (m k : ℤ) :
    Convex ℝ (reflectedWindow x m k) :=
  convex_coordBox _ _

/-! ## 5. The reflected window is bounded, and stays inside `□_{m+2}` -/

theorem reflectedHi_le (x : Vec d) (m k : ℤ) (i : Fin d) :
    reflectedHi x m k i ≤ (3 / 2 : ℝ) * (3 : ℝ) ^ m := by
  by_cases h : MeetsUpperFace x m k i
  · rw [reflectedHi_of_meetsUpperFace h]
    have := neg_half_zpow_le_windowLo x m k i
    linarith only [this]
  · rw [reflectedHi_of_not_meetsUpperFace h]
    have := windowHi_le_half_zpow x m k i
    have hpos : (0 : ℝ) < (3 : ℝ) ^ m := zpow_pos (by norm_num) m
    linarith only [this, hpos]

theorem le_reflectedLo (x : Vec d) (m k : ℤ) (i : Fin d) :
    -(3 / 2 : ℝ) * (3 : ℝ) ^ m ≤ reflectedLo x m k i := by
  by_cases h : MeetsLowerFace x m k i
  · rw [reflectedLo_of_meetsLowerFace h]
    have := windowHi_le_half_zpow x m k i
    linarith only [this]
  · rw [reflectedLo_of_not_meetsLowerFace h]
    have := neg_half_zpow_le_windowLo x m k i
    have hpos : (0 : ℝ) < (3 : ℝ) ^ m := zpow_pos (by norm_num) m
    linarith only [this, hpos]

/-- The partial reflection of a window of `□_m` never leaves `□_{m+2}`. -/
theorem reflectedWindow_subset_openCubeSet (x : Vec d) (m k : ℤ) :
    reflectedWindow x m k ⊆ openCubeSet (originCube d (m + 2)) := by
  intro y hy
  rw [mem_reflectedWindow_iff] at hy
  rw [mem_openCubeSet_originCube_iff]
  intro i
  have hpos : (0 : ℝ) < (3 : ℝ) ^ m := zpow_pos (by norm_num) m
  have hexp : (3 : ℝ) ^ (m + 2) = (3 : ℝ) ^ m * 9 := by
    rw [zpow_add₀ (by norm_num : (3 : ℝ) ≠ 0)]
    norm_num
  have h1 := (hy i).1
  have h2 := (hy i).2
  have hlo := le_reflectedLo x m k i
  have hhi := reflectedHi_le x m k i
  rw [hexp]
  constructor
  · linarith only [h1, hlo, hpos]
  · linarith only [h2, hhi, hpos]

theorem isBoundedDomain_reflectedWindow (x : Vec d) (m k : ℤ) :
    IsBoundedDomain (reflectedWindow x m k) := by
  refine ⟨(3 / 2 : ℝ) * (3 : ℝ) ^ m, ?_, ?_⟩
  · have hpos : (0 : ℝ) < (3 : ℝ) ^ m := zpow_pos (by norm_num) m
    linarith only [hpos]
  · intro y hy i
    rw [mem_reflectedWindow_iff] at hy
    have h1 := (hy i).1
    have h2 := (hy i).2
    have hlo := le_reflectedLo x m k i
    have hhi := reflectedHi_le x m k i
    rw [abs_le]
    exact ⟨by linarith only [h1, hlo], by linarith only [h2, hhi]⟩

theorem isOpenBoundedConvexDomain_reflectedWindow (x : Vec d) (m k : ℤ) :
    IsOpenBoundedConvexDomain (reflectedWindow x m k) :=
  ⟨isOpen_reflectedWindow x m k, isBoundedDomain_reflectedWindow x m k,
    convex_reflectedWindow x m k⟩

/-! ## 6. Edge lengths: the reflection doubles exactly the met coordinates -/

/-- On a met coordinate the reflected edge has exactly twice the original
length; on an unmet coordinate it is unchanged.  This is the per-coordinate
form of `|reflectedWindow| = 2^{#S} · |V|`, the volume identity that makes the
odd extension's normalized `L²` norm equal to the original's. -/
theorem reflectedHi_sub_reflectedLo_of_meetsUpperFace {x : Vec d} {m k : ℤ}
    {i : Fin d} (hkm : k < m) (hup : MeetsUpperFace x m k i) :
    reflectedHi x m k i - reflectedLo x m k i =
      2 * (windowHi x m k i - windowLo x m k i) := by
  have hlow : ¬ MeetsLowerFace x m k i :=
    not_meetsLowerFace_of_meetsUpperFace hkm hup
  rw [reflectedHi_of_meetsUpperFace hup, reflectedLo_of_not_meetsLowerFace hlow,
    windowHi_of_meetsUpperFace hup]
  ring

theorem reflectedHi_sub_reflectedLo_of_meetsLowerFace {x : Vec d} {m k : ℤ}
    {i : Fin d} (hup : ¬ MeetsUpperFace x m k i) (hlow : MeetsLowerFace x m k i) :
    reflectedHi x m k i - reflectedLo x m k i =
      2 * (windowHi x m k i - windowLo x m k i) := by
  rw [reflectedHi_of_not_meetsUpperFace hup, reflectedLo_of_meetsLowerFace hlow,
    windowLo_of_meetsLowerFace hlow]
  ring

theorem reflectedHi_sub_reflectedLo_of_unmet {x : Vec d} {m k : ℤ} {i : Fin d}
    (hup : ¬ MeetsUpperFace x m k i) (hlow : ¬ MeetsLowerFace x m k i) :
    reflectedHi x m k i - reflectedLo x m k i =
      windowHi x m k i - windowLo x m k i := by
  rw [reflectedHi_of_not_meetsUpperFace hup, reflectedLo_of_not_meetsLowerFace hlow]

/-! ## 7. The interior distance: the draft's `c(d)·3ⁿ` ball at `c(d) = 1/54` -/

/-- **The draft's key geometric claim, in triadic form.**

Every point `p` of `W₃ = (x + □_{n-3}) ∩ □_m` carries a full cube
`p + □_{n-3}` inside the partially reflected window of `V = (x + □_{n-2}) ∩ □_m`.
Since `p + □_{n-3}` contains the sup-ball of radius `½·3^{n-3} = 3ⁿ/54`, this is
the draft's "ball of radius `c(d)3ⁿ` around every point of `W₃`" with the
explicit, dimension-free constant `c = 1/54`.

Only `x ∈ □_m` and `n - 2 < m` are used (the anchor's `m ≥ n + 5` is far
stronger). -/
theorem image_add_openCubeSet_subset_reflectedWindow {m n : ℤ} {x p : Vec d}
    (hmn : n - 2 < m) (hx : x ∈ openCubeSet (originCube d m))
    (hp : p ∈ truncatedWindow x m (n - 3)) :
    (fun y => p + y) '' openCubeSet (originCube d (n - 3)) ⊆
      reflectedWindow x m (n - 2) := by
  have hB : (0 : ℝ) < (3 : ℝ) ^ (n - 3) := zpow_pos (by norm_num) _
  have hA : (3 : ℝ) ^ (n - 2) = 3 * (3 : ℝ) ^ (n - 3) := by
    rw [show n - 2 = n - 3 + 1 by ring, zpow_add_one₀ (by norm_num : (3 : ℝ) ≠ 0)]
    ring
  rw [truncatedWindow_eq_coordBox, mem_coordBox_iff] at hp
  rw [mem_openCubeSet_originCube_iff] at hx
  rintro q ⟨z, hz, rfl⟩
  rw [mem_openCubeSet_originCube_iff] at hz
  show p + z ∈ reflectedWindow x m (n - 2)
  rw [mem_reflectedWindow_iff]
  intro i
  have hzi := hz i
  have hpi := hp i
  have hxi := hx i
  -- the two window bounds on `p i`
  have hpl : x i - (1 / 2 : ℝ) * (3 : ℝ) ^ (n - 3) < p i :=
    lt_of_le_of_lt (le_max_left _ _) hpi.1
  have hpu : p i < x i + (1 / 2 : ℝ) * (3 : ℝ) ^ (n - 3) :=
    lt_of_lt_of_le hpi.2 (min_le_left _ _)
  have hpm : p i < (1 / 2 : ℝ) * (3 : ℝ) ^ m :=
    lt_of_lt_of_le hpi.2 (min_le_right _ _)
  have hpm' : -(1 / 2 : ℝ) * (3 : ℝ) ^ m < p i :=
    lt_of_le_of_lt (le_max_right _ _) hpi.1
  have hql : (p + z) i = p i + z i := rfl
  rw [hql]
  by_cases hup : MeetsUpperFace x m (n - 2) i
  · have hlow : ¬ MeetsLowerFace x m (n - 2) i :=
      not_meetsLowerFace_of_meetsUpperFace hmn hup
    rw [reflectedHi_of_meetsUpperFace hup, reflectedLo_of_not_meetsLowerFace hlow,
      windowLo_of_not_meetsLowerFace hlow]
    constructor
    · linarith only [hzi.1, hpl, hA, hB]
    · linarith only [hzi.2, hpm, hxi.2, hA, hB]
  · by_cases hlow : MeetsLowerFace x m (n - 2) i
    · rw [reflectedHi_of_not_meetsUpperFace hup, reflectedLo_of_meetsLowerFace hlow,
        windowHi_of_not_meetsUpperFace hup]
      constructor
      · linarith only [hzi.1, hpm', hxi.1, hA, hB]
      · linarith only [hzi.2, hpu, hA, hB]
    · rw [reflectedHi_of_not_meetsUpperFace hup, reflectedLo_of_not_meetsLowerFace hlow,
        windowHi_of_not_meetsUpperFace hup, windowLo_of_not_meetsLowerFace hlow]
      constructor
      · linarith only [hzi.1, hpl, hA, hB]
      · linarith only [hzi.2, hpu, hA, hB]

end

end Algsuperdiff.Section4.Provider.ExcessDecay
