/-
Copyright (c) 2026 Scott. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Scott
-/
import Algsuperdiff.Section3.Provider.MultiscaleEstimate.HomogenizationLanes
import Algsuperdiff.Section3.Provider.Orlicz.TwoTermCalculus

/-!
# Provider: the absorption calculus of `p.multiscale.estimate`

It carries nothing about the buckle's five terms; it carries only the three
calculi the final absorption runs on.

## 1. The two-lane envelope calculus

`TwoLaneEnvelope mu X A1 A2` says that the nonnegative observable `X` is
dominated almost surely by a sum `U + V` of two *nonnegative measurable*
observables carrying the squared-display Orlicz profiles `Gamma_1` and
`Gamma_{1/4}` at the scales `A1`, `A2`.  It is the shape in which every one of
the buckle's five terms arrives, and the shape in which they add.

The two nonnegativity fields are carried **by choice, not by necessity**.  This
module adds through `Provider.Orlicz.isBigOWith_gammaSigma_add`, whose
hypotheses include nonnegativity and measurability of both summands, and
carrying them in the package is cheaper than re-deriving them at each of the
five terms.  The fields are inert downstream, but they are what force
`isBigOWith_max_zero`, the `max`-truncations of `of_envelope` /
`of_isTwoTermBigOWith`, and the `hU0`/`hV0` plumbing.

The real obstruction to using `Probability.IsTwoTermBigOWith` as the carrier is
**a.e. versus pointwise domination** — that relation demands `Measurable X` and
`forall omega, X omega <= Y omega + Z omega`, while the buckle's five terms
dominate only almost surely — and not nonnegativity.

The calculus is closed under: weakening of both scales (`mono_scales`),
almost-sure domination (`of_ae_le`), addition (`add`), multiplication by a
nonnegative constant (`const_mul`), and it is generated by a single `Gamma_1`
tail (`of_isBigOWith_gammaOne`), by a deterministic constant (`of_le_const`),
by a raw measurable-and-tailed dominating pair (`of_envelope`) and by any
proved `Probability.IsTwoTermBigOWith` at the squared profiles
(`of_isTwoTermBigOWith`).

## 2. The square-root buckle's two amplitude identities

`sqrt_ordinaryLaneAmplitude` and `sqrt_rareLaneAmplitude` evaluate the square
roots of the two normal forms

```text
    A1 = K1 . (s^{-1})^2 . (eps^2 E^2 cgamma) ,
    A2 = K2 . (s^{-1})^4 . (eps^2 exp(-2 E^{-3} cgamma^{-1}))
```

in closed form.  Under the `eps^2` normalization of the squared display these
are exactly the two frozen amplitudes of
`Frozen/Section3/MultiscaleEstimate.lean` at `Cms := sqrt K`, and — this
is the point of the `eps^2` normalization — the **refinement clause is free**:
`sqrt A1 = sqrt K1 . eps . E . s^{-1} . sqrt cgamma` already has the refinement
amplitude's shape, so no `s <= Cms eps` hypothesis is ever consumed.  The two
comparisons are `sqrtOrdinaryLane_le_frozen` (main lane) and
`sqrtOrdinaryLane_le_refinement` (the second conjunct); the rare lane's is
`sqrtRareLane_le_frozen`.

Nearby statements elsewhere carry only the special cases `K = 1`,
`s^{-1} = 1`, or fix the lane constants `homLaneOrdinaryConst` /
`homLaneRareConst`.  Since the assembled display needs the free constant
throughout, this module proves the free-constant versions and routes the lanes
through them.

## 3. The absorption calculus

Three lemmas absorb the buckle's two non-lane *tail* families into the two
normal forms, using only the frozen root's own window binders `cstar^{-1}
eps^{-Cms} <= E` and `cgamma <= (E^{-1})^{10}` and the freedom to choose `Cms`
after every dimensional constant:

* `absorb_window_poly` — the polynomial lane `Q cstar^{-1} cgamma eps^{-p}
  (s^{-1})^2 <= K1. (s^{-1})^2 (eps^2 E^2 cgamma)` whenever `2 + p <= Cms` and
  `Q <= K1 E`.  This is the shape of the wave term and of the bad lane's
  `3^{5h} cgamma` summand (the exponent `p` there being `10 Chom log 3 + 8`,
  which is exactly the web conjunct `10 Chom log 3 + 8 <= Cms` plus the two
  units of `eps` that the `eps^2` normalization costs).
* `absorb_window_exp` — the exponentially small lane
  `Q exp(-(a E^{-2} cgamma^{-1})) <= K1 (eps^2 E^2 cgamma)`, by the elementary
  `x^2 exp(-x) <= 2` at `x = a E^{-2} cgamma^{-1}` followed by the window.
* `absorb_window_exp_rare` — its `Gamma_{1/4}` counterpart, where the printed
  rate `exp(-(Ccg^{-1} E^{-2} cgamma^{-1}))` must clear the frozen root's own
  `exp(-(2 E^{-3} cgamma^{-1}))`; the gap is the single inequality
  `4/a <= E`, and what remains is again the elementary two-factorial bound.
`window_inv_pow_le` is the single window utility they all share:
`(E^{-1})^n <= (3/2)^n eps^k` whenever `k <= n Cms`.

The deterministic remainder has NO absorption lemma of its own in this module.
Its three summands `cgamma^2 h^2`, `cgamma^2 s^{-2}` and `cgamma^2 E^4 |log
cgamma|^4` are absorbed in the consumer, by `remainderGap_le`,
`remainderScale_le` and `remainderLog_le` of `MultiscaleAbsorptionArith`.  What
this module supplies them is three window facts: `gamma_le_epsSq` (`cgamma <=
(3/2)^{10} eps^2`, consumed by the first two), `sqrt_gamma_mul_sq_le` (`sqrt
cgamma . E^2 <= (3/2)^3 eps^2`) and `sqrt_mul_abs_log_pow_four_le` (`sqrt x .
|log x|^4 <= 384`, the `k = 4` case of the elementary `x^k e^{-x} <= k!`), the
last two consumed by `remainderLog_le`.

Two further siblings close the section.  `le_rpow_neg_fifth` turns the frozen
root's `cgamma <= (E^{-1})^{10}` into the bad-event producer's own fifth-root
gate `E <= cgamma^{-1/5}`, and `measurable_tsum_of_nonneg'` is the measurability
of a nonnegative countable sum.  Both, like the section's own
`pow_mul_exp_neg_le'`, re-derive facts whose only other copies in this
development are `private`.
-/

namespace Algsuperdiff.Section3.Provider.MultiscaleEstimate

open _root_.MeasureTheory
open _root_.Homogenization
open _root_.Homogenization.IndependentSums

noncomputable section

/-! ## 1. The two-lane envelope calculus -/

section Envelope

variable {Omega : Type*} [MeasurableSpace Omega] {mu : Measure Omega}

/-- **The squared display's envelope package.**  `X` is almost surely dominated
by `U + V` with `U`, `V` nonnegative, measurable, and carrying the squared
profiles `Gamma_1` at scale `A1` and `Gamma_{1/4}` at scale `A2`.

`Probability.IsCommonEventTwoTermBigOWith` is the closest existing shape — two
witnesses, two profiles, one almost-sure domination event — but it is indexed
over a family, which these five terms are not.  `Probability.IsTwoTermBigOWith`
cannot serve as the carrier either, because it demands `Measurable X` and
`X omega <= Y omega + Z omega` pointwise, whereas the buckle's terms dominate
only almost surely; nonnegativity is not the obstruction (see §1 of the module
docstring). -/
def TwoLaneEnvelope (mu : Measure Omega) (X : Omega → ℝ) (A1 A2 : ℝ) : Prop :=
  ∃ U V : Omega → ℝ, Measurable U ∧ Measurable V ∧
    (∀ omega, 0 ≤ U omega) ∧ (∀ omega, 0 ≤ V omega) ∧
    IsBigOWith mu (gammaSigma 1) U A1 ∧
    IsBigOWith mu (gammaSigma (1 / 4)) V A2 ∧
    ∀ᵐ omega ∂mu, X omega ≤ U omega + V omega

/-- A constant observable below a nonnegative scale has that scale.

`Provider.Tail.isBigOWith_gammaSigma_const` is the same statement with the two
hypotheses in the other order, but it is not in this module's import closure,
so the three-line fact is proved here rather than imported. -/
theorem isBigOWith_gammaSigma_const {sigma : ℝ} {A c : ℝ} (hc : c ≤ A) (hA : 0 ≤ A) :
    IsBigOWith mu (gammaSigma sigma) (fun _ : Omega => c) A := by
  intro t ht
  have ht0 : (0 : ℝ) ≤ t := zero_le_one.trans ht
  have hAt : A ≤ A * t := le_mul_of_one_le_right hA ht
  have hempty : upperTailEvent (fun _ : Omega => c) (A * t) = (∅ : Set Omega) := by
    ext omega
    constructor
    · intro homega
      exact absurd (lt_of_le_of_lt (hc.trans hAt) homega) (lt_irrefl _)
    · intro homega
      exact homega.elim
  rw [hempty]
  simp only [measureReal_empty]
  exact inv_nonneg.2 (le_trans zero_le_one (one_le_gammaSigma (σ := sigma) ht0))

/-- The zero observable has every nonnegative scale.

This declaration is kept only as the `X := fun _ => 0` spelling the envelope
constructors below apply directly.  Five further `private` copies of the same
fact are named in the module header's twin census. -/
theorem isBigOWith_gammaSigma_zero {sigma : ℝ} {A : ℝ} (hA : 0 ≤ A) :
    IsBigOWith mu (gammaSigma sigma) (fun _ : Omega => (0 : ℝ)) A :=
  isBigOWith_gammaSigma_of_eq_zero hA (fun _ => rfl)

/-- Truncating a witness at zero preserves a positive weak-Orlicz scale.  the
proved `Provider.Tail.isBigOWith_max_zero` (`TailSqrt.lean`), which is stated at
the commuted spelling `max 0 (Y omega)`; the buckle
`Provider.Orlicz.isTwoTermBigOWithWitnesses_sqrt_of_sq_one_quarter` emits `max
(Y omega) 0`, so the one line of `max_comm` is the whole content.  (Two
`private` copies sit in
`Diffusivity/ApproximateRecurrence/PrincipalResponseMomentsCloseOrlicz.lean` and
in `Diffusivity/ApproximateRecurrence/PrincipalResponseDisplayTwoMoment.lean`,
the latter under the name `isBigOWith_max_zero_display`; both disclosed, neither
copied.) -/
theorem isBigOWith_max_zero {Psi : ℝ → ℝ} {Y : Omega → ℝ} {A : ℝ} (hA : 0 < A)
    (hY : IsBigOWith mu Psi Y A) :
    IsBigOWith mu Psi (fun omega => max (Y omega) 0) A := by
  have hfun : (fun omega => max (Y omega) 0) = fun omega => max 0 (Y omega) :=
    funext fun omega => max_comm _ _
  rw [hfun]
  exact Provider.Tail.isBigOWith_max_zero hA hY

/-- The envelope calculus is monotone in both scales. -/
theorem TwoLaneEnvelope.mono_scales [IsFiniteMeasure mu] {X : Omega → ℝ}
    {A1 A2 B1 B2 : ℝ} (h : TwoLaneEnvelope mu X A1 A2) (h1 : A1 ≤ B1)
    (h2 : A2 ≤ B2) :
    TwoLaneEnvelope mu X B1 B2 := by
  obtain ⟨U, V, hUm, hVm, hU0, hV0, hUt, hVt, hle⟩ := h
  exact ⟨U, V, hUm, hVm, hU0, hV0, hUt.mono_scale h1, hVt.mono_scale h2, hle⟩

/-- An almost-sure minorant inherits the envelope. -/
theorem TwoLaneEnvelope.of_ae_le {X X' : Omega → ℝ} {A1 A2 : ℝ}
    (h : TwoLaneEnvelope mu X A1 A2)
    (hle : ∀ᵐ omega ∂mu, X' omega ≤ X omega) :
    TwoLaneEnvelope mu X' A1 A2 := by
  obtain ⟨U, V, hUm, hVm, hU0, hV0, hUt, hVt, hdom⟩ := h
  refine ⟨U, V, hUm, hVm, hU0, hV0, hUt, hVt, ?_⟩
  filter_upwards [hdom, hle] with omega hdomega hleomega
  exact hleomega.trans hdomega

/-- The envelope calculus is closed under addition, at the two Orlicz triangle
constants of the squared display. -/
theorem TwoLaneEnvelope.add [IsFiniteMeasure mu] {X X' : Omega → ℝ}
    {A1 A2 B1 B2 : ℝ} (hA1 : 0 ≤ A1) (hA2 : 0 ≤ A2) (hB1 : 0 ≤ B1) (hB2 : 0 ≤ B2)
    (h : TwoLaneEnvelope mu X A1 A2) (h' : TwoLaneEnvelope mu X' B1 B2) :
    TwoLaneEnvelope mu (fun omega => X omega + X' omega)
      (gammaTriangleConst 1 * (A1 + B1))
      (gammaTriangleConst (1 / 4) * (A2 + B2)) := by
  obtain ⟨U, V, hUm, hVm, hU0, hV0, hUt, hVt, hdom⟩ := h
  obtain ⟨U', V', hUm', hVm', hU0', hV0', hUt', hVt', hdom'⟩ := h'
  refine ⟨fun omega => U omega + U' omega, fun omega => V omega + V' omega,
    hUm.add hUm', hVm.add hVm', fun omega => add_nonneg (hU0 omega) (hU0' omega),
    fun omega => add_nonneg (hV0 omega) (hV0' omega), ?_, ?_, ?_⟩
  · exact Provider.Orlicz.isBigOWith_gammaSigma_add one_pos hU0 hU0' hUm hUm'
      hA1 hB1 hUt hUt'
  · exact Provider.Orlicz.isBigOWith_gammaSigma_add (by norm_num) hV0 hV0' hVm hVm'
      hA2 hB2 hVt hVt'
  · filter_upwards [hdom, hdom'] with omega homega homega'
    have := add_le_add homega homega'
    linarith

/-- The envelope calculus is closed under multiplication by a nonnegative
constant. -/
theorem TwoLaneEnvelope.const_mul {X : Omega → ℝ} {A1 A2 c : ℝ} (hc : 0 ≤ c)
    (h : TwoLaneEnvelope mu X A1 A2) :
    TwoLaneEnvelope mu (fun omega => c * X omega) (c * A1) (c * A2) := by
  obtain ⟨U, V, hUm, hVm, hU0, hV0, hUt, hVt, hdom⟩ := h
  refine ⟨fun omega => c * U omega, fun omega => c * V omega,
    hUm.const_mul c, hVm.const_mul c, fun omega => mul_nonneg hc (hU0 omega),
    fun omega => mul_nonneg hc (hV0 omega), hUt.const_mul hc, hVt.const_mul hc, ?_⟩
  filter_upwards [hdom] with omega homega
  have := mul_le_mul_of_nonneg_left homega hc
  linarith [this]

/-- A single `Gamma_1` tail on a nonnegative measurable observable is an
envelope, with an empty rare lane. -/
theorem TwoLaneEnvelope.of_isBigOWith_gammaOne {U : Omega → ℝ} {A1 A2 : ℝ}
    (hUm : Measurable U) (hU0 : ∀ omega, 0 ≤ U omega)
    (hUt : IsBigOWith mu (gammaSigma 1) U A1) (hA2 : 0 ≤ A2) :
    TwoLaneEnvelope mu U A1 A2 :=
  ⟨U, fun _ => 0, hUm, measurable_const, hU0, fun _ => le_rfl, hUt,
    isBigOWith_gammaSigma_zero hA2, Filter.Eventually.of_forall fun omega => by simp⟩

/-- A deterministic bound is an envelope. -/
theorem TwoLaneEnvelope.of_le_const {X : Omega → ℝ} {A1 A2 c : ℝ}
    (hc : 0 ≤ c) (hcA : c ≤ A1) (hA2 : 0 ≤ A2)
    (hle : ∀ᵐ omega ∂mu, X omega ≤ c) :
    TwoLaneEnvelope mu X A1 A2 := by
  refine ⟨fun _ => c, fun _ => 0, measurable_const, measurable_const,
    fun _ => hc, fun _ => le_rfl, isBigOWith_gammaSigma_const hcA (hc.trans hcA),
    isBigOWith_gammaSigma_zero hA2, ?_⟩
  filter_upwards [hle] with omega homega
  simpa using homega

/-- A raw envelope pair — measurable, tailed, almost surely dominating — is an
envelope package: truncating both members at zero costs nothing, because both
scales are positive. -/
theorem TwoLaneEnvelope.of_envelope {X U V : Omega → ℝ} {A1 A2 : ℝ}
    (hA1 : 0 < A1) (hA2 : 0 < A2) (hUm : Measurable U) (hVm : Measurable V)
    (hUt : IsBigOWith mu (gammaSigma 1) U A1)
    (hVt : IsBigOWith mu (gammaSigma (1 / 4)) V A2)
    (hle : ∀ᵐ omega ∂mu, X omega ≤ U omega + V omega) :
    TwoLaneEnvelope mu X A1 A2 := by
  refine ⟨fun omega => max (U omega) 0, fun omega => max (V omega) 0,
    hUm.max measurable_const, hVm.max measurable_const,
    fun omega => le_max_right _ _, fun omega => le_max_right _ _,
    isBigOWith_max_zero hA1 hUt, isBigOWith_max_zero hA2 hVt, ?_⟩
  filter_upwards [hle] with omega homega
  exact homega.trans (add_le_add (le_max_left _ _) (le_max_left _ _))

/-- Every proved two-term bound at the squared display's profiles is an envelope:
its witnesses are truncated at zero, which costs nothing because both scales
are positive. -/
theorem TwoLaneEnvelope.of_isTwoTermBigOWith {X : Omega → ℝ} {A1 A2 : ℝ}
    (h : Probability.IsTwoTermBigOWith mu (gammaSigma 1) (gammaSigma (1 / 4))
      X A1 A2) :
    TwoLaneEnvelope mu X A1 A2 := by
  obtain ⟨Y, Z, _, _, hA1, hA2, _, hYm, hZm, hle, hYt, hZt⟩ := h
  refine ⟨fun omega => max (Y omega) 0, fun omega => max (Z omega) 0,
    hYm.max measurable_const, hZm.max measurable_const,
    fun omega => le_max_right _ _, fun omega => le_max_right _ _,
    isBigOWith_max_zero hA1 hYt, isBigOWith_max_zero hA2 hZt, ?_⟩
  exact Filter.Eventually.of_forall fun omega =>
    (hle omega).trans (add_le_add (le_max_left _ _) (le_max_left _ _))

end Envelope

/-! ## 2. The square-root buckle's amplitude normal forms -/

section Amplitudes

/-- The ordinary lane's normal form, in closed form. -/
theorem sqrt_ordinaryLaneAmplitude {K s eps Ev gam : ℝ} (hK : 0 ≤ K) (hs : 0 < s)
    (heps : 0 ≤ eps) (hEv : 0 ≤ Ev) :
    Real.sqrt (K * ((s⁻¹) ^ 2 * (eps ^ 2 * Ev ^ 2 * gam))) =
      Real.sqrt K * eps * Ev * s⁻¹ * Real.sqrt gam := by
  have hsinv : (0 : ℝ) ≤ s⁻¹ := (inv_pos.2 hs).le
  have hx : (0 : ℝ) ≤ Real.sqrt K * eps * Ev * s⁻¹ := by positivity
  have harg : K * ((s⁻¹) ^ 2 * (eps ^ 2 * Ev ^ 2 * gam)) =
      (Real.sqrt K * eps * Ev * s⁻¹) ^ 2 * gam := by
    have hsq : Real.sqrt K ^ 2 = K := Real.sq_sqrt hK
    calc K * ((s⁻¹) ^ 2 * (eps ^ 2 * Ev ^ 2 * gam))
        = (Real.sqrt K ^ 2 * eps ^ 2 * Ev ^ 2 * (s⁻¹) ^ 2) * gam := by rw [hsq]; ring
      _ = (Real.sqrt K * eps * Ev * s⁻¹) ^ 2 * gam := by ring
  rw [harg, Real.sqrt_mul (by positivity), Real.sqrt_sq hx]

/-- The rare lane's normal form, in closed form. -/
theorem sqrt_rareLaneAmplitude {K s eps X : ℝ} (hK : 0 ≤ K) (hs : 0 < s)
    (heps : 0 ≤ eps) :
    Real.sqrt (K * ((s⁻¹) ^ 4 * (eps ^ 2 * Real.exp (-(2 * X))))) =
      Real.sqrt K * eps * (s⁻¹) ^ 2 * Real.exp (-X) := by
  have hsinv : (0 : ℝ) ≤ s⁻¹ := (inv_pos.2 hs).le
  have hx : (0 : ℝ) ≤ Real.sqrt K * eps * (s⁻¹) ^ 2 * Real.exp (-X) := by positivity
  have hexp : Real.exp (-(2 * X)) = Real.exp (-X) ^ 2 := by
    rw [← Real.exp_nat_mul]
    congr 1
    ring
  have harg : K * ((s⁻¹) ^ 4 * (eps ^ 2 * Real.exp (-(2 * X)))) =
      (Real.sqrt K * eps * (s⁻¹) ^ 2 * Real.exp (-X)) ^ 2 := by
    have hsq : Real.sqrt K ^ 2 = K := Real.sq_sqrt hK
    rw [hexp]
    calc K * ((s⁻¹) ^ 4 * (eps ^ 2 * Real.exp (-X) ^ 2))
        = (Real.sqrt K ^ 2 * eps ^ 2 * ((s⁻¹) ^ 2) ^ 2 * Real.exp (-X) ^ 2) := by
          rw [hsq]; ring
      _ = (Real.sqrt K * eps * (s⁻¹) ^ 2 * Real.exp (-X)) ^ 2 := by ring
  rw [harg, Real.sqrt_sq hx]

/-- **The frozen root's ordinary amplitude, reached from the normal form.** -/
theorem sqrtOrdinaryLane_le_frozen {K Cms s eps Ev gam : ℝ} (hK : 0 ≤ K)
    (hs : 0 < s) (heps0 : 0 ≤ eps) (heps1 : eps ≤ 1) (hEv : 0 ≤ Ev)
    (hCms : Real.sqrt K ≤ Cms) :
    Real.sqrt (K * ((s⁻¹) ^ 2 * (eps ^ 2 * Ev ^ 2 * gam))) ≤
      Cms * Ev * s⁻¹ * Real.sqrt (eps * gam) := by
  rw [sqrt_ordinaryLaneAmplitude hK hs heps0 hEv,
    Real.sqrt_mul heps0]
  have hsinv : (0 : ℝ) ≤ s⁻¹ := (inv_pos.2 hs).le
  have hsq : Real.sqrt eps * Real.sqrt eps = eps := Real.mul_self_sqrt heps0
  have hse : Real.sqrt eps ≤ 1 := by
    rw [show (1 : ℝ) = Real.sqrt 1 by simp]
    exact Real.sqrt_le_sqrt heps1
  have hkey : Real.sqrt K * eps ≤ Cms * Real.sqrt eps := by
    calc Real.sqrt K * eps = Real.sqrt K * Real.sqrt eps * Real.sqrt eps := by
          rw [mul_assoc, hsq]
      _ ≤ Cms * 1 * Real.sqrt eps := by
          refine mul_le_mul_of_nonneg_right ?_ (Real.sqrt_nonneg _)
          exact mul_le_mul hCms hse (Real.sqrt_nonneg _)
            (le_trans (Real.sqrt_nonneg _) hCms)
      _ = Cms * Real.sqrt eps := by ring
  have hrest : (0 : ℝ) ≤ Ev * s⁻¹ * Real.sqrt gam := by positivity
  nlinarith [hkey, hrest, Real.sqrt_nonneg gam, Real.sqrt_nonneg eps]

/-- **The frozen root's refinement amplitude, reached from the SAME normal
form** — this is what the `eps^2` normalization buys: the second conjunct costs
nothing. -/
theorem sqrtOrdinaryLane_le_refinement {K Cms s eps Ev gam : ℝ} (hK : 0 ≤ K)
    (hs : 0 < s) (heps0 : 0 ≤ eps) (hEv : 0 ≤ Ev)
    (hCms : Real.sqrt K ≤ Cms) :
    Real.sqrt (K * ((s⁻¹) ^ 2 * (eps ^ 2 * Ev ^ 2 * gam))) ≤
      Cms * eps * Ev * s⁻¹ * Real.sqrt gam := by
  rw [sqrt_ordinaryLaneAmplitude hK hs heps0 hEv]
  have hsinv : (0 : ℝ) ≤ s⁻¹ := (inv_pos.2 hs).le
  have hrest : (0 : ℝ) ≤ eps * Ev * s⁻¹ * Real.sqrt gam := by positivity
  nlinarith [hCms, hrest, Real.sqrt_nonneg gam]

/-- **The frozen root's rare amplitude, reached from the normal form.** -/
theorem sqrtRareLane_le_frozen {K Cms s eps X : ℝ} (hK : 0 ≤ K) (hs : 0 < s)
    (heps0 : 0 ≤ eps) (hCms : Real.sqrt K ≤ Cms) :
    Real.sqrt (K * ((s⁻¹) ^ 4 * (eps ^ 2 * Real.exp (-(2 * X))))) ≤
      Cms * eps * (s⁻¹) ^ 2 * Real.exp (-X) := by
  rw [sqrt_rareLaneAmplitude hK hs heps0]
  have hsinv : (0 : ℝ) ≤ s⁻¹ := (inv_pos.2 hs).le
  have hrest : (0 : ℝ) ≤ eps * (s⁻¹) ^ 2 * Real.exp (-X) := by positivity
  nlinarith [hCms, hrest, (Real.exp_pos (-X)).le]

end Amplitudes

/-! ## 3. The absorption calculus -/

section Absorption

/-- The elementary `x^k e^{-x} <= k!`.  The only other copy here,
`HomogenizationLanes.pow_mul_exp_neg_le`, is `private`; the derivation from
mathlib's `Real.pow_div_factorial_le_exp` is the same. -/
theorem pow_mul_exp_neg_le' (k : ℕ) {x : ℝ} (hx : 0 ≤ x) :
    x ^ k * Real.exp (-x) ≤ (Nat.factorial k : ℝ) := by
  have hfac : (0 : ℝ) < (Nat.factorial k : ℝ) := by
    exact_mod_cast Nat.factorial_pos k
  have hterm : x ^ k / (Nat.factorial k : ℝ) ≤ Real.exp x :=
    Real.pow_div_factorial_le_exp (x := x) hx k
  have hxk : x ^ k ≤ (Nat.factorial k : ℝ) * Real.exp x := by
    rw [div_le_iff₀ hfac] at hterm
    linarith
  calc x ^ k * Real.exp (-x)
      ≤ ((Nat.factorial k : ℝ) * Real.exp x) * Real.exp (-x) :=
        mul_le_mul_of_nonneg_right hxk (Real.exp_pos _).le
    _ = (Nat.factorial k : ℝ) := by
        rw [mul_assoc, ← Real.exp_add]
        simp

/-- The quadratic decay of the exponential, in the form the two exponential
lanes consume.

The other copies of `exp(-x) <= 2/x^2` (both named `exp_neg_le_two_div_sq`, at
the `2 / x^2` spelling) are `private`, so the fact is re-derived here. -/
theorem exp_neg_le_two_mul_inv_sq {x : ℝ} (hx : 0 < x) :
    Real.exp (-x) ≤ 2 * (x⁻¹) ^ 2 := by
  have hkey : x ^ 2 * Real.exp (-x) ≤ 2 := by
    have := pow_mul_exp_neg_le' 2 hx.le
    simpa using this
  have hx2 : (0 : ℝ) < x ^ 2 := pow_pos hx 2
  have hinv : (x⁻¹) ^ 2 = (x ^ 2)⁻¹ := inv_pow x 2
  rw [hinv, ← div_eq_mul_inv, le_div_iff₀ hx2]
  linarith [hkey]

/-- **The window utility.**  Under the frozen root's own window binder, every
negative power of `E` is a power of `eps`, as soon as `Cms` has been chosen
large enough. -/
theorem window_inv_pow_le {eps Cms E : ℝ} (heps0 : 0 < eps) (heps1 : eps ≤ 1)
    (hE : 0 < E) (hfloor : (2 / 3 : ℝ) * eps ^ (-Cms) ≤ E) (n k : ℕ)
    (hk : (k : ℝ) ≤ (n : ℝ) * Cms) :
    (E⁻¹) ^ n ≤ (3 / 2 : ℝ) ^ n * eps ^ k := by
  have hrpow0 : (0 : ℝ) < eps ^ (-Cms) := Real.rpow_pos_of_pos heps0 _
  have hpos : (0 : ℝ) < (2 / 3 : ℝ) * eps ^ (-Cms) := by positivity
  have hstep : E⁻¹ ≤ (3 / 2 : ℝ) * eps ^ Cms := by
    have h1 : E⁻¹ ≤ ((2 / 3 : ℝ) * eps ^ (-Cms))⁻¹ := by
      rw [inv_le_inv₀ hE hpos]
      exact hfloor
    have h2 : ((2 / 3 : ℝ) * eps ^ (-Cms))⁻¹ = (3 / 2 : ℝ) * eps ^ Cms := by
      rw [Real.rpow_neg heps0.le, mul_inv, inv_inv]
      norm_num
    rwa [h2] at h1
  have hEinv0 : (0 : ℝ) ≤ E⁻¹ := (inv_pos.2 hE).le
  have hpow : (E⁻¹) ^ n ≤ ((3 / 2 : ℝ) * eps ^ Cms) ^ n :=
    pow_le_pow_left₀ hEinv0 hstep n
  have hsplit : ((3 / 2 : ℝ) * eps ^ Cms) ^ n =
      (3 / 2 : ℝ) ^ n * eps ^ ((n : ℝ) * Cms) := by
    rw [mul_pow, ← Real.rpow_natCast (eps ^ Cms) n, ← Real.rpow_mul heps0.le]
    ring_nf
  have hexp : eps ^ ((n : ℝ) * Cms) ≤ eps ^ (k : ℝ) :=
    Real.rpow_le_rpow_of_exponent_ge heps0 heps1 hk
  have hcast : eps ^ (k : ℝ) = eps ^ k := Real.rpow_natCast eps k
  calc (E⁻¹) ^ n ≤ ((3 / 2 : ℝ) * eps ^ Cms) ^ n := hpow
    _ = (3 / 2 : ℝ) ^ n * eps ^ ((n : ℝ) * Cms) := hsplit
    _ ≤ (3 / 2 : ℝ) ^ n * eps ^ (k : ℝ) := by
        exact mul_le_mul_of_nonneg_left hexp (by positivity)
    _ = (3 / 2 : ℝ) ^ n * eps ^ k := by rw [hcast]

/-- **The polynomial absorption.**  A dimensional constant `Q` times the
window's own `cstar^{-1}` and any negative power `eps^{-p}` is absorbed into
`K1 eps^2 E^2` as soon as `2 + p <= Cms` and `Q <= K1 E`. -/
theorem absorb_window_poly {cstarInv eps Cms E Q p K1 : ℝ} (hQ : 0 ≤ Q)
    (hcs : 0 ≤ cstarInv) (heps0 : 0 < eps) (heps1 : eps ≤ 1)
    (hCms : 2 + p ≤ Cms) (hQK : Q ≤ K1 * E)
    (hwin : cstarInv * eps ^ (-Cms) ≤ E) :
    Q * cstarInv * eps ^ (-p) ≤ K1 * (eps ^ 2 * E ^ 2) := by
  have hwin0 : (0 : ℝ) ≤ cstarInv * eps ^ (-Cms) :=
    mul_nonneg hcs (Real.rpow_pos_of_pos heps0 _).le
  have hQK0 : (0 : ℝ) ≤ K1 * E := hQ.trans hQK
  have hEsq : (K1 * E) * (cstarInv * eps ^ (-Cms)) ≤ K1 * E * E :=
    mul_le_mul_of_nonneg_left hwin hQK0
  have hstep1 : Q * (cstarInv * eps ^ (-Cms)) ≤ K1 * E * E :=
    le_trans (mul_le_mul_of_nonneg_right hQK hwin0) hEsq
  have heq : eps ^ (2 : ℕ) = eps ^ (2 : ℝ) := (Real.rpow_natCast eps 2).symm
  have hmerge : eps ^ (2 : ℝ) * eps ^ (-Cms) = eps ^ ((2 : ℝ) - Cms) := by
    rw [← Real.rpow_add heps0]
    ring_nf
  have hexp : eps ^ (-p) ≤ eps ^ ((2 : ℝ) - Cms) :=
    Real.rpow_le_rpow_of_exponent_ge heps0 heps1 (by linarith)
  have hQcs : (0 : ℝ) ≤ Q * cstarInv := mul_nonneg hQ hcs
  calc Q * cstarInv * eps ^ (-p) ≤ Q * cstarInv * eps ^ ((2 : ℝ) - Cms) :=
        mul_le_mul_of_nonneg_left hexp hQcs
    _ = eps ^ (2 : ℝ) * (Q * (cstarInv * eps ^ (-Cms))) := by
        rw [← hmerge]; ring
    _ ≤ eps ^ (2 : ℝ) * (K1 * E * E) := by
        exact mul_le_mul_of_nonneg_left hstep1 (Real.rpow_pos_of_pos heps0 _).le
    _ = K1 * (eps ^ (2 : ℕ) * E ^ 2) := by rw [heq]; ring

/-- **The exponential absorption, ordinary lane.**  The bad lane's printed rate
`exp(-(c E^{-2} cgamma^{-1}))` is polynomially smaller than the frozen root's
own `eps^2 E^2 cgamma`. -/
theorem absorb_window_exp {eps Cms E gam a Q K1 : ℝ} (hQ : 0 ≤ Q) (ha : 0 < a)
    (hE : 0 < E) (hgam : 0 < gam) (heps0 : 0 < eps) (heps1 : eps ≤ 1)
    (hgammaE : gam ≤ (E⁻¹) ^ 10) (hCms : (2 : ℝ) ≤ 8 * Cms)
    (hfloor : (2 / 3 : ℝ) * eps ^ (-Cms) ≤ E)
    (hK : 2 * Q * (a⁻¹) ^ 2 * (3 / 2 : ℝ) ^ 8 ≤ K1) :
    Q * Real.exp (-(a * (E⁻¹) ^ 2 * gam⁻¹)) ≤ K1 * (eps ^ 2 * E ^ 2 * gam) := by
  have hEne : E ≠ 0 := ne_of_gt hE
  have hgne : gam ≠ 0 := ne_of_gt hgam
  have hane : a ≠ 0 := ne_of_gt ha
  have hx0 : (0 : ℝ) < a * (E⁻¹) ^ 2 * gam⁻¹ := by positivity
  have hxinv : (a * (E⁻¹) ^ 2 * gam⁻¹)⁻¹ = a⁻¹ * (E ^ 2 * gam) := by
    field_simp
  have hEg0 : (0 : ℝ) ≤ E ^ 2 * gam := by positivity
  have hEg : E ^ 2 * gam ≤ (3 / 2 : ℝ) ^ 8 * eps ^ 2 := by
    have h1 : E ^ 2 * gam ≤ (E⁻¹) ^ 8 := by
      have h2 : E ^ 2 * gam ≤ E ^ 2 * (E⁻¹) ^ 10 :=
        mul_le_mul_of_nonneg_left hgammaE (by positivity)
      have h3 : E ^ 2 * (E⁻¹) ^ 10 = (E⁻¹) ^ 8 := by field_simp
      linarith [h2, h3.le, h3.ge]
    exact h1.trans (window_inv_pow_le heps0 heps1 hE hfloor 8 2 (by push_cast; linarith))
  have hexp : Real.exp (-(a * (E⁻¹) ^ 2 * gam⁻¹)) ≤
      2 * ((a⁻¹) ^ 2 * (E ^ 2 * gam) ^ 2) := by
    have h := exp_neg_le_two_mul_inv_sq hx0
    rw [hxinv] at h
    calc Real.exp (-(a * (E⁻¹) ^ 2 * gam⁻¹))
        ≤ 2 * (a⁻¹ * (E ^ 2 * gam)) ^ 2 := h
      _ = 2 * ((a⁻¹) ^ 2 * (E ^ 2 * gam) ^ 2) := by ring
  have hstep : Q * Real.exp (-(a * (E⁻¹) ^ 2 * gam⁻¹)) ≤
      2 * Q * (a⁻¹) ^ 2 * (E ^ 2 * gam) ^ 2 := by
    have := mul_le_mul_of_nonneg_left hexp hQ
    linarith [this]
  have hsq : (E ^ 2 * gam) ^ 2 ≤ ((3 / 2 : ℝ) ^ 8 * eps ^ 2) * (E ^ 2 * gam) := by
    have : (E ^ 2 * gam) * (E ^ 2 * gam) ≤ ((3 / 2 : ℝ) ^ 8 * eps ^ 2) * (E ^ 2 * gam) :=
      mul_le_mul_of_nonneg_right hEg hEg0
    nlinarith [this]
  have hQa : (0 : ℝ) ≤ 2 * Q * (a⁻¹) ^ 2 := by positivity
  have hchain : 2 * Q * (a⁻¹) ^ 2 * (E ^ 2 * gam) ^ 2 ≤
      (2 * Q * (a⁻¹) ^ 2 * (3 / 2 : ℝ) ^ 8) * (eps ^ 2 * E ^ 2 * gam) := by
    have := mul_le_mul_of_nonneg_left hsq hQa
    nlinarith [this]
  have hfinal : (2 * Q * (a⁻¹) ^ 2 * (3 / 2 : ℝ) ^ 8) * (eps ^ 2 * E ^ 2 * gam) ≤
      K1 * (eps ^ 2 * E ^ 2 * gam) :=
    mul_le_mul_of_nonneg_right hK (by positivity)
  linarith [hstep, hchain, hfinal]

/-- **The exponential absorption, rare lane.**  The bad lane's `Gamma_{2/7}`
rate `exp(-(Ccg^{-1} E^{-2} cgamma^{-1}))` clears the frozen root's own
`exp(-(2 E^{-3} cgamma^{-1}))` as soon as `4/a <= E`. -/
theorem absorb_window_exp_rare {eps Cms E gam a Q K2 : ℝ} (hQ : 0 ≤ Q) (ha : 0 < a)
    (hE : 0 < E) (hgam : 0 < gam) (heps0 : 0 < eps) (heps1 : eps ≤ 1)
    (hgammaE : gam ≤ (E⁻¹) ^ 10) (hEa : 4 / a ≤ E) (hCms : (2 : ℝ) ≤ 16 * Cms)
    (hfloor : (2 / 3 : ℝ) * eps ^ (-Cms) ≤ E)
    (hK : 8 * Q * (a⁻¹) ^ 2 * (3 / 2 : ℝ) ^ 16 ≤ K2) :
    Q * Real.exp (-(a * (E⁻¹) ^ 2 * gam⁻¹)) ≤
      K2 * (eps ^ 2 * Real.exp (-(2 * (E⁻¹) ^ 3 * gam⁻¹))) := by
  have hEne : E ≠ 0 := ne_of_gt hE
  have hgne : gam ≠ 0 := ne_of_gt hgam
  have hane : a ≠ 0 := ne_of_gt ha
  have hu0 : (0 : ℝ) < (E⁻¹) ^ 2 * gam⁻¹ := by positivity
  have hEinv : E⁻¹ ≤ a / 4 := by
    rw [inv_le_comm₀ hE (by positivity : (0 : ℝ) < a / 4)]
    have hrw : (a / 4)⁻¹ = 4 / a := by field_simp
    rw [hrw]
    exact hEa
  have hgap : a / 2 ≤ a - 2 * E⁻¹ := by linarith
  have hsplit : Real.exp (-(a * (E⁻¹) ^ 2 * gam⁻¹)) =
      Real.exp (-(((E⁻¹) ^ 2 * gam⁻¹) * (a - 2 * E⁻¹))) *
        Real.exp (-(2 * (E⁻¹) ^ 3 * gam⁻¹)) := by
    rw [← Real.exp_add]
    congr 1
    field_simp
    ring
  have hmono : Real.exp (-(((E⁻¹) ^ 2 * gam⁻¹) * (a - 2 * E⁻¹))) ≤
      Real.exp (-((a / 2) * ((E⁻¹) ^ 2 * gam⁻¹))) := by
    refine Real.exp_le_exp.2 ?_
    have := mul_le_mul_of_nonneg_left hgap hu0.le
    linarith [this]
  have hy0 : (0 : ℝ) < (a / 2) * ((E⁻¹) ^ 2 * gam⁻¹) := by positivity
  have hyinv : ((a / 2) * ((E⁻¹) ^ 2 * gam⁻¹))⁻¹ = (2 / a) * (E ^ 2 * gam) := by
    field_simp
  have hEg0 : (0 : ℝ) ≤ E ^ 2 * gam := by positivity
  have hEg : E ^ 2 * gam ≤ (E⁻¹) ^ 8 := by
    have h2 : E ^ 2 * gam ≤ E ^ 2 * (E⁻¹) ^ 10 :=
      mul_le_mul_of_nonneg_left hgammaE (by positivity)
    have h3 : E ^ 2 * (E⁻¹) ^ 10 = (E⁻¹) ^ 8 := by field_simp
    linarith [h2, h3.le, h3.ge]
  have hEg16 : (E ^ 2 * gam) ^ 2 ≤ (3 / 2 : ℝ) ^ 16 * eps ^ 2 := by
    have h1 : (E ^ 2 * gam) ^ 2 ≤ ((E⁻¹) ^ 8) ^ 2 :=
      pow_le_pow_left₀ hEg0 hEg 2
    have h2 : ((E⁻¹) ^ 8) ^ 2 = (E⁻¹) ^ 16 := by ring
    have h3 : (E⁻¹) ^ 16 ≤ (3 / 2 : ℝ) ^ 16 * eps ^ 2 :=
      window_inv_pow_le heps0 heps1 hE hfloor 16 2 (by push_cast; linarith)
    linarith [h1, h2.le, h2.ge, h3]
  have hquad : Real.exp (-((a / 2) * ((E⁻¹) ^ 2 * gam⁻¹))) ≤
      8 * ((a⁻¹) ^ 2 * (E ^ 2 * gam) ^ 2) := by
    have h := exp_neg_le_two_mul_inv_sq hy0
    rw [hyinv] at h
    calc Real.exp (-((a / 2) * ((E⁻¹) ^ 2 * gam⁻¹)))
        ≤ 2 * ((2 / a) * (E ^ 2 * gam)) ^ 2 := h
      _ = 8 * ((a⁻¹) ^ 2 * (E ^ 2 * gam) ^ 2) := by
          field_simp
          ring
  have hfirst : Q * Real.exp (-(((E⁻¹) ^ 2 * gam⁻¹) * (a - 2 * E⁻¹))) ≤
      K2 * eps ^ 2 := by
    have h1 : Real.exp (-(((E⁻¹) ^ 2 * gam⁻¹) * (a - 2 * E⁻¹))) ≤
        8 * ((a⁻¹) ^ 2 * (E ^ 2 * gam) ^ 2) := hmono.trans hquad
    have h2 : Q * Real.exp (-(((E⁻¹) ^ 2 * gam⁻¹) * (a - 2 * E⁻¹))) ≤
        8 * Q * (a⁻¹) ^ 2 * (E ^ 2 * gam) ^ 2 := by
      have := mul_le_mul_of_nonneg_left h1 hQ
      linarith [this]
    have h3 : 8 * Q * (a⁻¹) ^ 2 * (E ^ 2 * gam) ^ 2 ≤
        8 * Q * (a⁻¹) ^ 2 * ((3 / 2 : ℝ) ^ 16 * eps ^ 2) :=
      mul_le_mul_of_nonneg_left hEg16 (by positivity)
    have h4 : 8 * Q * (a⁻¹) ^ 2 * ((3 / 2 : ℝ) ^ 16 * eps ^ 2) ≤ K2 * eps ^ 2 := by
      have := mul_le_mul_of_nonneg_right hK (by positivity : (0:ℝ) ≤ eps ^ 2)
      linarith [this]
    linarith [h2, h3, h4]
  rw [hsplit]
  have hpos : (0 : ℝ) < Real.exp (-(2 * (E⁻¹) ^ 3 * gam⁻¹)) := Real.exp_pos _
  calc Q * (Real.exp (-(((E⁻¹) ^ 2 * gam⁻¹) * (a - 2 * E⁻¹))) *
        Real.exp (-(2 * (E⁻¹) ^ 3 * gam⁻¹)))
      = (Q * Real.exp (-(((E⁻¹) ^ 2 * gam⁻¹) * (a - 2 * E⁻¹)))) *
          Real.exp (-(2 * (E⁻¹) ^ 3 * gam⁻¹)) := by ring
    _ ≤ (K2 * eps ^ 2) * Real.exp (-(2 * (E⁻¹) ^ 3 * gam⁻¹)) :=
        mul_le_mul_of_nonneg_right hfirst hpos.le
    _ = K2 * (eps ^ 2 * Real.exp (-(2 * (E⁻¹) ^ 3 * gam⁻¹))) := by ring

/-- The elementary `sqrt x . |log x|^4 <= 384` on `(0,1]`, the `k = 4` case of
`pow_mul_exp_neg_le'`. -/
theorem sqrt_mul_abs_log_pow_four_le {x : ℝ} (hx0 : 0 < x) (hx1 : x ≤ 1) :
    Real.sqrt x * |Real.log x| ^ 4 ≤ 384 := by
  have hlog : Real.log x ≤ 0 := Real.log_nonpos hx0.le hx1
  have habs : |Real.log x| = -Real.log x := abs_of_nonpos hlog
  set u : ℝ := -Real.log x with hu
  have hu0 : (0 : ℝ) ≤ u := by rw [hu]; linarith
  have hsqrt : Real.sqrt x = Real.exp (-(u / 2)) := by
    rw [Real.sqrt_eq_rpow, Real.rpow_def_of_pos hx0, hu]
    congr 1
    ring
  have hkey : (u / 2) ^ 4 * Real.exp (-(u / 2)) ≤ (Nat.factorial 4 : ℝ) :=
    pow_mul_exp_neg_le' 4 (by linarith)
  have hfac : (Nat.factorial 4 : ℝ) = 24 := by norm_num [Nat.factorial]
  rw [habs, hsqrt]
  have hexpand : Real.exp (-(u / 2)) * u ^ 4 =
      16 * ((u / 2) ^ 4 * Real.exp (-(u / 2))) := by ring
  rw [hexpand]
  rw [hfac] at hkey
  linarith [hkey]

/-- `cgamma` is below `eps^2` on the window. -/
theorem gamma_le_epsSq {eps Cms E gam : ℝ} (heps0 : 0 < eps) (heps1 : eps ≤ 1)
    (hE : 0 < E) (hfloor : (2 / 3 : ℝ) * eps ^ (-Cms) ≤ E)
    (hCms : (2 : ℝ) ≤ 10 * Cms) (hgammaE : gam ≤ (E⁻¹) ^ 10) :
    gam ≤ (3 / 2 : ℝ) ^ 10 * eps ^ 2 :=
  hgammaE.trans (window_inv_pow_le heps0 heps1 hE hfloor 10 2 (by push_cast; linarith))

/-- `sqrt cgamma . E^2` is below `eps^2` on the window: this is the remainder
term's `E^4 |log cgamma|^4` summand's home. -/
theorem sqrt_gamma_mul_sq_le {eps Cms E gam : ℝ} (heps0 : 0 < eps) (heps1 : eps ≤ 1)
    (hE : 0 < E) (hfloor : (2 / 3 : ℝ) * eps ^ (-Cms) ≤ E)
    (hCms : (2 : ℝ) ≤ 3 * Cms) (hgammaE : gam ≤ (E⁻¹) ^ 10) :
    Real.sqrt gam * E ^ 2 ≤ (3 / 2 : ℝ) ^ 3 * eps ^ 2 := by
  have hEinv0 : (0 : ℝ) ≤ E⁻¹ := (inv_pos.2 hE).le
  have hsplit : (E⁻¹) ^ 10 = ((E⁻¹) ^ 5) ^ 2 := by ring
  have hs1 : Real.sqrt gam ≤ (E⁻¹) ^ 5 := by
    have h := Real.sqrt_le_sqrt hgammaE
    rwa [hsplit, Real.sqrt_sq (by positivity)] at h
  have h2 : Real.sqrt gam * E ^ 2 ≤ (E⁻¹) ^ 5 * E ^ 2 :=
    mul_le_mul_of_nonneg_right hs1 (by positivity)
  have h3 : (E⁻¹) ^ 5 * E ^ 2 = (E⁻¹) ^ 3 := by
    field_simp
  have h4 : (E⁻¹) ^ 3 ≤ (3 / 2 : ℝ) ^ 3 * eps ^ 2 :=
    window_inv_pow_le heps0 heps1 hE hfloor 3 2 (by push_cast; linarith)
  linarith [h2, h3.le, h3.ge, h4]

/-! ### Two re-derived siblings -/

/-- The frozen root's smallness gate implies the bad-event producer's own
fifth-root gate.  The sibling
`Provider.BadEvents.le_rpow_neg_fifth_of_gamma_le_inv_pow_ten` is `private`, so
the same derivation is repeated here. -/
theorem le_rpow_neg_fifth {Ev gam : ℝ} (hE : 1 ≤ Ev) (hgam : 0 < gam)
    (hgammaE : gam ≤ Ev⁻¹ ^ (10 : ℕ)) :
    Ev ≤ gam ^ (-(1 / 5 : ℝ)) := by
  have hE0 : 0 ≤ Ev := zero_le_one.trans hE
  have hEpos : 0 < Ev := zero_lt_one.trans_le hE
  have hEinv : gam ≤ (Ev ^ (10 : ℕ))⁻¹ := by
    simpa only [inv_pow] using hgammaE
  have hE10 : Ev ^ (10 : ℕ) ≤ gam⁻¹ := by
    rw [le_inv_comm₀ (pow_pos hEpos 10) hgam]
    exact hEinv
  have hE5 : Ev ^ (5 : ℕ) ≤ gam⁻¹ :=
    (pow_le_pow_right₀ hE (by norm_num : (5 : ℕ) ≤ 10)).trans hE10
  have hroot : Ev ≤ (gam⁻¹) ^ (5 : ℝ)⁻¹ := by
    rw [Real.le_rpow_inv_iff_of_pos hE0 (inv_pos.mpr hgam).le (by norm_num)]
    exact (Real.rpow_natCast Ev 5).trans_le hE5
  calc
    Ev ≤ (gam⁻¹) ^ (5 : ℝ)⁻¹ := hroot
    _ = (gam⁻¹) ^ (1 / 5 : ℝ) := by norm_num
    _ = (gam ^ (-1 : ℝ)) ^ (1 / 5 : ℝ) := by rw [Real.rpow_neg_one]
    _ = gam ^ ((-1 : ℝ) * (1 / 5 : ℝ)) := (Real.rpow_mul hgam.le _ _).symm
    _ = gam ^ (-(1 / 5 : ℝ)) := by norm_num


/-- Measurability of a nonnegative countable sum, through
`Measurable.nnreal_tsum`.  `HomogenizationLanes.measurable_tsum_of_nonneg` is
`private`, and `Provider.CoarseEllipticity.measurable_tsum_of_nonneg` demands
the extra hypothesis `forall omega, Summable (fun k => f k omega)`, which this
module's call sites do not have; the summability-free version is therefore
proved here. -/
theorem measurable_tsum_of_nonneg' {Omega : Type*} [MeasurableSpace Omega]
    {X : ℕ → Omega → ℝ} (hXm : ∀ k, Measurable (X k))
    (hX0 : ∀ k omega, 0 ≤ X k omega) :
    Measurable (fun omega => ∑' k : ℕ, X k omega) := by
  have hnn := (Measurable.nnreal_tsum fun k => (hXm k).real_toNNReal).coe_nnreal_real
  convert hnn using 1
  funext omega
  rw [NNReal.coe_tsum]
  refine tsum_congr fun k => ?_
  rw [Real.toNNReal_of_nonneg (hX0 k omega)]
  rfl


end Absorption

end

end Algsuperdiff.Section3.Provider.MultiscaleEstimate
