import Algsuperdiff.Section3.Provider.Affine.KuhnInterpolation
import Algsuperdiff.Section3.Provider.Whitney.ClusterDiameter
import Algsuperdiff.Section3.Provider.Whitney.SimplexPartition
import Homogenization.CoarseGraining.ResponseIdentities.Foundations.Algebra

/-!
# The global vertex datum of `l.piecewise.affine.approx`

This module provides a local vertex-data implementation of Step 1 associated
with ABK26's `l.piecewise.affine.approx` at the level the corrected reading
demands: the **global** assignment of a value to every point of `ℝ^d`, from
which each cell of `SW(□_m)` reads off its own vertex data, and the two
structural clauses of `e.hat.linear.properties` that assignment satisfies.

## The printed construction and the correction it needs

The manuscript fixes a `2`-connected component `𝒞_j` of the bad family `ℐ` and
sets, at the vertices `V_j` of the common coarse mesh of `𝒩(𝒞_j)`,

```
ℓ̂_e(v) := ℓ_e(v)              if v ∉ V(𝒞_j) ,
ℓ̂_e(v) := ⨍_{𝒞_j} ℓ_e(x) dx   if v ∈ V(𝒞_j) ,
```

and does this "one 2-connected component at a time", justified by the assertion
that the neighborhoods of distinct components are disjoint.  That assertion is
**false**, and there are two admissible constructions: *assign the vertex data
once on the full simplex complex*, or *superpose the component corrections
while allowing overlap on good cubes*.

Throughout, "connected component" is read at the **touching** relation:
`badComponent`, whose chains join cubes at `dist(□,□') = 0` — a strictly finer
partition than the one generated by `dist ≤ 1` — and the component average is
taken over the touching component.  That relation is hard-wired (`badComponent`
→ `BadChain` → `CubeTouch`), so reading the component instead at the
scale-covariant relation `dist ≤ 3^j` would change the datum and require a
revisit of this file; the abstract index type `I` does not insulate against it.

`competitorVertexData` below is the first construction, implemented at the
touching reading above (the datum-level case split is the manuscript's own):

```
ĝ_p(v) = ⨍_{𝒞(v)} ℓ_p    if v lies in some closed bad cube, 𝒞(v) its component,
ĝ_p(v) = ℓ_p(v)          otherwise.
```

**The two constructions are the same function at the vertex-datum level**, and
this file proves that rather than assuming it.
`badComponent_eq_of_mem_closedBall` says that if one point
lies in two closed bad cubes then those cubes lie in the *same* component
(they touch, so one chain step joins them).  Hence at most one component ever
claims a vertex, the superposition `ℓ_p + Σ_𝒞 (⨍_𝒞 ℓ_p − ℓ_p)·1_{V(𝒞)}` has at
most one nonzero summand at each point, and no summation, no choice of witness
and no disjointness hypothesis is needed.  `claimedBadComponent` is that
component, defined *without* `Classical.choose`: it collects every bad cube
chain-joined to *some* bad cube whose closed cube contains `v`.

## The active-component reading

The printed component-local gradient ratio is false under the required
overlap-safe construction.  The correct form is the **sum over the active
components** `𝒜_R = {𝒞 : R ∈ 𝒩(𝒞)}` of `diam(𝒞)/ρ_𝒞`, optionally followed by a
dimension-only overlap count `|𝒜_R| ≤ M(d)`.

Under the *single-assignment* reading implemented here the deviation at one
vertex is governed by the one component that claims it, so what the per-cell
estimate needs is a bound valid for **every** active component -- the `hact`
binder of `abs_competitorVertexData_sub_linearFn_le_of_forall_touching`, which
quantifies over exactly the bad cubes touching the cell's Whitney cube, i.e.
over exactly `𝒜_R`.  Consequently **no overlap count is consumed here**:
`card_le_eleven_pow_of_forall_cubeTouch` is not used and is not needed for this
estimate.  It remains the instrument for the superposition presentation, where
the corrections genuinely add.

## Scope: what this file does NOT do

* It does **not** build the global piecewise-affine function `ℓ̂_p` and asserts
  **no** continuity, `H¹` membership or subordination.  Every statement is
  per-cell: a cell interpolates the global datum at *its own* vertices
  (`kuhnInterp`/`kuhnSlope` of `KuhnInterpolation`).  Continuity across hanging
  vertices is the common-coarse-mesh obligation, and `e.hat.linear.1` is
  untouched; both remain open.  In `sum_of_a_decomp` those are carried by the
  *separate* binders `hF`/`hG`, while `hbadF`/`hoffF` are exactly the two
  clauses proved here.
* It asserts no face-to-face property of `SW(□_m)` and no layer window: no
  layer, no `n_j`, no three-layer statement occurs.  Nothing here assumes that
  the neighborhoods of distinct components are disjoint — the point of the
  construction is that it does not need to.
* No slope-square and no collar constant enters.

## References

* ABK26: `l.piecewise.affine.approx` and `e.hat.linear.properties` (the Step-1
  construction and the two structural clauses it must satisfy); the
  disjointness claim for the neighborhoods of distinct components; the Step-2
  vertex bound; and the definitions of `ℐ`, `𝒩(𝒥)`, the components, and
  `ℓ_e(x) = e·x`.
-/

namespace Algsuperdiff.Section3.Provider.Affine

open Homogenization MeasureTheory
open Algsuperdiff.Section3.Provider.Whitney

noncomputable section

variable {d : ℕ}

/-! ## The `ℓ¹` size of a slope -/

/-- `|p|_{ℓ¹} = ∑_i |p_i|`, the constant in the elementary bound
`|ℓ_p(x) − ℓ_p(y)| ≤ |p|_{ℓ¹} · ‖x − y‖_∞` used for the Step-2 vertex
estimate.  The ambient metric on `Vec d` is the sup metric, so this — not the
Euclidean norm — is the constant the diameter pairs with;
`sq_vecNormOne_le` converts it to the Euclidean norm at the cost of `√d`. -/
def vecNormOne (p : Vec d) : ℝ := ∑ i, |p i|

@[simp] theorem vecNormOne_apply (p : Vec d) : vecNormOne p = ∑ i, |p i| := rfl

theorem vecNormOne_nonneg (p : Vec d) : 0 ≤ vecNormOne p :=
  Finset.sum_nonneg fun i _ => abs_nonneg (p i)

/-- Cauchy--Schwarz: `(∑_i |p_i|)² ≤ d · |p|²`. -/
theorem sq_vecNormOne_le (p : Vec d) : vecNormOne p ^ 2 ≤ (d : ℝ) * vecNormSq p := by
  have h := sq_sum_le_card_mul_sum_sq (s := (Finset.univ : Finset (Fin d)))
    (f := fun i => |p i|)
  have hcard : ((Finset.univ : Finset (Fin d)).card : ℝ) = (d : ℝ) := by
    rw [Finset.card_univ, Fintype.card_fin]
  have hsq : ∑ i, |p i| ^ 2 = vecNormSq p := by
    simp only [vecNormSq, vecDot, sq_abs]
    exact Finset.sum_congr rfl fun i _ => by ring
  rw [vecNormOne_apply]
  rw [hcard, hsq] at h
  exact h

/-- `|ℓ_p(x) − ℓ_p(y)| ≤ |p|_{ℓ¹} · dist(x, y)` on `Vec d`, whose metric is the
sup metric. -/
theorem abs_linearFn_sub_le (p x y : Vec d) :
    |linearFn p x - linearFn p y| ≤ vecNormOne p * dist x y := by
  have hstep : ∀ i : Fin d, |p i * x i - p i * y i| ≤ |p i| * dist x y := by
    intro i
    rw [← mul_sub, abs_mul]
    exact mul_le_mul_of_nonneg_left
      (by rw [← Real.dist_eq]; exact dist_le_pi_dist x y i) (abs_nonneg (p i))
  calc
    |linearFn p x - linearFn p y| = |∑ i, (p i * x i - p i * y i)| := by
        simp only [linearFn_apply, vecDot, ← Finset.sum_sub_distrib]
    _ ≤ ∑ i, |p i * x i - p i * y i| := Finset.abs_sum_le_sum_abs _ _
    _ ≤ ∑ i, |p i| * dist x y := Finset.sum_le_sum fun i _ => hstep i
    _ = vecNormOne p * dist x y := by rw [vecNormOne_apply, ← Finset.sum_mul]

theorem continuous_linearFn (p : Vec d) : Continuous (linearFn (d := d) p) := by
  show Continuous fun x : Vec d => ∑ i, p i * x i
  exact continuous_finset_sum _ fun i _ => continuous_const.mul (continuous_apply i)

/-! ## The component that claims a point -/

/-- **The bad component claiming the point `v`.**  A vertex of the mesh is "in
`V(𝒞_j)`" exactly when it lies in one of the closed cubes of the component ---
NOTE: the manuscript defines `V(·)` only for simplices; `V(𝒞_j)` for a cube
collection is this file's closed reading, forced by clause 1 (the zero-slope
conclusion on every bad cube needs all its vertices, boundary included) --- of
the component `𝒞_j`; this is the family of *all* bad cubes chain-joined to some
bad cube whose closed cube contains `v`.

Two closed bad cubes containing a common point *touch*, hence lie in one
component (`badComponent_eq_of_mem_closedBall`), so this set is the component
claiming `v` whenever there is one, and is empty otherwise.  No witness is
chosen: the definition quantifies existentially inside the set-builder. -/
def claimedBadComponent (I : Set (TriadicCube d)) (v : Vec d) : Set (TriadicCube d) :=
  {Q | Q ∈ I ∧ ∃ R ∈ I,
    v ∈ Metric.closedBall (cubeCenter R) (Homogenization.cubeRadius R) ∧ BadChain I R Q}

/-- **The claimed component is the component of any witnessing cube.** -/
theorem claimedBadComponent_eq_badComponent {I : Set (TriadicCube d)}
    {R : TriadicCube d} (hR : R ∈ I) {v : Vec d}
    (hv : v ∈ Metric.closedBall (cubeCenter R) (Homogenization.cubeRadius R)) :
    claimedBadComponent I v = badComponent I R := by
  ext Q
  constructor
  · rintro ⟨hQ, S, hS, hvS, hSQ⟩
    exact ⟨hQ, Relation.ReflTransGen.head ⟨hR, hS, ⟨v, hv, hvS⟩⟩ hSQ⟩
  · rintro ⟨hQ, hRQ⟩
    exact ⟨hQ, R, hR, hv, hRQ⟩

/-! ## The component average `⨍_{𝒞} ℓ_p` -/

/-- **ABK26's `⨍_{𝒞_j} ℓ_e(x) dx`**: the mean of the linear function `ℓ_p` over the
region occupied by the component `𝒞`, at this repository's `volumeAverage`
carrier and over the closed carrier of the family (see the module docstring). -/
def componentAverage (C : Set (TriadicCube d)) (p : Vec d) : ℝ :=
  volumeAverage (closedCubeCarrier C) (linearFn p)

@[simp] theorem componentAverage_apply (C : Set (TriadicCube d)) (p : Vec d) :
    componentAverage C p = volumeAverage (closedCubeCarrier C) (linearFn p) := rfl

theorem isCompact_closedCubeCarrier {C : Set (TriadicCube d)} (hfin : C.Finite) :
    IsCompact (closedCubeCarrier C) :=
  hfin.isCompact_biUnion fun Q _ => isCompact_closedBall (cubeCenter Q) _

theorem volume_closedCubeCarrier_ne_zero {C : Set (TriadicCube d)}
    (hne : C.Nonempty) : volume (closedCubeCarrier C) ≠ 0 := by
  obtain ⟨Q, hQ⟩ := hne
  intro hzero
  have hsub : openCubeSet Q ⊆ closedCubeCarrier C :=
    (openCubeSet_subset_cubeSet Q).trans
      ((cubeSet_subset_closedBall Q).trans (closedBall_subset_closedCubeCarrier hQ))
  have hle : volume (openCubeSet Q) = 0 :=
    le_antisymm (hzero ▸ measure_mono hsub) (zero_le _)
  have hpos : 0 < cubeVolume Q := cubeVolume_pos Q
  rw [← volume_openCubeSet_toReal Q, hle, ENNReal.toReal_zero] at hpos
  exact lt_irrefl 0 hpos

/-! ## The global vertex datum -/

open Classical in
/-- **The vertex datum of `l.piecewise.affine.approx`**, in the global
single-assignment form prescribed: a point lying in a closed bad cube receives
the average of `ℓ_p` over the component claiming it, every other point keeps
`ℓ_p`.

The `if` is the manuscript's own case split `v ∈ V(𝒞_j)` versus `v ∉ V(𝒞_j)`;
neither branch is a fallback and neither uses a chosen witness.  The two
defining equations are `competitorVertexData_of_mem_closedBall` and
`competitorVertexData_of_notMem_closedCubeCarrier`. -/
def competitorVertexData (I : Set (TriadicCube d)) (p : Vec d) (v : Vec d) : ℝ :=
  if v ∈ closedCubeCarrier I then componentAverage (claimedBadComponent I v) p
  else linearFn p v

/-- **The bad branch**: at a point of a closed bad cube the datum is the component
average `⨍_{𝒞} ℓ_p`. -/
theorem competitorVertexData_of_mem_closedBall {I : Set (TriadicCube d)}
    {R : TriadicCube d} (hR : R ∈ I) (p : Vec d) {v : Vec d}
    (hv : v ∈ Metric.closedBall (cubeCenter R) (Homogenization.cubeRadius R)) :
    competitorVertexData I p v = componentAverage (badComponent I R) p := by
  classical
  rw [competitorVertexData,
    if_pos (mem_closedCubeCarrier_iff.mpr ⟨R, hR, hv⟩),
    claimedBadComponent_eq_badComponent hR hv]

/-- **The good branch**: away from the closed bad cubes the datum is `ℓ_p` itself. -/
theorem competitorVertexData_of_notMem_closedCubeCarrier {I : Set (TriadicCube d)}
    (p : Vec d) {v : Vec d} (hv : v ∉ closedCubeCarrier I) :
    competitorVertexData I p v = linearFn p v := by
  classical
  rw [competitorVertexData, if_neg hv]

/-! ## Vertices of a cell of a Whitney cube -/

theorem vertexSet_subset_closedBall_supportCube (T : KuhnCell d) :
    T.vertexSet ⊆
      Metric.closedBall (cubeCenter T.supportCube)
        (Homogenization.cubeRadius T.supportCube) := by
  rintro x ⟨k, rfl⟩
  exact (T.vertex_mem_closedCarrier k).1

private theorem closedBall_subset_of_mem_descendantsAtScale {Q R : TriadicCube d}
    {j : ℤ} (h : R ∈ descendantsAtScale Q j) :
    Metric.closedBall (cubeCenter R) (Homogenization.cubeRadius R) ⊆
      Metric.closedBall (cubeCenter Q) (Homogenization.cubeRadius Q) := by
  by_cases hj : j ≤ Q.scale
  · rw [descendantsAtScale_eq_descendantsAtDepth Q hj] at h
    exact closedBall_subset_closedBall_of_mem_descendantsAtDepth h
  · rw [descendantsAtScale_eq_empty Q (by omega)] at h
    exact absurd h (Finset.notMem_empty _)

/-- **Every vertex of a cell of `□` lies in the closed cube `□`.**  This is the
containment through which the two clauses of `e.hat.linear.properties` see the
cell: subordination to `e.SW.def` says the cell's support cube is a triadic
subcube of the Whitney cube. -/
theorem vertexSet_subset_closedBall_of_mem_descendantsAtScale {Q : TriadicCube d}
    {j : ℤ} {T : KuhnCell d} (hT : T.supportCube ∈ descendantsAtScale Q j) :
    T.vertexSet ⊆
      Metric.closedBall (cubeCenter Q) (Homogenization.cubeRadius Q) :=
  (vertexSet_subset_closedBall_supportCube T).trans
    (closedBall_subset_of_mem_descendantsAtScale hT)

/-! ## Clause 1 of `e.hat.linear.properties` -/

/-- **Clause 1, the vertex form**: on a cell of a *bad* Whitney cube every vertex
lies in that cube, hence is claimed by the cube's own component, hence receives
the one value `⨍_{𝒞} ℓ_p`. -/
theorem eqOn_vertexSet_competitorVertexData_of_mem {I : Set (TriadicCube d)}
    {Q : TriadicCube d} (hQ : Q ∈ I) (p : Vec d) {j : ℤ} {T : KuhnCell d}
    (hT : T.supportCube ∈ descendantsAtScale Q j) :
    Set.EqOn (competitorVertexData I p)
      (fun _ => componentAverage (badComponent I Q) p) T.vertexSet :=
  fun _ hv => competitorVertexData_of_mem_closedBall hQ p
    (vertexSet_subset_closedBall_of_mem_descendantsAtScale hT hv)

/-- **Clause 1 of `e.hat.linear.properties`**: `∇ℓ̂_p = 0` on every cell of every
bad cube.  This is the `hbadF`/`hbadG` shape of `Multiscale.sum_of_a_decomp`
(SubadditiveDecomposition.lean). -/
theorem kuhnSlope_competitorVertexData_eq_zero {I : Set (TriadicCube d)}
    {Q : TriadicCube d} (hQ : Q ∈ I) (p : Vec d) {j : ℤ} {T : KuhnCell d}
    (hT : T.supportCube ∈ descendantsAtScale Q j) :
    kuhnSlope T (competitorVertexData I p) = 0 :=
  kuhnSlope_eq_zero_of_eqOn_vertexSet T
    (eqOn_vertexSet_competitorVertexData_of_mem hQ p hT)

/-! ## The Step-2 vertex bound -/

/-- **The component average deviates from `ℓ_p` by at most `|p|_{ℓ¹} diam(𝒞)`** at
any point of the component's closed carrier.  This is the manuscript's
`|ℓ̂_e(v) − ℓ_e(v)| ≤ |e| diam(𝒞_j)` for `v ∈ V(𝒞_j)`, with the sup-metric
diameter that the proved cluster geometry bounds. -/
theorem abs_componentAverage_sub_linearFn_le {C : Set (TriadicCube d)}
    (hfin : C.Finite) (hne : C.Nonempty) (p : Vec d) {v : Vec d}
    (hv : v ∈ closedCubeCarrier C) :
    |componentAverage C p - linearFn p v| ≤
      vecNormOne p * Metric.diam (closedCubeCarrier C) := by
  set s : Set (Vec d) := closedCubeCarrier C with hs
  have hcpt : IsCompact s := isCompact_closedCubeCarrier hfin
  have hmeas : MeasurableSet s := hcpt.isClosed.measurableSet
  have htop : volume s ≠ ⊤ := hcpt.measure_lt_top.ne
  have hvol : (volume s).toReal ≠ 0 :=
    (ENNReal.toReal_pos (volume_closedCubeCarrier_ne_zero hne) htop).ne'
  letI : IsFiniteMeasure (volumeMeasureOn s) :=
    ⟨by rw [Measure.restrict_apply_univ]; exact lt_top_iff_ne_top.2 htop⟩
  have hint : IntegrableOn (linearFn p) s volume :=
    (continuous_linearFn p).continuousOn.integrableOn_compact hcpt
  have hconst : IntegrableOn (fun _ : Vec d => 2 * linearFn p v) s volume :=
    integrable_const _
  set B : ℝ := vecNormOne p * Metric.diam s with hB
  have hpt : ∀ x ∈ s, |linearFn p x - linearFn p v| ≤ B := by
    intro x hx
    refine le_trans (abs_linearFn_sub_le p x v) ?_
    exact mul_le_mul_of_nonneg_left
      (Metric.dist_le_diam_of_mem hcpt.isBounded hx hv) (vecNormOne_nonneg p)
  have hupper : volumeAverage s (linearFn p) ≤ linearFn p v + B := by
    refine volumeAverage_le_of_le_on hmeas hint hvol fun x hx => ?_
    have := abs_le.mp (hpt x hx)
    linarith [this.2]
  have hflip : volumeAverage s
      ((fun _ : Vec d => 2 * linearFn p v) - linearFn p) ≤ linearFn p v + B := by
    refine volumeAverage_le_of_le_on hmeas (hconst.sub hint) hvol fun x hx => ?_
    have := abs_le.mp (hpt x hx)
    simp only [Pi.sub_apply]
    linarith [this.1]
  rw [volumeAverage_sub hconst hint, volumeAverage_const hvol] at hflip
  rw [componentAverage_apply, ← hs]
  exact abs_le.mpr ⟨by linarith, by linarith⟩

/-- **The Step-2 vertex bound, pointwise**: the deviation of the global datum from
`ℓ_p` is `0` off the closed bad cubes and at most `|p|_{ℓ¹} diam(𝒞)` at a point
claimed by the component `𝒞`. -/
theorem abs_competitorVertexData_sub_linearFn_le {I : Set (TriadicCube d)}
    {R : TriadicCube d} (hR : R ∈ I) (hfin : (badComponent I R).Finite)
    (p : Vec d) {v : Vec d}
    (hv : v ∈ Metric.closedBall (cubeCenter R) (Homogenization.cubeRadius R)) :
    |competitorVertexData I p v - linearFn p v| ≤
      vecNormOne p * Metric.diam (closedCubeCarrier (badComponent I R)) := by
  rw [competitorVertexData_of_mem_closedBall hR p hv]
  exact abs_componentAverage_sub_linearFn_le hfin ⟨R, self_mem_badComponent hR⟩ p
    (closedBall_subset_closedCubeCarrier (self_mem_badComponent hR) hv)

/-- **The Step-2 vertex bound over the active components** (with). -/
theorem abs_competitorVertexData_sub_linearFn_le_of_forall_touching
    {I : Set (TriadicCube d)} {Q : TriadicCube d} {p : Vec d} {D : ℝ} (hD : 0 ≤ D)
    (hact : ∀ R ∈ I, CubeTouch Q R →
      (badComponent I R).Finite ∧
        Metric.diam (closedCubeCarrier (badComponent I R)) ≤ D)
    {v : Vec d}
    (hv : v ∈ Metric.closedBall (cubeCenter Q) (Homogenization.cubeRadius Q)) :
    |competitorVertexData I p v - linearFn p v| ≤ vecNormOne p * D := by
  classical
  by_cases hmem : v ∈ closedCubeCarrier I
  · obtain ⟨R, hR, hvR⟩ := mem_closedCubeCarrier_iff.mp hmem
    obtain ⟨hfin, hdiam⟩ := hact R hR ⟨v, hv, hvR⟩
    exact le_trans (abs_competitorVertexData_sub_linearFn_le hR hfin p hvR)
      (mul_le_mul_of_nonneg_left hdiam (vecNormOne_nonneg p))
  · rw [competitorVertexData_of_notMem_closedCubeCarrier p hmem, sub_self, abs_zero]
    exact mul_nonneg (vecNormOne_nonneg p) hD

/-- **The per-cell gradient consequence of Step 2**: with the active-component
diameter bound `D` at the Whitney cube `□`, every cell of `□` has interpolant
gradient within `2 |p|_{ℓ¹} D / (cell side)` of `p` in each coordinate, hence

```
|∇ℓ̂_p − p|² ≤ d · (2 |p|_{ℓ¹} D / 3^{scale})² .
```

Nothing here is component-local: the estimate is uniform over the active
components at `□`, which is what requires. -/
theorem vecNormSq_kuhnSlope_competitorVertexData_sub_le_of_forall_touching
    {I : Set (TriadicCube d)} {Q : TriadicCube d} {p : Vec d} {D : ℝ} (hD : 0 ≤ D)
    (hact : ∀ R ∈ I, CubeTouch Q R →
      (badComponent I R).Finite ∧
        Metric.diam (closedCubeCarrier (badComponent I R)) ≤ D)
    {j : ℤ} {T : KuhnCell d} (hT : T.supportCube ∈ descendantsAtScale Q j) :
    vecNormSq (kuhnSlope T (competitorVertexData I p) - p) ≤
      (d : ℝ) * (2 * (vecNormOne p * D) / cubeScaleFactor T.supportCube) ^ 2 :=
  vecNormSq_kuhnSlope_sub_le_of_vertexSet_bound T _ p fun _ hv =>
    abs_competitorVertexData_sub_linearFn_le_of_forall_touching hD hact
      (vertexSet_subset_closedBall_of_mem_descendantsAtScale hT hv)

end

end Algsuperdiff.Section3.Provider.Affine
