/-
Copyright (c) 2026 Scott Armstrong. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Scott Armstrong
-/
import Algsuperdiff.Section3.Cutoff.CoefficientLocality
import Algsuperdiff.Section5.Support.BallAverage
import Algsuperdiff.Section5.Support.CoefficientMeasurable
import Algsuperdiff.Section5.Support.SolutionSelector
import Homogenization.Probability.RegCoeffField.SliceMeasurability

/-!
# The coefficient field on a closed cube is a local observable

The local information carried by a region is generated by the integrals of the
entries of the coefficient field against test functions supported in that
region.  It is therefore an integral notion, while the solution of a Dirichlet
problem on the cube is built from the *field* on the cube, an element of the
Banach space of continuous matrix fields on the closed cube.  This module
bridges the two.

Two elementary steps do it.  First, the value of a continuous field at a point
is the limit of its averages over closed balls shrinking to that point, and each
such average is a scalar multiple of the integral of an entry against the
indicator of the ball, hence a local observable as soon as the ball lies in the
region.  Second, a map into the continuous fields on a compact carrier is Borel
measurable as soon as its values at the points of a countable dense subset of
the carrier are measurable: the distance to a fixed field is the supremum of the
pointwise distances over that subset, so the preimage of every closed ball is
measurable, and in a separable metric space the closed balls generate the Borel
sets.

Applied to `y + □̄_n` the two steps give the conclusion for the local
information of the *closed* cube itself: the points of the open cube are dense
in the closed cube, and around each of them a closed ball still fits inside the
cube, so no enlargement of the region is needed.

## Main results

* `closedCubeAt_subset_closure_cubeSetAt` — the closed cube is the closure of the
  open cube.
* `measurable_coefficientCutoff_apply_local` — the value of the coefficient field
  at a point interior to the region is a local observable.
* `measurable_coefficientCutoffRestrict_local` — the coefficient field on the
  closed cube is a local observable of the closed cube.

## References

* ABK26, the cutoff coefficient field of Section 3 and the localized Dirichlet
  problems of Section 5.1.
-/

namespace Algsuperdiff.Section5.Support

open Algsuperdiff.Section3
open Homogenization MeasureTheory Filter
open scoped Matrix.Norms.Elementwise Topology

noncomputable section

variable {d : ℕ}

/-! ## 1. Borel measurability from the preimages of closed balls -/

private theorem measurableSet_preimage_isOpen_of_closedBall {Omega X : Type*}
    (mOmega : MeasurableSpace Omega) [PseudoMetricSpace X]
    [TopologicalSpace.SeparableSpace X] {F : Omega → X}
    (hF : ∀ (c : X) (r : ℝ), MeasurableSet[mOmega] (F ⁻¹' Metric.closedBall c r))
    {V : Set X} (hV : IsOpen V) : MeasurableSet[mOmega] (F ⁻¹' V) := by
  obtain ⟨D, hDc, hDd⟩ := TopologicalSpace.exists_countable_dense X
  have := hDc.to_subtype
  have hEq : F ⁻¹' V =
      ⋃ (c : ↥D) (q : ℚ) (_ : Metric.closedBall (c : X) (q : ℝ) ⊆ V),
        F ⁻¹' Metric.closedBall (c : X) (q : ℝ) := by
    refine Set.Subset.antisymm (fun w hw => ?_) ?_
    · obtain ⟨eps, heps, hball⟩ := Metric.isOpen_iff.1 hV (F w) hw
      obtain ⟨c, hcD, hc⟩ :=
        Metric.mem_closure_iff.1 (hDd (F w)) (eps / 4) (by linarith)
      obtain ⟨q, hq1, hq2⟩ := exists_rat_btwn (show eps / 4 < eps / 3 by linarith)
      refine Set.mem_iUnion.2 ⟨⟨c, hcD⟩, Set.mem_iUnion.2 ⟨q, Set.mem_iUnion.2 ⟨?_, ?_⟩⟩⟩
      · intro z hz
        refine hball (Metric.mem_ball.2 ?_)
        have h1 : dist z c ≤ (q : ℝ) := Metric.mem_closedBall.1 hz
        have h2 : dist c (F w) < eps / 4 := by rwa [dist_comm] at hc
        calc dist z (F w) ≤ dist z c + dist c (F w) := dist_triangle _ _ _
          _ < (q : ℝ) + eps / 4 := by linarith
          _ < eps := by linarith
      · exact Metric.mem_closedBall.2 (le_of_lt (hc.trans hq1))
    · refine Set.iUnion_subset fun c => Set.iUnion_subset fun q =>
        Set.iUnion_subset fun hsub => Set.preimage_mono hsub
  rw [hEq]
  exact MeasurableSet.iUnion fun c => MeasurableSet.iUnion fun q =>
    MeasurableSet.iUnion fun _ => hF _ _

private theorem measurable_of_preimage_closedBall {Omega X : Type*}
    (mOmega : MeasurableSpace Omega) [PseudoMetricSpace X]
    [TopologicalSpace.SeparableSpace X] [MeasurableSpace X] [BorelSpace X] {F : Omega → X}
    (hF : ∀ (c : X) (r : ℝ), MeasurableSet[mOmega] (F ⁻¹' Metric.closedBall c r)) :
    Measurable[mOmega] F := by
  have key : @Measurable Omega X mOmega
      (MeasurableSpace.generateFrom {s : Set X | IsOpen s}) F :=
    measurable_generateFrom fun _t ht =>
      measurableSet_preimage_isOpen_of_closedBall mOmega hF ht
  intro s hs
  rw [BorelSpace.measurable_eq (α := X)] at hs
  exact key hs

/-! ## 2. Measurability into the continuous fields on a compact carrier -/

private theorem measurable_continuousMap_of_eval {Omega : Type*}
    (mOmega : MeasurableSpace Omega) {K : Set (Vec d)} [CompactSpace ↥K]
    {P : Set (Vec d)} (hPc : P.Countable) (hPK : P ⊆ K) (hPdense : K ⊆ closure P)
    {F : Omega → C(↥K, Mat d)}
    (hF : ∀ z : ↥K, (z : Vec d) ∈ P → Measurable[mOmega] fun w => F w z) :
    Measurable[mOmega] F := by
  have : SecondCountableTopology C(↥K, Mat d) := inferInstance
  have hEc : ((Subtype.val : ↥K → Vec d) ⁻¹' P).Countable :=
    hPc.preimage Subtype.val_injective
  have himg : (Subtype.val : ↥K → Vec d) '' ((Subtype.val : ↥K → Vec d) ⁻¹' P) = P := by
    refine Set.Subset.antisymm ?_ ?_
    · rintro t ⟨z, hz, rfl⟩
      exact hz
    · intro t ht
      exact ⟨⟨t, hPK ht⟩, ht, rfl⟩
  have hEd : Dense ((Subtype.val : ↥K → Vec d) ⁻¹' P) := by
    rw [Subtype.dense_iff, himg]
    exact hPdense
  refine measurable_of_preimage_closedBall mOmega fun g r => ?_
  rcases lt_or_ge r 0 with hr | hr
  · rw [Metric.closedBall_eq_empty.2 hr, Set.preimage_empty]
    exact MeasurableSet.empty
  · have hEqset : F ⁻¹' Metric.closedBall g r =
        ⋂ z ∈ (Subtype.val : ↥K → Vec d) ⁻¹' P, {w | dist (F w z) (g z) ≤ r} := by
      ext w
      simp only [Set.mem_preimage, Metric.mem_closedBall, Set.mem_iInter, Set.mem_ofPred_eq]
      constructor
      · intro h z _
        exact (ContinuousMap.dist_le hr).1 h z
      · intro h
        refine (ContinuousMap.dist_le hr).2 fun z => ?_
        have hclosed : IsClosed {z : ↥K | dist (F w z) (g z) ≤ r} :=
          isClosed_le ((F w).continuous.dist g.continuous) continuous_const
        have hsub : (Set.univ : Set ↥K) ⊆ {z : ↥K | dist (F w z) (g z) ≤ r} := by
          rw [← hEd.closure_eq]
          exact hclosed.closure_subset_iff.2 fun z hz => h z hz
        exact hsub (Set.mem_univ z)
    rw [hEqset]
    refine MeasurableSet.biInter hEc fun z hz => ?_
    have hdist : Measurable[mOmega] fun w => dist (F w z) (g z) :=
      (continuous_id.dist continuous_const).measurable.comp (hF z hz)
    exact measurableSet_le hdist measurable_const

/-! ## 3. The closed cube is the closure of the open cube -/

/-- **The closed cube is the closure of the open cube.**  Contracting a point
of the closed cube towards the centre lands in the open cube and moves it as
little as one likes. -/
theorem closedCubeAt_subset_closure_cubeSetAt (y : Vec d) (n : ℤ) :
    closedCubeAt y n ⊆ closure (cubeSetAt y n) := by
  intro x hx
  rw [Metric.mem_closure_iff]
  intro eps heps
  set t : ℝ := 1 - min (1 / 2) (eps / (2 * (‖x - y‖ + 1))) with ht
  have hnormnn : (0 : ℝ) ≤ ‖x - y‖ := norm_nonneg _
  have hden : (0 : ℝ) < 2 * (‖x - y‖ + 1) := by linarith
  have hminpos : (0 : ℝ) < min (1 / 2) (eps / (2 * (‖x - y‖ + 1))) :=
    lt_min (by norm_num) (by positivity)
  have hminle : min (1 / 2) (eps / (2 * (‖x - y‖ + 1))) ≤ 1 / 2 := min_le_left _ _
  have ht0 : (0 : ℝ) ≤ t := by rw [ht]; linarith
  have ht1 : t < 1 := by rw [ht]; linarith
  refine ⟨y + t • (x - y), ?_, ?_⟩
  · rw [mem_cubeSetAt_iff_forall_coord]
    intro i
    have hL : (0 : ℝ) < (1 / 2 : ℝ) * (3 : ℝ) ^ n := by
      have : (0 : ℝ) < (3 : ℝ) ^ n := zpow_pos (by norm_num) n
      linarith
    have hxi : |x i - y i| ≤ (1 / 2 : ℝ) * (3 : ℝ) ^ n := hx i
    have hcoord : (y + t • (x - y)) i - y i = t * (x i - y i) := by
      simp [Pi.add_apply, Pi.smul_apply, Pi.sub_apply]
    rw [hcoord]
    have habs : |t * (x i - y i)| ≤ t * ((1 / 2 : ℝ) * (3 : ℝ) ^ n) := by
      rw [abs_mul, abs_of_nonneg ht0]
      exact mul_le_mul_of_nonneg_left hxi ht0
    have hlt : t * ((1 / 2 : ℝ) * (3 : ℝ) ^ n) < (1 / 2 : ℝ) * (3 : ℝ) ^ n := by
      nlinarith [hL, ht1]
    have hlt' := abs_lt.1 (lt_of_le_of_lt habs hlt)
    constructor <;> linarith [hlt'.1, hlt'.2]
  · have hsub : (y + t • (x - y)) - x = (t - 1) • (x - y) := by
      funext i
      simp only [Pi.sub_apply, Pi.add_apply, Pi.smul_apply, smul_eq_mul]
      ring
    rw [dist_comm, dist_eq_norm, hsub, norm_smul, Real.norm_eq_abs]
    have habs : |t - 1| = min (1 / 2) (eps / (2 * (‖x - y‖ + 1))) := by
      rw [ht]
      rw [show (1 - min (1 / 2) (eps / (2 * (‖x - y‖ + 1))) - 1) =
        -min (1 / 2) (eps / (2 * (‖x - y‖ + 1))) by ring, abs_neg,
        abs_of_nonneg hminpos.le]
    rw [habs]
    have hkey : min (1 / 2) (eps / (2 * (‖x - y‖ + 1))) * ‖x - y‖ ≤
        eps / (2 * (‖x - y‖ + 1)) * ‖x - y‖ :=
      mul_le_mul_of_nonneg_right (min_le_right _ _) hnormnn
    have hfrac : eps / (2 * (‖x - y‖ + 1)) * ‖x - y‖ < eps := by
      rw [div_mul_eq_mul_div, div_lt_iff₀ hden]
      nlinarith [heps, hnormnn]
    linarith

/-! ## 4. Local measurability of the values of the coefficient field -/

private theorem measurable_of_tendsto_real {Omega : Type*} [MeasurableSpace Omega]
    {f : ℕ → Omega → ℝ} {g : Omega → ℝ} (hf : ∀ k, Measurable (f k))
    (hlim : ∀ w, Tendsto (fun k => f k w) atTop (𝓝 (g w))) : Measurable g :=
  measurable_of_tendsto_metrizable hf (tendsto_pi_nhds.2 hlim)

/-- **The value of the coefficient field at a point is a local observable.**
Around a point at positive distance from the complement of the local set the
field is the limit of its averages over shrinking closed balls, and each such
average is a scalar multiple of a supported integral test. -/
theorem measurable_coefficientCutoff_apply_local (M : ABKModel d) (m : ℤ) (U : Set (Vec d))
    {z : Vec d} {rho : ℝ} (hrho : 0 < rho) (hball : Metric.closedBall z rho ⊆ U) :
    Measurable[Cutoff.cutoffSampleLocalSigma M m U]
      fun omega : Cutoff.CutoffSample d => Cutoff.coefficientCutoff M.nu m omega z := by
  have : NeZero d := Provider.Orlicz.neZero_of_model M
  let mLoc : MeasurableSpace (Cutoff.CutoffSample d) :=
    Cutoff.cutoffSampleLocalSigma M m U
  set r : ℕ → ℝ := fun k => rho * (1 / (k + 1 : ℝ)) with hrdef
  have hrpos : ∀ k, 0 < r k := fun k => by rw [hrdef]; positivity
  have hrle : ∀ k, r k ≤ rho := by
    intro k
    have hk : (0 : ℝ) ≤ (k : ℝ) := Nat.cast_nonneg k
    have h1 : (1 : ℝ) / (k + 1 : ℝ) ≤ 1 := by
      rw [div_le_one (by linarith)]
      linarith
    rw [hrdef]
    calc rho * (1 / (k + 1 : ℝ)) ≤ rho * 1 := mul_le_mul_of_nonneg_left h1 hrho.le
      _ = rho := mul_one rho
  have hr0 : Tendsto r atTop (𝓝 0) := by
    have h := tendsto_one_div_add_atTop_nhds_zero_nat.const_mul rho
    simpa only [hrdef, mul_zero] using h
  have hsub : ∀ k, Metric.closedBall z (r k) ⊆ U := fun k =>
    subset_trans (Metric.closedBall_subset_closedBall (hrle k)) hball
  refine measurable_matrix_of_entries fun i j => ?_
  have hmeas : ∀ k, Measurable fun omega : Cutoff.CutoffSample d =>
      avgMat (Metric.closedBall z (r k)) (Cutoff.coefficientCutoff M.nu m omega) i j := by
    intro k
    have hentry : Measurable fun A : Mat d => A i j := (measurable_pi_apply i).eval
    have havg : Measurable[Homogenization.LocalSigmaR U]
        (avgMat (Metric.closedBall z (r k))) :=
      measurable_avgMat (isCompact_closedBall z (r k)) measurableSet_closedBall (hsub k)
    exact (hentry.comp havg).comp (Cutoff.measurable_coefficientCutoff_local M m U)
  refine measurable_of_tendsto_real hmeas fun omega => ?_
  have hcont : Continuous fun x : Vec d =>
      Cutoff.coefficientCutoff M.nu m omega x i j := by
    simp only [Cutoff.coefficientCutoff_apply, Matrix.add_apply]
    exact continuous_const.add (Cutoff.continuous_cutoff_entry m omega i j)
  have hbase := tendsto_setAverage_ball_of_continuousOn (U := Set.univ) isOpen_univ
    hcont.continuousOn (Set.mem_univ z) hrpos hr0
  refine hbase.congr fun k => ?_
  rw [avgMat_entry_eq_setAverage, ← setAverage_ball_eq_closedBall]

/-! ## 5. The coefficient field on the closed cube -/

/-- **The coefficient field restricted to the closed cube is measurable for the
local information of the closed cube.**  Its values at the points of the open
cube are limits of averages over closed balls contained in the cube, and those
points are dense in the closed cube. -/
theorem measurable_coefficientCutoffRestrict_local (M : ABKModel d) (m : ℤ) (y : Vec d)
    (n : ℤ) :
    Measurable[Cutoff.cutoffSampleLocalSigma M m (closedCubeAt y n)]
      (coefficientCutoffRestrict M.nu m (closedCubeAt y n)) := by
  obtain ⟨D, hDc, hDd⟩ := TopologicalSpace.exists_countable_dense (Vec d)
  have hPc : (D ∩ cubeSetAt y n).Countable := hDc.mono Set.inter_subset_left
  have hPK : D ∩ cubeSetAt y n ⊆ closedCubeAt y n :=
    fun x hx => cubeSetAt_subset_closedCubeAt y n hx.2
  have hPdense : closedCubeAt y n ⊆ closure (D ∩ cubeSetAt y n) := by
    refine subset_trans (closedCubeAt_subset_closure_cubeSetAt y n) ?_
    have hopen : cubeSetAt y n ⊆ closure (cubeSetAt y n ∩ D) :=
      hDd.open_subset_closure_inter (isOpen_cubeSetAt y n)
    rw [Set.inter_comm] at hopen
    calc closure (cubeSetAt y n) ⊆ closure (closure (D ∩ cubeSetAt y n)) :=
          closure_mono hopen
      _ = closure (D ∩ cubeSetAt y n) := closure_closure
  refine measurable_continuousMap_of_eval _ hPc hPK hPdense fun z hz => ?_
  obtain ⟨delta, hdelta, hballsub⟩ :=
    Metric.isOpen_iff.1 (isOpen_cubeSetAt y n) (z : Vec d) hz.2
  have hclosed : Metric.closedBall (z : Vec d) (delta / 2) ⊆ closedCubeAt y n := by
    refine subset_trans ?_ (subset_trans hballsub (cubeSetAt_subset_closedCubeAt y n))
    intro w hw
    exact Metric.mem_ball.2
      (lt_of_le_of_lt (Metric.mem_closedBall.1 hw) (by linarith))
  exact measurable_coefficientCutoff_apply_local M m (closedCubeAt y n)
    (by linarith : (0:ℝ) < delta / 2) hclosed

end

end Algsuperdiff.Section5.Support
