import Algsuperdiff.Section3.Provider.Multiscale.RandomHsepWaveEnvelope
import Algsuperdiff.Section3.Provider.Stream.IncrementTranslation

/-!
# One random-`hsep` wave event for every upper cutoff

The fixed-cutoff wave estimate cannot be union-bounded over all cutoff indices
after selecting the random separation profile: doing that would charge the
same `hsep` tail infinitely many times.  This file performs the operations in
the opposite order.  For each deterministic separation profile it aggregates
the wave failures at `L₀ + r` using the growing amplitude `t + r`; only then
does it select the sample-dependent `hsep` profile through the existing finite
random-index decomposition.

The resulting event controls every integer cutoff `L ≥ L₀`, has an explicit
`Gamma₂` price, and transports exactly under cutoff-sample stationarity.  The
common `hsep` tail occurs once in `randomHsepAllLWavePrice`.
-/

namespace Algsuperdiff.Section3.Provider.Multiscale

open MeasureTheory
open Homogenization Homogenization.Book
open Algsuperdiff.Frozen.Assumptions
open Algsuperdiff.Section3
open Algsuperdiff.Section3.Cutoff
open Algsuperdiff.Section3.Provider.BadEvents
open Algsuperdiff.Section3.Provider.Percolation
open Algsuperdiff.Section3.Provider.Stream
open Algsuperdiff.Section3.Provider.Whitney

noncomputable section

variable {d : ℕ}

/-- The wave-envelope amplitude at cutoff depth `r`.  Its linear growth makes
the resulting `Gamma₂` failure probabilities summable over `r`. -/
def allLWaveAmplitude (t : ℝ) (r : ℕ) : ℝ := t + r

/-- The geometric sum of the fixed-profile wave prices generated by
`allLWaveAmplitude`. -/
def allLWavePrice (t : ℝ) : ℝ :=
  2 * (IndependentSums.gammaSigma 2 t)⁻¹ * (1 - Real.exp (-1))⁻¹

private theorem gammaSigma_two_allLWaveAmplitude_inv_le
    {t : ℝ} (ht : 1 ≤ t) (r : ℕ) :
    (IndependentSums.gammaSigma 2 (allLWaveAmplitude t r))⁻¹ ≤
      (IndependentSums.gammaSigma 2 t)⁻¹ * Real.exp (-1) ^ r := by
  have hr0 : (0 : ℝ) ≤ r := Nat.cast_nonneg r
  have htr : (r : ℝ) ≤ t * r := by
    nlinarith [mul_nonneg (sub_nonneg.mpr ht) hr0]
  have hsq : t ^ 2 + (r : ℝ) ≤ (t + (r : ℝ)) ^ 2 := by
    nlinarith [sq_nonneg (r : ℝ)]
  simp only [IndependentSums.gammaSigma, allLWaveAmplitude]
  rw [show (2 : ℝ) = ((2 : ℕ) : ℝ) by norm_num, Real.rpow_natCast,
    Real.rpow_natCast, ← Real.exp_neg, ← Real.exp_neg, ← Real.exp_nat_mul]
  rw [← Real.exp_add]
  apply Real.exp_le_exp.2
  have hneg := neg_le_neg hsq
  ring_nf at hneg ⊢
  exact hneg.trans_eq (by
    simp only [sub_eq_add_neg, add_comm])

private theorem allLWavePrice_nonneg (t : ℝ) : 0 ≤ allLWavePrice t := by
  unfold allLWavePrice
  have hq : Real.exp (-1) < 1 := by
    have := Real.exp_lt_exp.2 (show (-1 : ℝ) < 0 by norm_num)
    simpa only [Real.exp_zero] using this
  have hden : 0 ≤ (1 - Real.exp (-1))⁻¹ := inv_nonneg.mpr (sub_nonneg.mpr hq.le)
  exact mul_nonneg (mul_nonneg (by norm_num)
    (inv_nonneg.mpr (by
      simp only [IndependentSums.gammaSigma]
      exact (Real.exp_pos _).le))) hden

/-- For a deterministic Whitney profile, the probability of violating some
wave envelope at some cutoff `L₀ + r` is at most `allLWavePrice t`. -/
theorem measureReal_exists_allLCubeSupBound_gt_le
    (hd : 2 ≤ d) (M : ABKModel d) (n : ℤ) (hn : ℕ → ℕ)
    {L₀ : ℤ} (hnL₀ : n ≤ L₀) {t : ℝ} (ht : 1 ≤ t) :
    (cutoffSampleLaw M).toMeasure.real
        {omega : CutoffSample d | ∃ r : ℕ, ∃ k : ℕ,
          ∃ Q ∈ whitneyLayer (d := d) n hn k,
            whitneyWaveLayerScale M n hn k (L₀ + (r : ℤ)) * allLWaveAmplitude t r <
              cubeSupBound Q Q.scale (L₀ + (r : ℤ)) omega.1} ≤
      allLWavePrice t := by
  classical
  let μ := (cutoffSampleLaw M).toMeasure
  let E : ℕ → Set (CutoffSample d) := fun r =>
    {omega : CutoffSample d | ∃ k : ℕ,
      ∃ Q ∈ whitneyLayer (d := d) n hn k,
        whitneyWaveLayerScale M n hn k (L₀ + (r : ℤ)) * allLWaveAmplitude t r <
          cubeSupBound Q Q.scale (L₀ + (r : ℤ)) omega.1}
  let A : ℝ := 2 * (IndependentSums.gammaSigma 2 t)⁻¹
  let q : ℝ := Real.exp (-1)
  have hq0 : 0 ≤ q := (Real.exp_pos _).le
  have hq1 : q < 1 := by
    dsimp [q]
    have := Real.exp_lt_exp.2 (show (-1 : ℝ) < 0 by norm_num)
    simpa only [Real.exp_zero] using this
  have hA0 : 0 ≤ A := by dsimp [A]; positivity
  have hEr : ∀ r : ℕ, μ.real (E r) ≤ A * q ^ r := by
    intro r
    have hnL : n ≤ L₀ + (r : ℤ) := by omega
    have htr : 1 ≤ allLWaveAmplitude t r := by
      unfold allLWaveAmplitude
      have hr0 : (0 : ℝ) ≤ r := Nat.cast_nonneg r
      linarith
    have hbase := measureReal_exists_cubeSupBound_gt_le hd M n hn hnL htr
    calc
      μ.real (E r) ≤
          2 * (IndependentSums.gammaSigma 2 (allLWaveAmplitude t r))⁻¹ := by
        simpa [μ, E] using hbase
      _ ≤ 2 * ((IndependentSums.gammaSigma 2 t)⁻¹ * Real.exp (-1) ^ r) :=
        mul_le_mul_of_nonneg_left (gammaSigma_two_allLWaveAmplitude_inv_le ht r)
          (by norm_num)
      _ = A * q ^ r := by simp [A, q]; ring
  have hsummable : Summable fun r : ℕ => A * q ^ r :=
    (summable_geometric_of_lt_one hq0 hq1).mul_left A
  have hmeasure : μ (⋃ r, E r) ≤ ENNReal.ofReal (allLWavePrice t) := by
    rw [show allLWavePrice t = ∑' r : ℕ, A * q ^ r by
      simp only [allLWavePrice, A, q]
      rw [tsum_mul_left, tsum_geometric_of_lt_one hq0 hq1],
      ENNReal.ofReal_tsum_of_nonneg (fun r => mul_nonneg hA0 (pow_nonneg hq0 r)) hsummable]
    exact (measure_iUnion_le _).trans (ENNReal.tsum_le_tsum fun r =>
      (ENNReal.le_ofReal_iff_toReal_le (measure_ne_top _ _) (mul_nonneg hA0 (pow_nonneg hq0 r))).2
        (hEr r))
  have htoReal := ENNReal.toReal_mono ENNReal.ofReal_ne_top hmeasure
  rw [ENNReal.toReal_ofReal (allLWavePrice_nonneg t)] at htoReal
  have hset :
      {omega : CutoffSample d | ∃ r : ℕ, ∃ k : ℕ,
        ∃ Q ∈ whitneyLayer (d := d) n hn k,
          whitneyWaveLayerScale M n hn k (L₀ + (r : ℤ)) * allLWaveAmplitude t r <
            cubeSupBound Q Q.scale (L₀ + (r : ℤ)) omega.1} = ⋃ r, E r := by
    ext omega
    simp [E]
  rw [hset]
  exact htoReal

/-- The one-event literal wave envelope on every cutoff index `L₀ + r`,
with amplitudes whose resulting failure prices are summable in `r`. -/
def randomHsepAllLWaveEnvelope (M : ABKModel d) (n : ℤ)
    (E b : ℝ) (k₀ : ℕ) (L₀ : ℤ) (t : ℝ) (omega : CutoffSample d) : Prop :=
  ∀ (r k : ℕ), ∀ Q ∈ whitneyLayer (d := d) n
      (whitneyScale M n E b k₀ omega) k,
    cubeSupBound Q Q.scale (L₀ + (r : ℤ)) omega.1 ≤
      whitneyWaveLayerScale M n (whitneyScale M n E b k₀ omega) k
        (L₀ + (r : ℤ)) * allLWaveAmplitude t r

/-- The explicit price of the random-profile all-cutoff wave event.  The
separation tail is charged once, after all cutoff depths have been summed for
each deterministic profile. -/
def randomHsepAllLWavePrice (sigma b : ℝ) (H : ℕ) (t : ℝ) : ℝ :=
  ((H : ℝ) + 1) * allLWavePrice t +
    hsepTailConst sigma b *
      Real.exp (-((3 : ℝ) ^ ((1 - sigma) * b * (H : ℝ))))

/-- The tail of `hsep` with the four direct preliminary probability gates exposed,
rather than the stronger packaged admissibility consequence used by the
compatibility A. -/
theorem measureReal_lt_hsep_le_of_gates (M : ABKModel d) {m : ℤ}
    {E sigma b : ℝ} (hd : 2 ≤ d) (hE : 1 ≤ E)
    (hS : Algsuperdiff.Frozen.Section3.inductionState M (m - 1) ⟨E, hE⟩)
    (hsigma0 : 0 < sigma) (hsigma : sigma ≤ 1 / 2)
    (hb0 : 0 < b) (hb : b ≤ 1 / 8)
    (hEexp : Real.exp (badClustersConst d / sigma) ≤ E)
    (hE4 : 4 ≤ E) (hunit : unitGate M) (hgamma20 : M.gamma ≤ 1 / 20)
    (hinvSq : E⁻¹ ^ 2 ≤ Algsuperdiff.Section3.Disorder.cstar M)
    (hEb : badClustersConst d / b ≤ E)
    (hgamma : M.gamma ≤ E ^ (-5 : ℤ)) {H : ℕ} (hH : 1 ≤ H) :
    (cutoffSampleLaw M).toMeasure.real {omega | H < hsep M m E b omega} ≤
      hsepTailConst sigma b *
        Real.exp (-((3 : ℝ) ^ ((1 - sigma) * b * (H : ℝ)))) := by
  refine le_trans (measureReal_mono ?_ (measure_ne_top _ _))
    (measureReal_scaleSeparationFail_le_of_gates M hd hE hS hsigma0 hsigma
      hb0 hb hEexp hE4 hunit hgamma20 hinvSq hEb hgamma hH)
  rw [scaleSeparationFail_eq M m E b hH]
  intro omega homega
  simp only [Set.mem_setOf_eq] at homega ⊢
  omega

/-- The random-profile all-cutoff failure price.  The wave failures are first
summed over the cutoff depth for each deterministic profile, and the common
`hsep` tail is then charged exactly once. -/
theorem measureReal_not_randomHsepAllLWaveEnvelope_le
    (hd : 2 ≤ d) (M : ABKModel d) {n : ℤ} {E sigma b : ℝ}
    (hE : 1 ≤ E)
    (hS : Algsuperdiff.Frozen.Section3.inductionState M (n - 1) ⟨E, hE⟩)
    (hsigma0 : 0 < sigma) (hsigma : sigma ≤ 1 / 2)
    (hb0 : 0 < b) (hb : b ≤ 1 / 8)
    (hEexp : Real.exp (badClustersConst d / sigma) ≤ E)
    (hE4 : 4 ≤ E) (hunit : unitGate M) (hgamma20 : M.gamma ≤ 1 / 20)
    (hinvSq : E⁻¹ ^ 2 ≤ Algsuperdiff.Section3.Disorder.cstar M)
    (hEb : badClustersConst d / b ≤ E)
    (hgamma : M.gamma ≤ E ^ (-5 : ℤ)) (k₀ : ℕ)
    {L₀ : ℤ} (hnL₀ : n ≤ L₀) {H : ℕ} (hH : 1 ≤ H)
    {t : ℝ} (ht : 1 ≤ t) :
    (cutoffSampleLaw M).toMeasure.real
        {omega : CutoffSample d |
          ¬ randomHsepAllLWaveEnvelope M n E b k₀ L₀ t omega} ≤
      randomHsepAllLWavePrice sigma b H t := by
  classical
  let B : ℕ → Set (CutoffSample d) := fun h =>
    {omega : CutoffSample d | ∃ r : ℕ, ∃ k : ℕ,
      ∃ Q ∈ whitneyLayer (d := d) n (whitneyScaleSeq b h k₀) k,
        whitneyWaveLayerScale M n (whitneyScaleSeq b h k₀) k
              (L₀ + (r : ℤ)) * allLWaveAmplitude t r <
          cubeSupBound Q Q.scale (L₀ + (r : ℤ)) omega.1}
  have hfixed : ∀ h : ℕ,
      (cutoffSampleLaw M).toMeasure.real (B h) ≤ allLWavePrice t := by
    intro h
    simpa [B] using
      (measureReal_exists_allLCubeSupBound_gt_le hd M n
        (whitneyScaleSeq b h k₀) hnL₀ ht)
  have hdiag := measureReal_mem_randomIndex_le
    (mu := (cutoffSampleLaw M).toMeasure) B (fun omega => hsep M n E b omega) H
  have hsum :
      (∑ h ∈ Finset.range (H + 1),
          (cutoffSampleLaw M).toMeasure.real (B h)) ≤
        ((H : ℝ) + 1) * allLWavePrice t := by
    calc
      (∑ h ∈ Finset.range (H + 1),
          (cutoffSampleLaw M).toMeasure.real (B h)) ≤
          ∑ _h ∈ Finset.range (H + 1), allLWavePrice t :=
        Finset.sum_le_sum fun h _ => hfixed h
      _ = ((H : ℝ) + 1) * allLWavePrice t := by
        rw [Finset.sum_const, Finset.card_range, nsmul_eq_mul]
        push_cast
        rfl
  have htail := measureReal_lt_hsep_le_of_gates M hd hE hS hsigma0 hsigma hb0 hb
    hEexp hE4 hunit hgamma20 hinvSq hEb hgamma hH
  have hset :
      {omega : CutoffSample d |
        ¬ randomHsepAllLWaveEnvelope M n E b k₀ L₀ t omega} =
        {omega | omega ∈ B (hsep M n E b omega)} := by
    ext omega
    simp only [randomHsepAllLWaveEnvelope, B, whitneyScale,
      Set.mem_setOf_eq]
    push_neg
    rfl
  rw [hset]
  exact hdiag.trans (by
    unfold randomHsepAllLWavePrice
    exact add_le_add hsum htail)


/-- Measurability of `hsep`, re-derived from the measurable strict upper
level sets exported by `WaveOscillations`. -/
private theorem measurable_hsep_for_allLWave
    (M : ABKModel d) (n : ℤ) (E b : ℝ) :
    Measurable (hsep M n E b) := by
  refine measurable_to_countable' fun k => ?_
  cases k with
  | zero =>
      have hset : hsep M n E b ⁻¹' {0} =
          {omega : CutoffSample d | 0 < hsep M n E b omega}ᶜ := by
        ext omega
        simp only [Set.mem_preimage, Set.mem_singleton_iff, Set.mem_compl_iff,
          Set.mem_setOf_eq]
        omega
      rw [hset]
      exact (measurableSet_lt_hsep M n E b 0).compl
  | succ j =>
      have hset : hsep M n E b ⁻¹' {j + 1} =
          {omega : CutoffSample d | j < hsep M n E b omega} ∩
            {omega : CutoffSample d | j + 1 < hsep M n E b omega}ᶜ := by
        ext omega
        simp only [Set.mem_preimage, Set.mem_singleton_iff, Set.mem_inter_iff,
          Set.mem_compl_iff, Set.mem_setOf_eq]
        omega
      rw [hset]
      exact (measurableSet_lt_hsep M n E b j).inter
        (measurableSet_lt_hsep M n E b (j + 1)).compl

/-- The all-cutoff random-profile wave event is measurable, so stationarity
can transport its exact probability rather than only an outer bound. -/
theorem measurableSet_randomHsepAllLWaveEnvelope
    (M : ABKModel d) (n : ℤ) (E b : ℝ) (k₀ : ℕ) (L₀ : ℤ) (t : ℝ) :
    MeasurableSet {omega : CutoffSample d |
      randomHsepAllLWaveEnvelope M n E b k₀ L₀ t omega} := by
  classical
  let D : ℕ → Set (CutoffSample d) := fun h =>
    {omega : CutoffSample d | ∀ (r k : ℕ),
      ∀ Q ∈ whitneyLayer (d := d) n (whitneyScaleSeq b h k₀) k,
        cubeSupBound Q Q.scale (L₀ + (r : ℤ)) omega.1 ≤
          whitneyWaveLayerScale M n (whitneyScaleSeq b h k₀) k
            (L₀ + (r : ℤ)) * allLWaveAmplitude t r}
  have hD : ∀ h : ℕ, MeasurableSet (D h) := by
    intro h
    have hsetD : D h =
        ⋂ r : ℕ, ⋂ k : ℕ,
          ⋂ Q ∈ whitneyLayer (d := d) n (whitneyScaleSeq b h k₀) k,
            {omega : CutoffSample d |
              cubeSupBound Q Q.scale (L₀ + (r : ℤ)) omega.1 ≤
                whitneyWaveLayerScale M n (whitneyScaleSeq b h k₀) k
                  (L₀ + (r : ℤ)) * allLWaveAmplitude t r} := by
      ext omega
      simp [D]
    rw [hsetD]
    refine MeasurableSet.iInter fun (r : ℕ) =>
      MeasurableSet.iInter fun (k : ℕ) => ?_
    refine MeasurableSet.biInter
      (whitneyLayer (d := d) n (whitneyScaleSeq b h k₀) k).countable_toSet
      fun (Q : TriadicCube d) _ => ?_
    exact measurableSet_le
      ((measurable_cubeSupBound Q Q.scale (L₀ + (r : ℤ))).comp
        measurable_subtype_coe)
      measurable_const
  have hset :
      {omega : CutoffSample d |
        randomHsepAllLWaveEnvelope M n E b k₀ L₀ t omega} =
        ⋂ h : ℕ, ({omega : CutoffSample d | hsep M n E b omega ≠ h} ∪ D h) := by
    ext omega
    simp only [Set.mem_setOf_eq, Set.mem_iInter, Set.mem_union]
    constructor
    · intro hgood h
      by_cases heq : hsep M n E b omega = h
      · right
        subst h
        simpa only [D, randomHsepAllLWaveEnvelope, whitneyScale]
          using hgood
      · exact Or.inl heq
    · intro hall
      have hh := hall (hsep M n E b omega)
      rcases hh with hne | hgood
      · exact (hne rfl).elim
      · simpa only [D, randomHsepAllLWaveEnvelope, whitneyScale]
          using hgood
  rw [hset]
  refine MeasurableSet.iInter fun h => MeasurableSet.union ?_ (hD h)
  exact ((measurable_hsep_for_allLWave M n E b)
    (measurableSet_singleton h)).compl


end

end Algsuperdiff.Section3.Provider.Multiscale
